/**
 * Generate `src/data/site/publicImageManifest.ts` from files under `public/images`.
 * Used by middleware to rewrite missing infographic/hero URLs to a fallback (Ahrefs 404s).
 *
 * Run: `npx tsx scripts/generate-public-image-manifest.ts`
 * Hooked from `prebuild` so Vercel stays in sync.
 */
import { mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const PUBLIC_IMAGES = join(process.cwd(), "public", "images");
const OUT = join(process.cwd(), "src", "data", "site", "publicImageManifest.ts");

function walk(dir: string, acc: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) walk(full, acc);
    else if (/\.(png|jpe?g|webp|svg|gif|avif)$/i.test(name)) {
      const rel = relative(join(process.cwd(), "public"), full).split("\\").join("/");
      acc.push(`/${rel}`);
    }
  }
  return acc;
}

const paths = walk(PUBLIC_IMAGES).sort((a, b) => a.localeCompare(b));
mkdirSync(join(process.cwd(), "src", "data", "site"), { recursive: true });

const body = `/**
 * Auto-generated by \`scripts/generate-public-image-manifest.ts\`.
 * Do not edit by hand — rerun the script after adding/removing public images.
 *
 * ${paths.length} paths · generated ${new Date().toISOString()}
 */
export const PUBLIC_IMAGE_PATHS: ReadonlySet<string> = new Set([
${paths.map((p) => `  ${JSON.stringify(p)},`).join("\n")}
]);

export function publicImageExists(pathname: string): boolean {
  if (!pathname) return false;
  const p = pathname.startsWith("/") ? pathname : \`/\${pathname}\`;
  return PUBLIC_IMAGE_PATHS.has(p);
}
`;

writeFileSync(OUT, body, "utf8");
console.log(`Wrote ${paths.length} image paths → ${relative(process.cwd(), OUT)}`);
