import type { PlanningProviderCategory, PlanningProviderSeed } from "./types";

/**
 * Editorial planning shortlist — internal hubs plus a few cautious off-site comparison entry points.
 * Ordering uses `editorialWeight` (planning relevance), not pay-to-rank.
 */
export const PLANNING_PROVIDER_SHORTLIST: PlanningProviderSeed[] = [
  {
    id: "svc-banks-hub",
    slug: "banks-hub",
    name: "Dutch banks directory",
    category: "banks",
    summary: "Overview of common retail and mobile-friendly options expats use for salary, rent, and iDEAL.",
    bestFor: "Setting up a euro account before your first payslip or rental payment.",
    pricingNote: "Monthly packages and card rules vary — confirm on each bank’s site.",
    ctaLabel: "Browse banks",
    href: "/netherlands/services/banks/",
    tags: ["salary", "iDEAL", "setup"],
    editorialWeight: 10,
    isAffiliateReady: true,
    market: "NL",
    audience: ["expats", "professionals", "families"],
    external: false,
  },
  {
    id: "svc-health-hub",
    slug: "health-insurance-hub",
    name: "Health insurance directory",
    category: "insurers",
    summary: "Mandatory basic insurance context plus where to compare policies when you register in the Netherlands.",
    bestFor: "Anyone who needs a basic policy after arrival (timing rules apply).",
    pricingNote: "Premiums and deductibles change by year and insurer — get a current quote.",
    ctaLabel: "Health insurance hub",
    href: "/netherlands/services/health-insurance/",
    tags: ["basic-insurance", "compare"],
    editorialWeight: 10,
    isAffiliateReady: true,
    market: "NL",
    audience: ["expats", "families", "professionals"],
    external: false,
  },
  {
    id: "independer-compare",
    slug: "independer",
    name: "Independer (comparison)",
    category: "insurers",
    summary: "Widely used comparison flow for Dutch insurance products; useful when shortlisting basic health policies.",
    bestFor: "Side-by-side views of premiums when you already know you need a Dutch basic policy.",
    pricingNote: "Third-party site; offers change — read policy documents before you buy.",
    ctaLabel: "Open Independer",
    href: "https://www.independer.nl/",
    tags: ["compare", "basic-insurance"],
    editorialWeight: 6,
    isAffiliateReady: true,
    market: "NL",
    audience: ["expats", "professionals"],
    external: true,
  },
  {
    id: "svc-housing-platforms",
    slug: "housing-platforms",
    name: "Housing & rental platforms",
    category: "rentalPlatforms",
    summary: "Listing ecosystems and search portals expats often combine when hunting for long-term rentals.",
    bestFor: "Building a realistic rent range before you lock a budget line.",
    pricingNote: "Most portals are free to browse; paid boosts or agencies may add fees.",
    ctaLabel: "Housing platforms",
    href: "/netherlands/services/housing-platforms/",
    tags: ["rent", "search"],
    editorialWeight: 9,
    isAffiliateReady: true,
    market: "NL",
    audience: ["expats", "professionals", "students"],
    external: false,
  },
  {
    id: "svc-rental-agencies",
    slug: "rental-agencies",
    name: "Rental agencies",
    category: "rentalPlatforms",
    summary: "When you want professional search help in tight markets — scope and fees differ widely.",
    bestFor: "Time-poor movers or competitive cities where viewings move quickly.",
    pricingNote: "Confirm success fees and exclusivity before signing with an agent.",
    ctaLabel: "Rental agencies hub",
    href: "/netherlands/services/rental-agencies/",
    tags: ["rent", "support"],
    editorialWeight: 7,
    isAffiliateReady: true,
    market: "NL",
    audience: ["expats", "professionals", "families"],
    external: false,
  },
  {
    id: "svc-relocation-services",
    slug: "relocation-services",
    name: "Relocation services",
    category: "relocationServices",
    summary: "Bundled help for housing, paperwork, and settling in — useful when your employer does not run the full process.",
    bestFor: "First-time movers who want a single coordinator for practical setup.",
    pricingNote: "Packages are bespoke — ask what is included (viewings, school search, etc.).",
    ctaLabel: "Relocation services",
    href: "/netherlands/services/relocation-services/",
    tags: ["setup", "family"],
    editorialWeight: 8,
    isAffiliateReady: true,
    market: "NL",
    audience: ["expats", "families", "professionals"],
    external: false,
  },
  {
    id: "svc-relocation-agencies",
    slug: "relocation-agencies",
    name: "Relocation agencies",
    category: "relocationServices",
    summary: "Another common channel for employer-sponsored or private relocation support.",
    bestFor: "Employer benefits that point you to a preferred relocation partner.",
    pricingNote: "Who pays (you vs employer) changes the budget impact entirely.",
    ctaLabel: "Relocation agencies",
    href: "/netherlands/services/relocation-agencies/",
    tags: ["employer", "setup"],
    editorialWeight: 7,
    isAffiliateReady: true,
    market: "NL",
    audience: ["expats", "professionals"],
    external: false,
  },
  {
    id: "svc-mobile",
    slug: "mobile-connectivity",
    name: "Mobile & connectivity",
    category: "internetUtilities",
    summary: "SIMs, home internet, and connectivity choices while you settle — pair with your housing timeline.",
    bestFor: "First-month setup when you need data and often home Wi-Fi.",
    pricingNote: "Intro offers rotate; check contract length and cancellation rules.",
    ctaLabel: "Mobile & internet hub",
    href: "/netherlands/services/mobile-connectivity/",
    tags: ["internet", "sim"],
    editorialWeight: 6,
    isAffiliateReady: true,
    market: "NL",
    audience: ["expats", "students", "professionals"],
    external: false,
  },
  {
    id: "taxes-hub",
    slug: "taxes-hub",
    name: "Dutch taxes hub",
    category: "taxAdvisory",
    summary: "High-level payroll and filing context when you are triangulating net salary with living costs.",
    bestFor: "Anyone pairing this budget with gross-to-net or 30% ruling questions.",
    pricingNote: "Not personalized advice — use calculators and professionals for your case.",
    ctaLabel: "Taxes hub",
    href: "/netherlands/taxes/",
    tags: ["salary", "30-percent"],
    editorialWeight: 5,
    isAffiliateReady: false,
    market: "NL",
    audience: ["expats", "professionals"],
    external: false,
  },
];

const CATEGORY_ORDER: PlanningProviderCategory[] = [
  "rentalPlatforms",
  "banks",
  "insurers",
  "relocationServices",
  "internetUtilities",
  "taxAdvisory",
];

const CATEGORY_LABEL: Record<PlanningProviderCategory, string> = {
  rentalPlatforms: "Housing search & rental help",
  banks: "Bank accounts & salary deposits",
  insurers: "Health insurance (basic)",
  relocationServices: "Relocation & expat support",
  internetUtilities: "Internet & connectivity",
  taxAdvisory: "Taxes & payroll context",
};

export function getPlanningShortlistByCategory(): Array<{ category: PlanningProviderCategory; label: string; items: PlanningProviderSeed[] }> {
  const byCat = new Map<PlanningProviderCategory, PlanningProviderSeed[]>();
  for (const c of CATEGORY_ORDER) byCat.set(c, []);
  for (const p of PLANNING_PROVIDER_SHORTLIST) {
    const list = byCat.get(p.category) ?? [];
    list.push(p);
    byCat.set(p.category, list);
  }
  return CATEGORY_ORDER.map((category) => ({
    category,
    label: CATEGORY_LABEL[category],
    items: (byCat.get(category) ?? []).sort((a, b) => b.editorialWeight - a.editorialWeight),
  })).filter((g) => g.items.length > 0);
}
