import type { LucideIcon } from "lucide-react";
import {
  Bike,
  BookOpen,
  Building2,
  CalendarRange,
  Car,
  CloudRain,
  CreditCard,
  GraduationCap,
  HeartPulse,
  Home,
  Languages,
  Landmark,
  MapPin,
  MapPinned,
  MessageCircle,
  Moon,
  Package,
  Route,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Shield,
  Sparkles,
  Tag,
  Ticket,
  Trash2,
  TrainFront,
  TrendingUp,
  Tv,
  UtensilsCrossed,
  Wallet,
} from "lucide-react";
import type { LivingAppsIconKey } from "./livingEssentialApps.types";

export const LIVING_APPS_ICON_MAP: Record<LivingAppsIconKey, LucideIcon> = {
  bike: Bike,
  bookOpen: BookOpen,
  building2: Building2,
  calendarRange: CalendarRange,
  car: Car,
  cloudRain: CloudRain,
  creditCard: CreditCard,
  graduationCap: GraduationCap,
  heartPulse: HeartPulse,
  home: Home,
  languages: Languages,
  landmark: Landmark,
  mapPin: MapPin,
  mapPinned: MapPinned,
  messageCircle: MessageCircle,
  moon: Moon,
  package: Package,
  route: Route,
  shoppingBag: ShoppingBag,
  shoppingCart: ShoppingCart,
  shield: Shield,
  smartphone: Smartphone,
  sparkles: Sparkles,
  tag: Tag,
  ticket: Ticket,
  trash2: Trash2,
  trainFront: TrainFront,
  trendingUp: TrendingUp,
  tv: Tv,
  utensilsCrossed: UtensilsCrossed,
  wallet: Wallet,
};

export function livingAppsIcon(key: LivingAppsIconKey): LucideIcon {
  return LIVING_APPS_ICON_MAP[key];
}
