import type { UtilitiesServicesInput } from "./types";

export const UTILITIES_SERVICES_DEFAULT_INPUT: UtilitiesServicesInput = {
  plannerMode: "quick",
  city: "amsterdam",
  moveStage: "moving_soon",
  householdType: "couple",
  adultsCount: 2,
  childrenCount: 0,
  renterOrOwner: "renter",
  utilitiesIncludedInRent: "unsure",
  housingType: "apartment",
  sizeBand: "medium",
  energyQuality: "average",
  heating: "gas",
  furnished: "unfurnished",
  landlordBuildingIncludesServices: "unsure",
  usageLevel: "average",
  internetTier: "standard",
  mobileUsage: "standard",
  mobileLines: 2,
  evHeavy: false,
  wfhHeavy: false,
  includeInternet: true,
  includeMobile: true,
  includeTvMedia: false,
  includeContentsInsurance: true,
  includeLiabilityInsurance: true,
  priority: "balanced",
  movingDateNote: "",
  shortTermOverlap: false,
};
