export const RANDSTAD_PATH = "/netherlands/randstad/" as const;

export const randstadPage = {
  slug: "randstad",
  path: RANDSTAD_PATH,
  publish: true,
  publishDate: "2026-05-06",
  seo: {
    title: "Randstad Netherlands Guide for Expats | Cities, Jobs, Housing & Commuting",
    description:
      "Explore the Randstad region of the Netherlands, including Amsterdam, Rotterdam, The Hague, Utrecht and nearby cities. Compare lifestyle, housing, jobs, commuting and expat services.",
    keywords: [
      "Randstad Netherlands expat",
      "living in the Randstad",
      "Randstad cities Netherlands",
      "best Randstad cities for expats",
      "Amsterdam Rotterdam The Hague Utrecht expats",
      "Randstad commuting expats",
      "where to live in the Randstad",
    ],
  },
  hero: {
    eyebrow: "Netherlands region guide",
    pageTitle: "Randstad Netherlands Guide for Expats",
    subtitle:
      "Understand the Netherlands' main urban region - from Amsterdam and Rotterdam to The Hague, Utrecht and surrounding cities - and decide where to live, work and settle.",
    primaryCta: { label: "Compare Randstad Cities", href: "#main-randstad-cities" },
    secondaryCta: { label: "Explore Services", href: "#services" },
    chips: ["Connected cities", "Jobs", "Housing", "Commuting"],
    image: {
      src: "/images/heroes/randstad-netherlands-expat-hero.png",
      alt: "Photorealistic Randstad relocation planning scene with a western Netherlands map, Amsterdam, Rotterdam, The Hague and Utrecht marked, a transit card, and a commute comparison tablet.",
    },
  },
  sectionNav: [
    { href: "#what-is-the-randstad", label: "What it is" },
    { href: "#randstad-at-a-glance", label: "At a glance" },
    { href: "#where-is-the-randstad", label: "Map / region" },
    { href: "#main-randstad-cities", label: "Main cities" },
    { href: "#lifestyle-fit", label: "Lifestyle fit" },
    { href: "#housing", label: "Housing" },
    { href: "#jobs-business", label: "Jobs & business" },
    { href: "#commuting", label: "Commuting" },
    { href: "#services", label: "Services" },
    { href: "#scenarios", label: "Scenarios" },
    { href: "#sources", label: "Sources" },
    { href: "#related-guides", label: "Related guides" },
  ],
  snapshotCards: [
    { title: "Best for", body: "International jobs, universities, transport, and expat services." },
    { title: "Main cities", body: "Amsterdam, Rotterdam, The Hague, and Utrecht." },
    { title: "Also consider", body: "Haarlem, Leiden, Delft, Amstelveen, Almere, and Gouda." },
    { title: "Biggest challenge", body: "Housing availability and cost, especially near core job markets." },
    { title: "Best strategy", body: "Compare lifestyle plus commute, not only city reputation." },
    {
      title: "Good for",
      body: "Professionals, students, families, entrepreneurs, and international couples.",
    },
  ],
  regionLinks: [
    { label: "Amsterdam", href: "/netherlands/amsterdam/" },
    { label: "Rotterdam", href: "/netherlands/rotterdam/" },
    { label: "The Hague", href: "/netherlands/the-hague/" },
    { label: "Utrecht", href: "/netherlands/utrecht/" },
    { label: "Haarlem", href: "/netherlands/haarlem/" },
    { label: "Leiden", href: "/netherlands/leiden/" },
    { label: "Delft", href: "/netherlands/delft/" },
    { label: "Amstelveen", href: "/netherlands/amstelveen/" },
  ],
  infographics: {
    cityNetwork: {
      src: "/images/infographics/randstad-city-network-infographic.png",
      alt: "Infographic map showing the Randstad as a connected city network with Amsterdam, Rotterdam, The Hague, Utrecht, Haarlem, Leiden, Delft and Amstelveen linked by rail and commute lines.",
      caption:
        "Use this to understand the Randstad as a connected region with different city identities, not one single city.",
    },
    cityFit: {
      src: "/images/infographics/randstad-city-fit-tradeoffs-infographic.png",
      alt: "Infographic comparing Randstad city-fit lenses: Amsterdam for career intensity, The Hague for international institutions, Utrecht for central commuting, Rotterdam for modern urban energy, Haarlem Leiden Delft for historic smaller-city living, Amstelveen for Amsterdam access, and Leiden Delft Utrecht Amsterdam for students and research.",
      caption:
        "Use this as a shortlist lens: match the city to your weekly rhythm before deep-diving neighbourhoods.",
    },
    commuteHousing: {
      src: "/images/infographics/randstad-commute-housing-flow-infographic.png",
      alt: "Infographic decision flow for Randstad housing and commuting: office or campus, station access, bike to station, hybrid pattern, school or childcare, and housing shortlist.",
      caption:
        "Use this before you sign a rental contract: test the door-to-door week, not only the city name.",
    },
  },
  mainCities: [
    {
      name: "Amsterdam",
      href: "/netherlands/amsterdam/",
      role: "Global career hub",
      bestFor: ["Tech / finance", "Startups", "Culture"],
      commuteNote: "Often paired with Haarlem, Amstelveen, Leiden, Almere or Schiphol-area commutes.",
      summary: "International jobs, tech, finance, startups, culture, and a deep service ecosystem.",
      watchOut: "High housing pressure means many expats compare nearby cities before signing.",
    },
    {
      name: "Rotterdam",
      href: "/netherlands/rotterdam/",
      role: "Port and modern business city",
      bestFor: ["Logistics", "Maritime", "Modern urban life"],
      commuteNote: "Works well with Delft, The Hague and some Utrecht-facing commutes.",
      summary: "Port, logistics, architecture, international business, maritime, energy, and trade.",
      watchOut: "A more urban and modern feel than many historic Dutch cities.",
    },
    {
      name: "The Hague",
      href: "/netherlands/the-hague/",
      role: "International institutions",
      bestFor: ["Diplomacy", "NGOs", "Families"],
      commuteNote: "Commonly paired with Leiden, Delft and Rotterdam, depending on office and school routes.",
      summary: "Government, diplomacy, international courts, NGOs, and international institutions.",
      watchOut: "Strong family and international-school appeal can shape neighbourhood demand.",
    },
    {
      name: "Utrecht",
      href: "/netherlands/utrecht/",
      role: "Central rail anchor",
      bestFor: ["Rail access", "Dutch city feel", "Hybrid workers"],
      commuteNote: "Useful if your household needs access to multiple Randstad cities.",
      summary: "Central location, strong Dutch city feel, and excellent rail connectivity.",
      watchOut: "Popular and competitive, especially for people who commute across the country.",
    },
    {
      name: "Haarlem",
      href: "/netherlands/haarlem/",
      role: "Amsterdam-area historic base",
      bestFor: ["Calmer lifestyle", "Historic centre", "Amsterdam access"],
      commuteNote: "Often chosen by people working in Amsterdam who want a smaller-city rhythm.",
      summary: "Amsterdam-area alternative with historic streets, lifestyle appeal, and rail access.",
      watchOut: "Often chosen for balance rather than big-city intensity.",
    },
    {
      name: "Leiden",
      href: "/netherlands/leiden/",
      role: "University and science city",
      bestFor: ["Research", "Biotech", "Historic living"],
      commuteNote: "Can work for The Hague, Amsterdam or Schiphol-area routines if station access fits.",
      summary: "University, science, biotech, and a compact historic city environment.",
      watchOut: "Useful for research careers and commutes toward The Hague or Amsterdam.",
    },
    {
      name: "Delft",
      href: "/netherlands/delft/",
      role: "Engineering and TU Delft base",
      bestFor: ["Engineering", "Students", "Compact living"],
      commuteNote: "Strong middle option between Rotterdam and The Hague.",
      summary: "Technical university, engineering, innovation, and a compact historic setting.",
      watchOut: "A strong option between Rotterdam and The Hague.",
    },
    {
      name: "Amstelveen",
      href: "/netherlands/amstelveen/",
      role: "Family-friendly Amsterdam access",
      bestFor: ["Families", "International community", "Amsterdam Zuid / Schiphol"],
      commuteNote: "Practical for Amsterdam Zuid, Schiphol-area jobs and households wanting calmer living.",
      summary: "Amsterdam access, family-friendly living, international community, and Schiphol-area reach.",
      watchOut: "Often works for people who need Amsterdam Zuid without central Amsterdam living.",
    },
  ],
  lifestyleComparisons: [
    { title: "Best for career intensity", body: "Amsterdam" },
    { title: "Best for international institutions", body: "The Hague" },
    { title: "Best for central commuting", body: "Utrecht" },
    { title: "Best for modern urban energy", body: "Rotterdam" },
    { title: "Best for historic smaller-city living", body: "Haarlem, Leiden, Delft" },
    { title: "Best for Amsterdam access with calmer living", body: "Amstelveen" },
    { title: "Best for students and research", body: "Leiden, Delft, Utrecht, Amsterdam" },
  ],
  housingLinks: [
    { label: "Housing platforms", href: "/netherlands/services/housing-platforms/" },
    { label: "Rental agencies", href: "/netherlands/services/rental-agencies/" },
    { label: "Relocation services", href: "/netherlands/services/relocation-services/" },
    { label: "Relocation agencies", href: "/netherlands/services/relocation-agencies/" },
  ],
  workLinks: [
    { label: "Highly skilled migrant sponsors", href: "/netherlands/services/highly-skilled-migrant-sponsors/" },
    { label: "Visa consultants", href: "/netherlands/services/visa-consultants/" },
    { label: "Immigration lawyers", href: "/netherlands/services/immigration-lawyers/" },
    { label: "Startup visa advisors", href: "/netherlands/services/startup-visa-advisors/" },
  ],
  commuteChecks: [
    "commute time",
    "station access",
    "bike-to-station time",
    "hybrid work pattern",
    "childcare or school route",
    "airport access",
  ],
  commuteExamples: [
    "live in Haarlem, work in Amsterdam",
    "live in Leiden, work in The Hague or Amsterdam",
    "live in Delft, work in Rotterdam or The Hague",
    "live in Utrecht, commute across multiple cities",
    "live in Amstelveen, work in Amsterdam Zuid or the Schiphol area",
  ],
  personas: [
    "international professional",
    "highly skilled migrant",
    "student or researcher",
    "family needing international schools and services",
    "entrepreneur or startup founder",
    "expat couple with jobs in different cities",
    "newcomer who wants the widest service ecosystem",
  ],
  outsideRandstadLinks: [
    { label: "Eindhoven", href: "/netherlands/eindhoven/" },
    { label: "Groningen", href: "/netherlands/groningen/" },
    { label: "Maastricht", href: "/netherlands/maastricht/" },
    { label: "Breda", href: "/netherlands/breda/" },
    { label: "Tilburg", href: "/netherlands/tilburg/" },
    { label: "Arnhem", href: "/netherlands/arnhem/" },
    { label: "Nijmegen", href: "/netherlands/nijmegen/" },
  ],
  serviceLinks: [
    { label: "Housing platforms", href: "/netherlands/services/housing-platforms/", description: "Listings, furnished rentals, and mid-term options." },
    { label: "Rental agencies", href: "/netherlands/services/rental-agencies/", description: "Agency-assisted search when competition is high." },
    { label: "Relocation services", href: "/netherlands/services/relocation-services/", description: "Bundled help with housing, registration, and settling in." },
    { label: "Immigration lawyers", href: "/netherlands/services/immigration-lawyers/", description: "Legal support for complex immigration situations." },
    { label: "Visa consultants", href: "/netherlands/services/visa-consultants/", description: "Permit routes, documents, and process guidance." },
    { label: "Banks", href: "/netherlands/services/banks/", description: "Accounts for salary, rent, cards, and everyday payments." },
    { label: "Health insurance", href: "/netherlands/services/health-insurance/", description: "Compare Dutch basic insurance options." },
  ],
  scenarios: [
    {
      title: "You work in Amsterdam but cannot find housing there",
      body: "Compare Amsterdam-area alternatives and station-to-office travel before widening your search randomly.",
      links: [
        { label: "Amsterdam", href: "/netherlands/amsterdam/" },
        { label: "Haarlem", href: "/netherlands/haarlem/" },
        { label: "Amstelveen", href: "/netherlands/amstelveen/" },
        { label: "Housing platforms", href: "/netherlands/services/housing-platforms/" },
      ],
    },
    {
      title: "You and your partner work in different Randstad cities",
      body: "Shortlist by combined commute, not by one person's office alone.",
      links: [
        { label: "Utrecht", href: "/netherlands/utrecht/" },
        { label: "City comparison tool", href: "/netherlands/tools/city-comparison/" },
        { label: "Cities hub", href: "/netherlands/cities/" },
      ],
    },
    {
      title: "You want an international-school-friendly family base",
      body: "Look at school routes, housing type, commute, and support services together.",
      links: [
        { label: "The Hague", href: "/netherlands/the-hague/" },
        { label: "Amstelveen", href: "/netherlands/amstelveen/" },
        { label: "Relocation services", href: "/netherlands/services/relocation-services/" },
      ],
    },
    {
      title: "You are choosing between Amsterdam and Utrecht",
      body: "Test job access, rail patterns, housing pressure, and the weekly rhythm you want.",
      links: [
        { label: "Amsterdam", href: "/netherlands/amsterdam/" },
        { label: "Utrecht", href: "/netherlands/utrecht/" },
        { label: "Best cities guide", href: "/netherlands/cities/best-cities-for-expats/" },
      ],
    },
    {
      title: "You want tech or engineering work but prefer a smaller city",
      body: "Compare university and research hubs with transport access to larger employers.",
      links: [
        { label: "Delft", href: "/netherlands/delft/" },
        { label: "Leiden", href: "/netherlands/leiden/" },
        { label: "Highly skilled migrant sponsors", href: "/netherlands/services/highly-skilled-migrant-sponsors/" },
      ],
    },
    {
      title: "You want to reduce rent while keeping train access",
      body: "Search around stations and test door-to-door commute before assuming a cheaper city is practical.",
      links: [
        { label: "Rental agencies", href: "/netherlands/services/rental-agencies/" },
        { label: "Rent affordability calculator", href: "/netherlands/housing/tools/rent-affordability-calculator/" },
        { label: "Cheapest cities guide", href: "/netherlands/cities/cheapest-cities-for-expats/" },
      ],
    },
  ],
  officialSources: [
    {
      label: "Netherlands relocation checklist",
      href: "https://www.netherlandsworldwide.nl/checklist-relocating-netherlands-immigration",
    },
    {
      label: "Government moving to Netherlands guidance",
      href: "https://www.government.nl/topics/immigration-to-the-netherlands/question-and-answer/what-do-i-need-to-arrange-if-im-moving-to-the-netherlands",
    },
    { label: "Invest in Holland", href: "https://investinholland.com/" },
    {
      label: "Business.gov.nl location guidance",
      href: "https://business.gov.nl/business-location/establishing-or-relocating-a-business/finding-the-right-business-location/",
    },
  ],
  relatedGuides: [
    { label: "Cities in the Netherlands", href: "/netherlands/cities/" },
    { label: "Moving to the Netherlands", href: "/netherlands/moving-to-the-netherlands/" },
    { label: "After arriving in the Netherlands", href: "/netherlands/after-arriving-netherlands/" },
    { label: "Municipality registration", href: "/netherlands/municipality-registration-netherlands/" },
    { label: "Open a bank account", href: "/netherlands/open-bank-account-netherlands/" },
    { label: "Health insurance", href: "/netherlands/health-insurance-netherlands/" },
    { label: "Services", href: "/netherlands/services/" },
  ],
  exploreNextCards: [
    { label: "Compare Dutch Cities", href: "/netherlands/cities/", description: "Open the full city hub and compare live city guides." },
    { label: "Explore Services", href: "/netherlands/services/", description: "Browse providers for housing, visas, banking, insurance, and relocation." },
    {
      label: "Moving to the Netherlands",
      href: "/netherlands/moving-to-the-netherlands/",
      description: "Put Randstad city choice inside your relocation timeline and admin checklist.",
    },
    {
      label: "Housing Platforms",
      href: "/netherlands/services/housing-platforms/",
      description: "Start the rental search with platforms that support different housing types.",
    },
  ],
} as const;
