import { buyingHouseReference2026 } from "./buyingHouseReference2026";

export const BUYING_HOUSE_NETHERLANDS_PATH = "/netherlands/housing/buying-a-house-netherlands/" as const;
export const HOUSING_HUB_PATH = "/netherlands/housing/" as const;
export const RENTING_NETHERLANDS_PATH = "/netherlands/housing/renting-in-the-netherlands/" as const;
export const MOVING_TO_NETHERLANDS_PATH = "/netherlands/moving-to-the-netherlands/" as const;
export const TAXES_HUB_PATH = "/netherlands/taxes/" as const;
export const CITIES_HUB_PATH = "/netherlands/cities/" as const;
export const EXPAT_SALARY_NETHERLANDS_PATH = "/netherlands/jobs/expat-salary-netherlands/" as const;
export const NET_SALARY_NETHERLANDS_PATH = "/netherlands/taxes/net-salary-netherlands/" as const;
export const RENT_AFFORDABILITY_TOOL_PATH = "/netherlands/housing/tools/rent-affordability-calculator/" as const;

export type BuyingHouseNetherlandsLink = {
  label: string;
  href: string;
  description?: string;
  status?: "live" | "comingSoon";
};

export const buyingHouseNetherlandsPage = {
  slug: "buying-a-house-netherlands",
  path: BUYING_HOUSE_NETHERLANDS_PATH,
  publish: true,
  publishDate: "2026-07-12",
  seo: {
    title: "Buying a House in the Netherlands | Expat Guide to Mortgages, Costs & Process",
    description:
      "Learn how buying a house works in the Netherlands for expats, including mortgages, taxes, overbidding, legal steps, costs and city-by-city housing insights.",
    keywords: [
      "buying a house netherlands",
      "buy house netherlands expat",
      "buying property netherlands",
      "dutch housing market",
      "mortgage netherlands expat",
      "expat mortgage netherlands",
      "house prices netherlands",
      "buying apartment netherlands",
      "overbidding netherlands",
      "buying home amsterdam",
    ],
  },
  hero: {
    eyebrow: "Netherlands · Housing · Buying property",
    pageTitle: "Buying a House in the Netherlands",
    subtitle:
      "Understand how buying property works in the Netherlands, including mortgages, bidding, taxes, legal steps and what expats should know before purchasing a home.",
    primaryCta: { label: "Understand the Buying Process", href: "#intro" },
    secondaryCta: { label: "Explore Housing Guides", href: HOUSING_HUB_PATH },
    chips: ["Expat mortgages", "Kosten koper", "Overbidding", "Notary transfer"],
    image: {
      src: "/images/heroes/netherlands-buying-a-house-netherlands-hero-v3.png",
      alt: "Photorealistic editorial photo of a Dutch canal-side residential street with brick townhouses and bicycles, house keys and a property purchase contract on a wooden table in the foreground — authentic expat home-buying atmosphere without realtors or stock-photo clichés.",
    },
  },
  infographics: {
    introFlow: {
      src: "/images/infographics/netherlands-buying-a-house-intro-flow-infographic-v3.png",
      alt: "Infographic explaining whether expats can buy property in the Netherlands: residency, employment, mortgage advice and competitive market context.",
      caption: "Many expats buy Dutch property — but mortgages, bidding and kosten koper need planning before you search.",
    },
    snapshot: {
      src: "/images/infographics/netherlands-buying-a-house-snapshot-infographic-v3.png",
      alt: "Infographic snapshot of buying property in the Netherlands at a glance: expats can buy, mortgages, competition, costs and overbidding.",
      caption: "Use this snapshot before viewing — buyer costs sit on top of the purchase price.",
    },
    buyOrRent: {
      src: "/images/infographics/netherlands-buying-a-house-buy-or-rent-infographic-v3.png",
      alt: "Infographic comparing when expats should buy vs rent in the Netherlands: long-term stay, family relocation vs short-term uncertainty.",
      caption: "Buying suits stable long-term plans — renting keeps flexibility during probation or uncertain relocation.",
    },
    process: {
      src: "/images/infographics/netherlands-buying-a-house-process-infographic-v3.png",
      alt: "Infographic of the Dutch home buying process from budget and mortgage advice through offer, purchase agreement, inspection and notary transfer.",
      caption: "The Dutch buying process often moves quickly once you find a property — prepare mortgage advice early.",
    },
    mortgages: {
      src: "/images/infographics/netherlands-buying-a-house-mortgages-infographic-v3.png",
      alt: "Infographic explaining mortgages for expats in the Netherlands: employment, income, residency and lender requirements.",
      caption: "Many expats may qualify — but approval depends on your personal situation, not nationality alone.",
    },
    capacity: {
      src: "/images/infographics/netherlands-buying-a-house-capacity-infographic-v3.png",
      alt: "Infographic explaining how Dutch mortgage borrowing capacity works: salary, debts, partner income and affordability tests.",
      caption: "Banks use affordability calculations — connect salary planning to realistic purchase ranges.",
    },
    costs: {
      src: "/images/infographics/netherlands-buying-a-house-costs-infographic-v3.png",
      alt: "Infographic of additional costs when buying a house in the Netherlands: transfer tax, notary, valuation, inspection and advisor fees.",
      caption: "Kosten koper often reach 4–6% of the purchase price — plan own funds beyond the mortgage.",
    },
    overbidding: {
      src: "/images/infographics/netherlands-buying-a-house-overbidding-infographic-v3.png",
      alt: "Infographic explaining overbidding in the Dutch housing market and how competition varies by city.",
      caption: "Randstad cities often see offers above asking — budget for appraisal gaps from savings.",
    },
    cities: {
      src: "/images/infographics/netherlands-buying-a-house-cities-infographic-v3.png",
      alt: "Infographic comparing buying property in Dutch cities: Amsterdam, Rotterdam, Utrecht, Eindhoven and smaller cities.",
      caption: "City choice shapes price pressure, commute and expat community — compare before you bid.",
    },
    mortgageTypes: {
      src: "/images/infographics/netherlands-buying-a-house-mortgage-types-infographic-v3.png",
      alt: "Infographic explaining Dutch mortgage types: fixed vs variable interest and repayment structures.",
      caption: "Mortgage structure is personal — use AFM-regulated advice, not blog generalisations.",
    },
    taxes: {
      src: "/images/infographics/netherlands-buying-a-house-taxes-infographic-v3.png",
      alt: "Infographic of taxes and financial considerations when buying Dutch property: transfer tax, mortgage interest deduction and municipal levies.",
      caption: "Transfer tax and ongoing property taxes vary by use and municipality — verify on Belastingdienst.",
    },
    challenges: {
      src: "/images/infographics/netherlands-buying-a-house-challenges-infographic-v3.png",
      alt: "Infographic of common challenges for expat home buyers: language, contracts, competition and temporary employment.",
      caption: "Professional advisors and neighbourhood research reduce common expat buying mistakes.",
    },
    apartmentVsHouse: {
      src: "/images/infographics/netherlands-buying-a-house-apartment-vs-house-infographic-v3.png",
      alt: "Infographic comparing buying an apartment vs house in the Netherlands: VvE fees vs maintenance responsibility.",
      caption: "Apartments involve owners associations (VvE) — houses involve direct maintenance and renovation choices.",
    },
    questions: {
      src: "/images/infographics/netherlands-buying-a-house-questions-infographic-v3.png",
      alt: "Infographic summarising common expat questions about buying property in the Netherlands.",
      caption: "Use these prompts when planning — then confirm with mortgage advisers and official sources.",
    },
    relatedGuides: {
      src: "/images/infographics/netherlands-buying-a-house-related-guides-infographic-v3.png",
      alt: "Infographic linking to related housing guides: renting, housing costs, mortgages and cities.",
      caption: "Connect buying plans to renting alternatives, salary context and city comparison.",
    },
    services: {
      src: "/images/infographics/netherlands-buying-a-house-services-infographic-v3.png",
      alt: "Infographic showing professional services for Dutch home buyers: mortgage advisors, agents, lawyers and inspectors.",
      caption: "Use licensed professionals for personal mortgage and legal questions — this guide is orientation only.",
    },
    officialSources: {
      src: "/images/infographics/netherlands-buying-a-house-official-sources-infographic-v3.png",
      alt: "Infographic map of official Dutch home buying sources: Government.nl, Belastingdienst, Kadaster, AFM and Business.gov.nl.",
      caption: "Verify current transfer tax, mortgage rules and registration requirements on official government sources.",
    },
    exploreNext: {
      src: "/images/infographics/netherlands-buying-a-house-explore-next-infographic-v3.png",
      alt: "Infographic linking to next-step guides: renting, mortgage guide, housing costs, cities and moving guide.",
      caption: "Move from buying concepts into salary planning, city choice and relocation timelines.",
    },
  },
  sectionNav: [
    { href: "#intro", label: "Overview" },
    { href: "#snapshot", label: "Snapshot" },
    { href: "#costs-reference", label: "2026 costs" },
    { href: "#buy-or-rent", label: "Buy vs rent" },
    { href: "#process", label: "Process" },
    { href: "#mortgages", label: "Mortgages" },
    { href: "#capacity", label: "Borrowing" },
    { href: "#costs", label: "Costs" },
    { href: "#overbidding", label: "Overbidding" },
    { href: "#cities", label: "Cities" },
    { href: "#mortgage-types", label: "Mortgage types" },
    { href: "#taxes", label: "Taxes" },
    { href: "#challenges", label: "Challenges" },
    { href: "#apartment-vs-house", label: "Apartment vs house" },
    { href: "#questions", label: "Questions" },
    { href: "#related-guides", label: "Related" },
    { href: "#services", label: "Services" },
    { href: "#faq", label: "FAQ" },
    { href: "#sources", label: "Sources" },
  ],
  conceptCards: [
    { title: "Expats can buy", body: "Foreign nationals and international residents can own Dutch property — mortgage and residency rules apply per lender." },
    { title: "Kosten koper", body: "Buyer costs (transfer tax, notary, valuation, advice) sit on top of the purchase price — often paid from own funds." },
    { title: "Fast-moving process", body: "From accepted offer to notarial transfer often takes weeks — mortgage advice and documents should be ready early." },
  ],
  snapshotCards: [
    { label: "Transfer tax", value: "2% → €8,000 at €400k" },
    { label: "Kosten koper", value: "~€13,500 at €400k" },
    { label: "NHG limit 2026", value: "€470,000" },
    { label: "NHG + energy", value: "€498,200" },
    { label: "Overbid gap", value: "€15,000 example" },
    { label: "Timeline", value: "6–12 weeks" },
  ],
  snapshotTips: [
    "At €400,000: ~€8,000 transfer tax + ~€5,500 other buyer costs ≈ €13,500 kosten koper — plan this from savings, not the mortgage.",
    "NHG 2026 cap is €470,000 (€498,200 with energy improvements) — fee 0.4% of loan when NHG applies.",
    "Overbid example: offer €425,000, appraisal €410,000 → €15,000 gap from savings on top of kosten koper.",
    "Investment/second home: 10.4% transfer tax — €400,000 → ~€41,600 vs ~€8,000 owner-occupied.",
  ],
  reference2026: buyingHouseReference2026,
  introChecklist: [
    "Budget kosten koper separately — e.g. ~€13,500 own funds at a €400,000 purchase before any overbid gap.",
    "Check NHG eligibility if purchase ≤ €470,000 (€498,200 with energy improvements) — verify on nhg.nl.",
    "Book mortgage advice early — know your indicative budget and max bid including overbid buffer.",
    "Confirm owner-occupied vs investment transfer tax (2% vs 10.4%) before you sign.",
  ],
  newcomerSurprises: [
    "Kosten koper at €400,000 is often ~€13,500+ — banks may finance the property but rarely all buyer-side costs.",
    "Overbid gap is separate: offer €425,000 with €410,000 appraisal → €15,000 from savings before the mortgage covers the rest.",
    "NHG 2026 limit is €470,000 — purchases above that typically cannot use NHG (verify with adviser).",
    "Investment transfer tax at 10.4% turns €400,000 into ~€41,600 tax vs ~€8,000 for owner-occupied.",
  ],
  buyOrRentTips: [
    "Buying may suit families, long-term employment and stable residency planning.",
    "Renting may suit probation periods, short assignments and uncertain relocation timelines.",
    "Compare total cost of ownership (mortgage, taxes, maintenance, VvE) with rent — not purchase price alone.",
    "Neither choice is universally better — match housing strategy to your relocation horizon.",
  ],
  buyReasons: [
    { title: "Long-term stay", body: "Multi-year employment or family relocation where roots and stability matter." },
    { title: "Stable employment", body: "Permanent or long fixed-term contract that supports mortgage affordability tests." },
    { title: "Family relocation", body: "Schools, space and neighbourhood choice for children over several years." },
  ],
  buyOrRentComparison: [
    { factor: "Stay horizon", buy: "Multi-year roots, family relocation", rent: "Short assignment, uncertain visa renewal" },
    { factor: "Employment", buy: "Permanent or long fixed-term contract", rent: "Probation, temporary contract, job search" },
    { factor: "Upfront cash", buy: "~€13,500 at €400k + overbid gap (e.g. €15k)", rent: "Deposit ~1–2 months + agency fees" },
    { factor: "Flexibility", buy: "Selling takes time and transaction costs", rent: "Easier to relocate cities or countries" },
    { factor: "Monthly cost", buy: "Mortgage + OZB + maintenance/VvE", rent: "Rent + utilities (no equity build-up)" },
  ],
  rentReasons: [
    { title: "Short assignment", body: "Temporary contracts or uncertain visa renewal make selling later costly." },
    { title: "Probation period", body: "New job probation may affect mortgage timing — renting preserves flexibility." },
    { title: "Market learning", body: "Time to understand cities and neighbourhoods before committing to purchase." },
  ],
  processSteps: [
    { step: "1", title: "Determine budget", body: "Model purchase range from income, savings for kosten koper and conservative overbid buffer." },
    { step: "2", title: "Arrange mortgage advice", body: "AFM-regulated hypotheekadviseur reviews indicative capacity — not a guarantee of approval." },
    { step: "3", title: "Search for property", body: "Use Funda, agents and networks — set alerts in target cities and price bands." },
    { step: "4", title: "Attend viewings", body: "Inspect condition, neighbourhood, VvE documents (apartments) and energy label." },
    { step: "5", title: "Make an offer", body: "Bid through seller's agent or your aankoopmakelaar — competition may require overbidding." },
    { step: "6", title: "Sign purchase agreement", body: "Koopovereenkomst with resolutieve voorwaarden (financing, inspection) — legal review recommended." },
    { step: "7", title: "Arrange mortgage approval", body: "Lender processes application after accepted offer — valuation may cap the loan amount." },
    { step: "8", title: "Technical inspection", body: "Bouwkundige keuring identifies structural risks — common condition before final commitment." },
    { step: "9", title: "Final transfer at notary", body: "Notaris executes levering — purchase deed, mortgage deed and transfer tax settlement." },
    { step: "10", title: "Receive keys", body: "Ownership transfers on the agreed date — register utilities and update address (BRP)." },
  ],
  processTips: [
    "The process often moves quickly — have mortgage advice and document copies ready before bidding.",
    "Purchase agreements may include financing and inspection conditions — understand deadlines.",
    "The civil-law notary (notaris) is mandatory for property transfer — buyer typically chooses the notary.",
    "This guide does not replace legal or mortgage advice for your specific purchase.",
  ],
  mortgageTips: [
    "Many expats may qualify depending on employment contract, income, residency status and creditworthiness.",
    "Highly skilled migrants with stable employment are commonly approved — but each lender sets policy.",
    "Temporary contracts, probation and cross-border income may need extra documentation or reduce options.",
    "Mortgage approval is never guaranteed — treat advice as indicative until the lender confirms.",
  ],
  mortgageFactors: [
    { title: "Employment contract", body: "Permanent or long fixed-term contracts are typically preferred — probation may delay approval." },
    { title: "Residency & visa", body: "Valid residence permit and stable stay horizon matter for lender risk assessment." },
    { title: "Income & debts", body: "Gross income, existing loans and partner income feed affordability calculations." },
    { title: "Nationality", body: "Not a general barrier — lender policy and documentation requirements vary." },
  ],
  expatMortgageScenarios: [
    { title: "Highly skilled migrant", body: "Stable employment and valid permit often support approval — confirm contract length and probation with your adviser." },
    { title: "International employee", body: "Long-term expat packages may qualify when income is documented in euros and employment is stable." },
    { title: "Partner with Dutch income", body: "Combined household income can increase capacity — both incomes and debts typically count in affordability tests." },
    { title: "Temporary or probation contract", body: "Shorter contracts may limit lender options — some buyers wait until permanent employment before bidding." },
  ],
  capacityTips: [
    "Dutch banks use affordability tests (toetsrente / Nibud-style norms) — not gross salary alone.",
    "Partner income can increase capacity — debts and student loans reduce it.",
    "Interest rate environment affects maximum loan — rates change; do not rely on outdated blog figures.",
    "Connect salary planning to purchase range via net salary and expat salary guides.",
  ],
  capacityFactors: [
    { title: "Gross income", body: "Salary, bonuses and variable pay may be treated differently per lender." },
    { title: "Employment stability", body: "Contract type, employer and probation status affect how income counts." },
    { title: "Existing debts", body: "Loans, alimony and other obligations reduce borrowing room." },
    { title: "Interest assumptions", body: "Affordability tests use regulatory test rates — not your quoted mortgage rate." },
  ],
  costsTips: [
    "At €300k / €400k / €500k / €600k — see the purchase-price table for transfer tax and total kosten koper planning figures.",
    "Transfer tax alone: €6,000 at €300k · €8,000 at €400k · €10,000 at €500k · €12,000 at €600k (owner-occupied 2%).",
    "Add ~€5,000–€6,000 mid-range for notary, valuation, inspection and mortgage advice at most price points.",
    "NHG fee when used: 0.4% of loan — e.g. €1,520 on a €380,000 mortgage.",
  ],
  costItems: [
    { title: "Transfer tax", body: "Overdrachtsbelasting on the purchase — owner-occupied rate differs from investment/non-primary use." },
    { title: "Notary fees", body: "Mandatory civil-law notary for deed transfer and mortgage registration." },
    { title: "Mortgage advisor", body: "Hypotheekadviseur fee for advice and lender application coordination." },
    { title: "Valuation", body: "Taxatierapport required by lender — may cap financeable amount." },
    { title: "Technical inspection", body: "Bouwkundige keuring — optional but strongly recommended." },
    { title: "Buyer's agent", body: "Aankoopmakelaar optional fee — can help in competitive markets." },
    { title: "Mortgage arrangement", body: "Bank arrangement and NHG fees when applicable." },
    { title: "Real estate agent (seller)", body: "Seller pays verkopend makelaar — buyer may pay aankoopmakelaar separately." },
  ],
  overbiddingTips: [
    "Mortgage is typically capped at appraisal — a €425k offer with €410k appraisal means €15k from savings before financing.",
    "5% over asking on €400k (bid €420k, appraisal €410k) → €10k gap — see overbidding table for more scenarios.",
    "Amsterdam/Utrecht hot markets: 10% over €550k asking can mean €30k+ appraisal gap from savings.",
    "Set max bid = appraisal estimate + kosten koper savings + acceptable overbid gap — with your mortgage adviser.",
  ],
  overbiddingConcepts: [
    { title: "Appraisal gap", body: "Offer €425,000, appraisal €410,000 → €15,000 from savings — mortgage covers appraisal, not your bid." },
    { title: "Hot-market scale", body: "10% over €550,000 asking (bid €605k, appraisal €575k) → €30,000 gap — common in Amsterdam/Utrecht." },
    { title: "Total own funds", body: "Overbid gap stacks on kosten koper — e.g. €15k gap + ~€13.5k buyer costs at €400k before you move in." },
  ],
  cityTips: [
    "Amsterdam and Utrecht often show the highest price pressure — commute towns like Haarlem or Amstelveen are common alternatives.",
    "Rotterdam and Eindhoven can offer more space per euro than central Randstad cities for international professionals.",
    "Student cities (Leiden, Delft, Groningen) mix strong demand with different expat employer profiles — check commute to your office.",
    "Visit neighbourhoods at weekday evenings and weekends before bidding — noise, parking and schools matter long-term.",
  ],
  cityMarketConcepts: [
    { title: "Randstad premium", body: "Amsterdam, Utrecht, The Hague and Haarlem cluster high demand — overbidding and tight supply are common." },
    { title: "Commuter strategy", body: "Buying in Haarlem, Amstelveen or Utrecht outskirts can balance price with Amsterdam/Rotterdam access." },
    { title: "Regional alternatives", body: "Groningen, Arnhem, Nijmegen and Maastricht often offer lower entry prices and distinct expat communities." },
  ],
  cityCards: [
    { label: "Amsterdam", href: "/netherlands/amsterdam/", vibe: "Canal belt, international hub", pricing: "Very high pressure", expat: "Very popular", commute: "Strong OV; parking scarce" },
    { label: "Rotterdam", href: "/netherlands/rotterdam/", vibe: "Modern, port city energy", pricing: "High but often below Amsterdam", expat: "Growing international base", commute: "Good rail links; car-friendly vs Amsterdam" },
    { label: "The Hague", href: "/netherlands/the-hague/", vibe: "Government & international orgs", pricing: "High coastal Randstad", expat: "Diplomatic & NGO community", commute: "Randstad rail; beach proximity" },
    { label: "Utrecht", href: "/netherlands/utrecht/", vibe: "Central, compact, young professional", pricing: "High competition", expat: "Strong student & tech mix", commute: "Hub station — nationwide access" },
    { label: "Eindhoven", href: "/netherlands/eindhoven/", vibe: "Tech & design", pricing: "Moderate-high", expat: "ASML & Brainport professionals", commute: "Car common; Eindhoven Airport" },
    { label: "Haarlem", href: "/netherlands/haarlem/", vibe: "Historic, Amsterdam-adjacent", pricing: "High Randstad", expat: "Families & commuters", commute: "15 min train to Amsterdam" },
    { label: "Leiden", href: "/netherlands/leiden/", vibe: "University city, canals", pricing: "High for size", expat: "Academic & pharma", commute: "Randstad links; bike culture" },
    { label: "Delft", href: "/netherlands/delft/", vibe: "Tech university town", pricing: "High student/pro demand", expat: "TU Delft community", commute: "The Hague & Rotterdam links" },
    { label: "Groningen", href: "/netherlands/groningen/", vibe: "Northern student city", pricing: "Moderate", expat: "University & healthcare", commute: "Remote from Randstad — self-contained" },
    { label: "Arnhem", href: "/netherlands/arnhem/", vibe: "Green, eastern city", pricing: "Moderate", expat: "Smaller international base", commute: "Germany border proximity" },
    { label: "Nijmegen", href: "/netherlands/nijmegen/", vibe: "Oldest city, university", pricing: "Moderate", expat: "Academic & healthcare", commute: "Near German border" },
    { label: "Maastricht", href: "/netherlands/maastricht/", vibe: "Southern, European feel", pricing: "Moderate", expat: "EU institutions & cross-border", commute: "Belgium/Germany cross-border" },
  ],
  mortgageTypeCards: [
    { title: "Fixed interest", body: "Interest rate locked for a set period — payment predictability; early repayment rules apply." },
    { title: "Variable interest", body: "Rate follows market — can fall or rise; understand cap and review periods." },
    { title: "Mortgage term", body: "Typical 20–30 year horizon — match to stay plans and retirement timing." },
    { title: "Repayment structure", body: "Annuitair (linear decline in interest) vs linear (fixed principal) — monthly pattern differs." },
  ],
  mortgageTypeTips: [
    "AFM-regulated advisers explain product fit — this guide does not recommend specific products.",
    "Fixed vs variable is a personal risk choice — depends on stay horizon and rate environment.",
    "National Mortgage Guarantee (NHG) may apply under price caps — verify current limits annually.",
    "Do not treat blog examples as quotes — lender offers change with market conditions.",
  ],
  taxTips: [
    "Transfer tax (overdrachtsbelasting) applies at purchase — rate depends on property use classification.",
    "Mortgage interest deduction (hypotheekrenteaftrek) may reduce taxable income for qualifying owner-occupiers — rules evolve.",
    "Municipal property tax (OZB) and waste/water levies continue after purchase — vary by gemeente.",
    "Connect tax planning to net salary, payroll and expat tax guides — not DIY legal advice.",
  ],
  taxTopics: [
    { title: "Transfer tax", body: "Paid at purchase through the notary — owner-occupied vs investment rates differ significantly." },
    { title: "Mortgage interest deduction", body: "Potential income tax relief on qualifying owner-occupied mortgage interest — verify on Belastingdienst." },
    { title: "Property tax (OZB)", body: "Annual municipal levy on homeowners — budget alongside mortgage and insurance." },
    { title: "Municipal user charges", body: "Waste, water board and other local levies — not part of kosten koper but ongoing cost." },
  ],
  challengeCards: [
    { title: "Language barriers", body: "Contracts, VvE documents and notary meetings may be Dutch — translation and legal review help." },
    { title: "Understanding contracts", body: "Koopovereenkomst and resolutieve voorwaarden need careful review before signing." },
    { title: "Mortgage paperwork", body: "Employment letters, permits and income proof must match lender checklists." },
    { title: "Viewing competition", body: "Popular properties attract many bidders — prepare budget and strategy early." },
    { title: "Overbidding pressure", body: "Emotional bidding can exceed sensible limits — set a ceiling with your advisor." },
    { title: "Temporary contracts", body: "Short employment may limit lenders — timing purchase with contract renewal matters." },
    { title: "Trustworthy advisors", body: "Use AFM-regulated mortgage advisers and registered agents — compare fees." },
    { title: "Understanding neighborhoods", body: "Visit at different times; check noise, schools, parking and future development." },
  ],
  apartmentPoints: [
    { title: "VvE (owners association)", body: "Monthly bijdrage, maintenance plans and reserve fund health affect long-term cost." },
    { title: "Building rules", body: "Alterations, pets and short-term rental may be restricted in the VvE statutes." },
    { title: "Shared maintenance", body: "Roof, facade and lift costs shared — review MJOP (maintenance plan)." },
  ],
  housePoints: [
    { title: "Full maintenance", body: "You own structure, roof, garden and installations — budget for repairs." },
    { title: "Renovation freedom", body: "More control than apartments — but check monument status and permits." },
    { title: "Energy label", body: "Poor labels imply upgrade costs — factor into offer and mortgage energy loan options." },
  ],
  apartmentVsHouseTips: [
    "Apartments: request VvE (owners association) minutes, reserve fund balance and MJOP maintenance plan before bidding.",
    "Houses: budget for roof, facade, heating system and garden — no shared reserve fund to spread big repairs.",
    "Energy label C or below often means renovation costs — some lenders offer energy improvement loans.",
    "Monument or protected buildings may restrict alterations — confirm with gemeente and a notary.",
  ],
  vveChecklist: [
    "Monthly VvE bijdrage and any planned special assessments (bijzondere bijdrage).",
    "Reserve fund (reservefonds) balance vs building age and maintenance backlog.",
    "MJOP multi-year maintenance plan — roof, lift, facade timelines.",
    "VvE rules on short-term rental, pets, alterations and owner-occupation.",
    "Outstanding disputes or litigation involving the VvE.",
  ],
  mistakeCards: [
    { title: "Bidding without mortgage advice", body: "Winning a bid you cannot finance wastes time and may forfeit deposits if conditions are missed." },
    { title: "Ignoring kosten koper", body: "Assuming the mortgage covers everything — buyer costs usually need separate savings." },
    { title: "Overbidding beyond appraisal", body: "The taxatierapport caps what the bank finances — the gap must come from own funds." },
    { title: "Skipping technical inspection", body: "Hidden structural issues can cost tens of thousands after transfer." },
    { title: "Signing without legal review", body: "Koopovereenkomst deadlines and resolutieve voorwaarden bind quickly — understand before you sign." },
    { title: "Underestimating VvE risk", body: "Weak reserve funds or pending major works can raise monthly costs sharply after purchase." },
  ],
  mistakesTips: [
    "Set a maximum bid with your mortgage adviser before viewings — emotional overbidding is common in Randstad markets.",
    "Plan kosten koper as a separate savings pot — not as part of the mortgage amount.",
    "Treat the technical inspection and VvE document review as non-optional for apartments.",
    "This guide does not replace contract review — use a property lawyer for koopovereenkomst questions.",
  ],
  questionsSectionTips: [
    "Highly skilled migrants follow the same mortgage framework — employment stability and documentation matter more than nationality.",
    "Plan own funds for kosten koper even when 100% property financing is discussed — banks rarely cover all buyer-side costs.",
    "Overbidding above appraisal creates a gap from savings — model this before you set your maximum bid.",
    "Compare buying with renting using total monthly cost and stay horizon — not purchase price alone.",
  ],
  relatedGuideTips: [
    "Start with salary and net pay guides to model mortgage capacity before city comparison.",
    "Use the rent affordability calculator to stress-test housing budget alongside kosten koper.",
    "Read the moving guide for BSN, registration and timeline context that runs parallel to house hunting.",
    "Connect transfer tax questions to the Netherlands Taxes hub — not forum anecdotes.",
  ],
  expatQuestions: [
    { q: "Can expats buy property?", a: "Yes — foreign nationals and international residents can buy Dutch property. Mortgages and residency rules apply per lender; confirm your situation with regulated mortgage advice." },
    { q: "Can highly skilled migrants get mortgages?", a: "Many highly skilled migrants with stable employment and valid residence permits are approved by Dutch lenders — but approval is never guaranteed and depends on income, contract and lender policy." },
    { q: "How much deposit do I need?", a: "Plan own funds for kosten koper — at €400,000 often ~€13,500 (€8,000 transfer tax + ~€5,500 notary/valuation/advice/inspection). Add any overbid gap (e.g. €15,000 if offer €425k but appraisal €410k). Some buyers finance 100% of the property price but not buyer costs." },
    { q: "What is overbidding?", a: "Offering above asking to win — e.g. bid €425,000 on €400,000 asking. Mortgage capped at appraisal (€410,000) → €15,000 from savings before the bank finances the rest." },
    { q: "Is buying better than renting?", a: "Depends on stay length, employment stability and local market. Buying suits long-term roots; renting suits short assignments and uncertain relocation." },
    { q: "How long does the process take?", a: "Often roughly 6–12 weeks from accepted offer to notarial transfer and keys — can be faster or slower depending on mortgage, conditions and parties." },
    { q: "What additional costs apply?", a: "At €400,000 owner-occupied: ~€8,000 transfer tax (2%), ~€2,000 notary, ~€750 valuation, ~€500 inspection, ~€2,250 mortgage advice ≈ €13,500 total kosten koper. Buyer's agent (~1%) and NHG fee (0.4% of loan) are extra." },
    { q: "Is Amsterdam too expensive?", a: "Amsterdam has among the highest price pressure in the Netherlands — not impossible to buy, but budgets, overbidding and commute alternatives need realistic planning." },
  ],
  relatedHousingGuides: [
    { label: "Renting in the Netherlands", href: RENTING_NETHERLANDS_PATH, status: "comingSoon", description: "Full renting guide — contracts, search and tenant rights." },
    { label: "Housing Costs Netherlands", href: "/netherlands/housing/housing-costs-netherlands/", status: "comingSoon", description: "Typical housing costs for renters and buyers." },
    { label: "Mortgage Guide Netherlands", href: "/netherlands/housing/mortgages-netherlands-expats/", status: "comingSoon", description: "Deep dive on expat mortgages and lender requirements." },
    { label: "Dutch Cities Guide", href: CITIES_HUB_PATH, status: "live", description: "Compare cities before choosing where to buy." },
    { label: "Moving to the Netherlands", href: MOVING_TO_NETHERLANDS_PATH, status: "live", description: "Relocation hub — registration, employment and housing timeline." },
    { label: "Netherlands Housing Hub", href: HOUSING_HUB_PATH, status: "live", description: "Central housing guide for expats." },
  ] satisfies BuyingHouseNetherlandsLink[],
  servicesWhenToUse: [
    { title: "Mortgage advisors", body: "Indicative capacity, lender selection and application coordination — AFM-regulated." },
    { title: "Real estate agents", body: "Aankoopmakelaar for search, bidding strategy and technical coordination." },
    { title: "Relocation services", body: "Move-year orientation, city shortlists and admin setup alongside housing search." },
    { title: "Property lawyers", body: "Contract review, VvE analysis and notary process questions." },
    { title: "Financial advisors", body: "Broader financial planning context — not mortgage product sales." },
    { title: "Technical inspectors", body: "Bouwkundige keuring before waiving inspection conditions." },
  ],
  servicesTips: [
    "Mortgage advice is standard in the Netherlands — compare adviser fees and lender access.",
    "Use property lawyers for contract review — purchase agreements can be binding quickly.",
    "Relocation services help with city choice — they do not guarantee mortgage approval.",
    "This guide does not endorse specific providers — orientation only.",
  ],
  services: [
    { label: "Mortgage advisors", href: "/netherlands/services/mortgage-advisors/", status: "comingSoon", description: "Directory of AFM-regulated hypotheekadviseurs for expats." },
    { label: "Real estate agents", href: "/netherlands/services/real-estate-agents/", status: "comingSoon", description: "Buyer's and seller's agents for Dutch property search." },
    { label: "Relocation services", href: "/netherlands/services/relocation-services/", status: "live", description: "Move support including housing orientation." },
    { label: "Property lawyers", href: "/netherlands/services/property-lawyers/", status: "comingSoon", description: "Legal review for purchase contracts and VvE." },
    { label: "Financial advisors", href: "/netherlands/services/financial-advisors/", status: "comingSoon", description: "Financial planning context for major purchases." },
  ] satisfies BuyingHouseNetherlandsLink[],
  faqQuickChecks: [
    "At €400,000 plan ~€13,500 kosten koper from savings — separate from the mortgage amount.",
    "NHG 2026 cap: €470,000 (€498,200 with energy improvements) — verify on nhg.nl.",
    "Overbid example: offer €425k, appraisal €410k → €15k from savings before financing.",
    "Owner-occupied transfer tax 2% vs investment 10.4% — confirm classification with Belastingdienst.",
  ],
  faq: [
    { q: "Can expats buy property in the Netherlands?", a: "Yes. Foreign nationals and international residents can own Dutch property. Mortgage eligibility depends on employment, income, residency and lender policy — not nationality alone." },
    { q: "Can highly skilled migrants get mortgages?", a: "Many highly skilled migrants with stable employment and valid permits are approved by Dutch lenders. Approval is never guaranteed — each application is assessed individually." },
    { q: "What is overbidding?", a: "Bidding above asking to win — e.g. offer €425,000 on €400,000 asking. Mortgage is typically capped at appraisal (€410,000) → €15,000 gap from savings before financing covers the rest." },
    { q: "How much deposit do I need?", a: "Plan own funds for kosten koper — at €400,000 typically ~€13,500 (€8,000 transfer tax + ~€5,500 notary/valuation/advice/inspection). Add any overbid gap (e.g. €15,000 if offer €425k but appraisal €410k)." },
    { q: "Is buying better than renting?", a: "Buying may suit long-term stays and family relocation. Renting may suit short assignments, probation periods and uncertain plans. Compare total costs and flexibility." },
    { q: "What costs apply when buying?", a: "At €400,000 owner-occupied: ~€13,500 kosten koper (€8,000 transfer tax at 2% + notary, valuation, advice, inspection). Investment rate 10.4% → ~€41,600 transfer tax alone at €400,000." },
    { q: "How long does the process take?", a: "Often roughly 6–12 weeks from accepted offer to notarial transfer. Timelines vary with mortgage approval, inspection conditions and party availability." },
    { q: "Can foreigners own Dutch property?", a: "Yes — there is no general prohibition on foreign ownership. Mortgages, tax classification and residency rules still apply." },
  ],
  officialSources: [
    { label: "Government.nl", href: "https://www.government.nl/", description: "Official Dutch government information on housing, residency and public services." },
    { label: "Business.gov.nl", href: "https://business.gov.nl/", description: "Practical government portal for living and working in the Netherlands." },
    { label: "Belastingdienst", href: "https://www.belastingdienst.nl/", description: "Transfer tax, mortgage interest deduction and property tax guidance." },
    { label: "Kadaster", href: "https://www.kadaster.nl/", description: "Land registry — property ownership records and cadastral information." },
    { label: "AFM", href: "https://www.afm.nl/en", description: "Financial markets authority — mortgage adviser regulation and consumer information." },
    { label: "NederlandWereldwijd", href: "https://www.nederlandwereldwijd.nl/", description: "Government information for Dutch nationals abroad and international context." },
  ],
  sourcesDisclaimer:
    "Property regulations, mortgage rules, transfer tax rates and exemptions may change. Always verify current requirements through official resources and licensed mortgage advisers before purchasing.",
  relatedGuides: [
    { label: "Netherlands Housing Hub", href: HOUSING_HUB_PATH, status: "live", description: "Central housing guide for expats." },
    { label: "Renting in the Netherlands", href: RENTING_NETHERLANDS_PATH, status: "comingSoon", description: "Renting alternative for shorter stays." },
    { label: "Netherlands Taxes Hub", href: TAXES_HUB_PATH, status: "live", description: "Transfer tax and mortgage interest deduction context." },
    { label: "Expat Salary Guide", href: EXPAT_SALARY_NETHERLANDS_PATH, status: "live", description: "Salary expectations for mortgage capacity planning." },
    { label: "Net Salary Guide", href: NET_SALARY_NETHERLANDS_PATH, status: "live", description: "Take-home pay context for affordability." },
    { label: "Moving to the Netherlands", href: MOVING_TO_NETHERLANDS_PATH, status: "live", description: "Relocation timeline and housing setup." },
    { label: "Dutch Cities Guide", href: CITIES_HUB_PATH, status: "live", description: "Compare cities before choosing where to buy." },
  ] satisfies BuyingHouseNetherlandsLink[],
  exploreNextCards: [
    { label: "Renting in the Netherlands", href: RENTING_NETHERLANDS_PATH, status: "comingSoon", description: "Full renting guide for expats." },
    { label: "Mortgage Guide", href: "/netherlands/housing/mortgages-netherlands-expats/", status: "comingSoon", description: "Deep dive on expat mortgages." },
    { label: "Housing Costs", href: "/netherlands/housing/housing-costs-netherlands/", status: "comingSoon", description: "Typical housing costs overview." },
    { label: "Dutch Cities Guide", href: CITIES_HUB_PATH, status: "live", description: "Compare cities and housing markets." },
    { label: "Moving to the Netherlands", href: MOVING_TO_NETHERLANDS_PATH, status: "live", description: "Main relocation guide." },
  ] satisfies BuyingHouseNetherlandsLink[],
  officialPlanningCta: {
    title: "Confirm costs and rules officially",
    description:
      "The figures on this page use published 2026 buyer-cost parameters and indicative worked examples. For transfer tax classification, registration and your personal mortgage capacity, verify on Belastingdienst, Kadaster and with AFM-regulated mortgage advice.",
    primaryCta: { label: "Rent affordability calculator", href: RENT_AFFORDABILITY_TOOL_PATH },
    secondaryCta: { label: "Belastingdienst transfer tax", href: "https://www.belastingdienst.nl/wps/wcm/connect/nl/belastingen/content/overdrachtsbelasting" },
    disclaimer: buyingHouseReference2026.disclaimer,
  },
} as const;
