import type { CityComparisonId } from "../types";
import type { NormalizedCityProfile } from "./types";

/**
 * Normalized profiles (1–10). Higher rentLevel / livingCostLevel = more expensive / tighter market.
 * careerStrength, expatEase, etc. = editorial “more of this attribute in typical expat planning stories”.
 */
export const NORMALIZED_CITY_PROFILES: Record<CityComparisonId, NormalizedCityProfile> = {
  amsterdam: {
    id: "amsterdam",
    displayName: "Amsterdam",
    colProxy: "amsterdam",
    rentPlanningMult: 1,
    rentLevel: 10,
    livingCostLevel: 9,
    careerStrength: 10,
    expatEase: 10,
    familyFit: 7,
    nightlife: 9,
    calmNature: 4,
    commuteHubStrength: 10,
    internationalSchoolSupport: 9,
    languageBarrierEase: 9,
    comments: "Maximum choice for jobs, English day-to-day, and going out — paired with the country’s steepest rents and busiest flat market.",
  },
  rotterdam: {
    id: "rotterdam",
    displayName: "Rotterdam",
    colProxy: "rotterdam",
    rentPlanningMult: 1,
    rentLevel: 7,
    livingCostLevel: 7,
    careerStrength: 9,
    expatEase: 9,
    familyFit: 8,
    nightlife: 8,
    calmNature: 5,
    commuteHubStrength: 9,
    internationalSchoolSupport: 8,
    languageBarrierEase: 8,
    comments: "Major port and logistics hub — strong urban energy with somewhat softer rent than Amsterdam.",
  },
  "the-hague": {
    id: "the-hague",
    displayName: "The Hague",
    colProxy: "the-hague",
    rentPlanningMult: 1,
    rentLevel: 8,
    livingCostLevel: 7,
    careerStrength: 8,
    expatEase: 9,
    familyFit: 9,
    nightlife: 6,
    calmNature: 7,
    commuteHubStrength: 8,
    internationalSchoolSupport: 9,
    languageBarrierEase: 8,
    comments: "Government and institutions town — calmer pace with a strong schools story.",
  },
  utrecht: {
    id: "utrecht",
    displayName: "Utrecht",
    colProxy: "utrecht",
    rentPlanningMult: 1,
    rentLevel: 9,
    livingCostLevel: 8,
    careerStrength: 9,
    expatEase: 9,
    familyFit: 9,
    nightlife: 7,
    calmNature: 6,
    commuteHubStrength: 9,
    internationalSchoolSupport: 8,
    languageBarrierEase: 8,
    comments: "Trains in every direction and a lively compact center — a favourite for families and Amsterdam commuters; housing moves fast.",
  },
  eindhoven: {
    id: "eindhoven",
    displayName: "Eindhoven",
    colProxy: "eindhoven",
    rentPlanningMult: 1,
    rentLevel: 6,
    livingCostLevel: 6,
    careerStrength: 9,
    expatEase: 8,
    familyFit: 8,
    nightlife: 6,
    calmNature: 6,
    commuteHubStrength: 7,
    internationalSchoolSupport: 7,
    languageBarrierEase: 8,
    comments: "Tech and manufacturing depth — often easier monthly story than Randstad core for similar roles.",
  },
  haarlem: {
    id: "haarlem",
    displayName: "Haarlem",
    colProxy: "haarlem",
    rentPlanningMult: 1,
    rentLevel: 8,
    livingCostLevel: 7,
    careerStrength: 7,
    expatEase: 8,
    familyFit: 9,
    nightlife: 6,
    calmNature: 8,
    commuteHubStrength: 8,
    internationalSchoolSupport: 8,
    languageBarrierEase: 8,
    comments: "Smaller-city calm near Amsterdam — expect commuter rhythm if work is in the capital.",
  },
  leiden: {
    id: "leiden",
    displayName: "Leiden",
    colProxy: "leiden",
    rentPlanningMult: 1,
    rentLevel: 7,
    livingCostLevel: 7,
    careerStrength: 7,
    expatEase: 8,
    familyFit: 8,
    nightlife: 6,
    calmNature: 8,
    commuteHubStrength: 8,
    internationalSchoolSupport: 8,
    languageBarrierEase: 8,
    comments: "Compact university town — biotech and Randstad links with a quieter core than Rotterdam.",
  },
  delft: {
    id: "delft",
    displayName: "Delft",
    colProxy: "delft",
    rentPlanningMult: 1,
    rentLevel: 7,
    livingCostLevel: 7,
    careerStrength: 7,
    expatEase: 8,
    familyFit: 8,
    nightlife: 5,
    calmNature: 8,
    commuteHubStrength: 8,
    internationalSchoolSupport: 7,
    languageBarrierEase: 8,
    comments: "University and tech corridor to Rotterdam and The Hague — quieter nights than big cities.",
  },
  groningen: {
    id: "groningen",
    displayName: "Groningen",
    colProxy: "groningen",
    rentPlanningMult: 1,
    rentLevel: 5,
    livingCostLevel: 5,
    careerStrength: 7,
    expatEase: 8,
    familyFit: 8,
    nightlife: 7,
    calmNature: 7,
    commuteHubStrength: 6,
    internationalSchoolSupport: 6,
    languageBarrierEase: 7,
    comments: "Lower rent pressure and student energy — far from Randstad office gravity for daily commuting.",
  },
  amstelveen: {
    id: "amstelveen",
    displayName: "Amstelveen",
    colProxy: "haarlem",
    rentPlanningMult: 0.96,
    rentLevel: 8,
    livingCostLevel: 7,
    careerStrength: 7,
    expatEase: 9,
    familyFit: 9,
    nightlife: 5,
    calmNature: 8,
    commuteHubStrength: 8,
    internationalSchoolSupport: 8,
    languageBarrierEase: 9,
    comments: "Leafy, family-friendly suburb near Amsterdam — how easy life feels depends on metro, bus, or bike from your exact street.",
  },
  rotterdam_commuter_belt: {
    id: "rotterdam_commuter_belt",
    displayName: "Rotterdam commuter belt",
    colProxy: "rotterdam",
    rentPlanningMult: 0.9,
    rentLevel: 6,
    livingCostLevel: 6,
    careerStrength: 7,
    expatEase: 7,
    familyFit: 8,
    nightlife: 4,
    calmNature: 8,
    commuteHubStrength: 7,
    internationalSchoolSupport: 7,
    languageBarrierEase: 7,
    comments: "Stand-in for smaller towns around Rotterdam — often cheaper on paper, but the right station and line make or break daily life.",
  },
  the_hague_commuter_belt: {
    id: "the_hague_commuter_belt",
    displayName: "The Hague commuter belt",
    colProxy: "the-hague",
    rentPlanningMult: 0.9,
    rentLevel: 6,
    livingCostLevel: 6,
    careerStrength: 7,
    expatEase: 8,
    familyFit: 9,
    nightlife: 5,
    calmNature: 8,
    commuteHubStrength: 7,
    internationalSchoolSupport: 8,
    languageBarrierEase: 8,
    comments: "Stand-in for Zoetermeer-style commutes — family-friendly budget on one side, office in The Hague or Rotterdam on the other.",
  },
  other: {
    id: "other",
    displayName: "Other Netherlands",
    colProxy: "other",
    rentPlanningMult: 1,
    rentLevel: 6,
    livingCostLevel: 6,
    careerStrength: 6,
    expatEase: 7,
    familyFit: 7,
    nightlife: 5,
    calmNature: 7,
    commuteHubStrength: 7,
    internationalSchoolSupport: 6,
    languageBarrierEase: 7,
    comments: "Generic NL anchor when your municipality is not listed — re-run with specific cities when you can.",
  },
};

export function getNormalizedCityProfile(id: CityComparisonId): NormalizedCityProfile {
  return NORMALIZED_CITY_PROFILES[id];
}

/** Map 1–10 → 0–100 for legacy consumers / weighted blends. */
export function scale1to100(n: number): number {
  return Math.max(0, Math.min(100, Math.round(n * 10)));
}
