import type { ClauseCategory, FindingRiskLabel } from "@/src/lib/tools/contract-scanner/types";

export type ClausePatternDef = {
  id: string;
  category: ClauseCategory;
  subcategory: string;
  re: RegExp;
  /** Base label; heuristics may adjust. */
  riskLabel: FindingRiskLabel;
  explain: string;
  whyItMatters: string;
  question: string;
  broadUnlessContains?: string[];
};

/**
 * Clause dictionary: Dutch + English variants. Order can matter for first-match wins per id (deduped later).
 */
export const CLAUSE_PATTERNS: ClausePatternDef[] = [
  {
    id: "permanent-indefinite",
    category: "contract_structure",
    subcategory: "Permanent / indefinite term",
    re: /\b(permanent|indefinite|onbepaalde\s+tijd|voor\s+onbepaalde\s+tijd|arbeidsovereenkomst\s+voor\s+onbepaalde\s+tijd|employment\s+of\s+indefinite|duurloze\s+arbeidsovereenkomst)\b/i,
    riskLabel: "common_standard",
    explain: "The document references a permanent or indefinite employment term.",
    whyItMatters: "Indefinite contracts usually have different notice and end-date expectations than fixed-term roles.",
    question: "Please confirm this is an indefinite (permanent) contract and whether any side letter or probation changes the end date or renewal rules.",
  },
  {
    id: "fixed-term",
    category: "contract_structure",
    subcategory: "Fixed-term contract",
    re: /\b(fixed[\s-]?term|bepaalde\s+tijd|tijdelijke\s+arbeidsovereenkomst|contract\s+voor\s+bepaalde\s+tijd|einddatum|einde\s+arbeidsovereenkomst|end\s+date\s+of\s+employment|duur\s+van\s+deze\s+overeenkomst|contractduur)\b/i,
    riskLabel: "worth_confirming",
    explain: "A fixed-term or end-dated arrangement is referenced.",
    whyItMatters: "Renewal rules, conversion to permanent, and notice can differ from indefinite contracts.",
    question: "What exactly happens at the end date: automatic renewal, mutual extension, or conversion to indefinite — and how is notice calculated?",
  },
  {
    id: "probation",
    category: "contract_structure",
    subcategory: "Probation / trial period",
    re: /\b(probation|trial\s+period|proeftijd|proefperiode|proeftijdperiode|proeftijd\s+van|proefmaand)\b/i,
    riskLabel: "worth_confirming",
    explain: "A probation or trial period is mentioned.",
    whyItMatters: "Shorter notice during probation is common in the Netherlands; length and rules should match CAO/law context.",
    question: "What is the exact probation length in calendar months, and what are employee and employer notice periods during and immediately after probation?",
  },
  {
    id: "cao",
    category: "contract_structure",
    subcategory: "CAO / collective agreement",
    re: /\b(CAO|cao|collective\s+(labo[u]?r\s+)?agreement|bedrijfsreglement|metalektro|ABU|NBBU|toepasselijkheid\s+van\s+de\s+cao|van\s+toepassing\s+zijn\s+de\s+bepalingen\s+van)\b/i,
    riskLabel: "worth_confirming",
    explain: "A collective labour agreement (CAO) or similar reference appears.",
    whyItMatters: "Many pay, leave, and notice rules may live in the CAO rather than this document.",
    question: "Which CAO edition applies to my role and start date, and can you share the articles covering salary scales, overtime, leave, and notice?",
  },
  {
    id: "handbook-incorporation",
    category: "policy_data",
    subcategory: "Handbook / policy incorporation",
    re: /\b(employee\s+handbook|staff\s+handbook|medewerkershandboek|personeelshandboek|personnel\s+manual|employee\s+policies|personnel\s+polic(?:y|ies)|arbeidsvoorwaarden(?:\s+handboek)?|huisregels|code\s+of\s+conduct|gedragscode|reglement|policy\s+as\s+amended|incorporated\s+by\s+reference|maken\s+deel\s+uit\s+van\s+deze\s+overeenkomst|zijn\s+van\s+toepassing\s+de\s+(?:interne\s+)?(?:regels|beleidsregels)|company\s+policies\s+form\s+part|intranet\s+.*\bpolic)/i,
    riskLabel: "broad_strong_wording",
    explain: "The contract appears to incorporate handbook, intranet policies, or rules by reference.",
    whyItMatters: "Material terms may sit outside this PDF — you may be bound to documents you have not reviewed.",
    question: "Please send the current handbook, discipline/sanctions policy, overtime policy, and absence/illness procedure referenced here before signing.",
    broadUnlessContains: ["appendix", "bijlage", "annex", "exhibit", "bijgevoegd"],
  },
  {
    id: "gross-salary",
    category: "salary_compensation",
    subcategory: "Gross salary",
    re: /\b(bruto\s*(salaris|jaarsalaris|maandsalaris|jaarloon|maandloon|bezoldiging)?|gross\s*(salary|annual|monthly|remuneration|comp(?:ensation)?)|salaris\s+(?:bedraagt|is|zijn)|base\s+salary|jaarsalaris|maandsalaris|annual\s+salary|monthly\s+salary|yearly\s+salary|remuneration\s+of|jaarloon|maandloon|loon\s+per\s+maand|salaris\s+per\s+jaar|€\s*[\d.,]+\s*(?:per\s+)?(?:month|maand|year|jaar)|eur\s*[\d.,]+\s*(?:gross|bruto))\b/i,
    riskLabel: "worth_confirming",
    explain: "Salary or remuneration wording is present.",
    whyItMatters: "Confirm gross vs net, pay period (monthly/annual), and currency.",
    question: "Is the figure quoted gross per calendar month or per year, in euros, and does it exclude or include holiday allowance and any thirteenth month?",
  },
  {
    id: "holiday-allowance",
    category: "salary_compensation",
    subcategory: "Holiday allowance",
    re: /\b(vakantiegeld|vakantietoeslag|vakantiebijslag|holiday\s+allowance|8\s*%|8[,.]33?\s*%|8,3\s*%|acht\s+procent|vacation\s+pay|holiday\s+pay|jaarlijks\s+vakantiegeld)\b/i,
    riskLabel: "worth_confirming",
    explain: "Holiday allowance (vakantiegeld) is referenced.",
    whyItMatters: "Timing (accrued vs May payout) and inclusion in quoted salary vary.",
    question: "Is vakantiegeld on top of the quoted base, when is it paid (e.g. May), and is any part included in monthly pay?",
  },
  {
    id: "pension",
    category: "salary_compensation",
    subcategory: "Pension",
    re: /\b(pensioen|pensioenfonds|pensioenregeling|pensioenpremie|premie\s+pensioen|bedrijfstakpensioen|pension(\s+(scheme|plan|fund|via))?|PPI|OPP|stichting\s+pensioen|werkgeversbijdrage|employer\s+pension|participatie\s+in\s+het\s+pensioen)\b/i,
    riskLabel: "worth_confirming",
    explain: "Pension contributions or a scheme are mentioned.",
    whyItMatters: "Employer contribution percentage and waiting periods affect total compensation.",
    question: "Which pension fund or contract applies, what are the employee and employer contribution percentages, and is there a waiting or participation period?",
  },
  {
    id: "bonus-variable",
    category: "salary_compensation",
    subcategory: "Bonus / variable pay",
    re: /\b(bonus|variable\s+comp(?:ensation)?|variabele\s+beloning|commission|commissie|provisie|incentive|13th\s+month|dertiende\s+maand|winstdeling|performance\s+pay|target\s+bonus|STI|LTI|doelbonus|resultaatafhankelijk)\b/i,
    riskLabel: "worth_confirming",
    explain: "Variable or bonus compensation is referenced.",
    whyItMatters: "Discretionary vs guaranteed bonus language changes planning certainty.",
    question: "Is this bonus guaranteed, on-target only, or fully discretionary — what are the KPIs, payout month, and any clawback if I leave mid-year?",
  },
  {
    id: "overtime-included",
    category: "salary_compensation",
    subcategory: "Overtime included in salary",
    re: /\b(all\s+reasonable\s+overtime|alle\s+redelijke\s+overwerk|reasonably\s+required\s+overtime|overtime\s+included|meewerkers?|overwerk\s+(?:is\s+)?(?:begrepen|inbegrepen)|geen\s+extra\s+vergoeding\s+voor\s+overwerk|geen\s+vergoeding\s+voor\s+overuren|overuren\s+zijn\s+inbegrepen|additional\s+hours\s+without\s+extra\s+pay|onbetaalde\s+overuren)\b/i,
    riskLabel: "potentially_restrictive",
    explain: "The wording suggests overtime may be included in base salary or unpaid beyond normal hours.",
    whyItMatters: "You may be expected to work extra hours without additional pay unless CAO/law says otherwise.",
    question: "Which hours count as overtime versus normal hours, what is the CAO rate, and how is overtime registered and paid or explicitly excluded?",
  },
  {
    id: "overtime-paid",
    category: "salary_compensation",
    subcategory: "Overtime compensation",
    re: /\b(overwerkvergoeding|vergoeding\s+overuren|overtime\s+(?:pay|rate|compensation)|toeslag\s+voor\s+overwerk)\b/i,
    riskLabel: "common_standard",
    explain: "Overtime pay or allowance is mentioned.",
    whyItMatters: "Clarifies that some overtime may be compensated separately.",
    question: "What rate applies to weekday, weekend, and public-holiday overtime, and from how many hours per week does overtime start?",
  },
  {
    id: "notice-period",
    category: "notice_termination",
    subcategory: "Notice period",
    re: /\b(opzegtermijn|opzeggingstermijn|opzegging|opzeggen|notice\s+period|termination\s+notice|period\s+of\s+notice|month[s]?\s+notice|kalendermaand(?:en)?\s+opzegtermijn|opzeggen\s+met\s+ingang)\b/i,
    riskLabel: "worth_confirming",
    explain: "Notice or termination period language is present.",
    whyItMatters: "Employee vs employer notice can differ; probation notice is often shorter.",
    question: "What are employee and employer notice periods after probation (in calendar months), and do they mirror the CAO or deviate?",
  },
  {
    id: "garden-leave",
    category: "notice_termination",
    subcategory: "Garden leave / paid leave",
    re: /\b(garden\s+leave|non-active\s+duty|thuisstelling|betaald\s+verlof\s+bij\s+beëindiging)\b/i,
    riskLabel: "worth_confirming",
    explain: "Garden leave or similar inactive-duty wording may appear.",
    whyItMatters: "Clarifies whether you must stay available, and how compensation works during the period.",
    question: "During garden leave or inactive duty, am I relieved of all duties, and do salary, pension accrual, and benefits continue unchanged?",
  },
  {
    id: "non-compete",
    category: "restrictive_clauses",
    subcategory: "Non-compete",
    re: /\b(non[\s-]?compete|concurrentiebeding|niet\s+concurreren|noncompetition|post[\s-]?employment\s+restriction|verbod\s+op\s+concurrentie|werkgever\s+verbiedt\s+.*concurrent)\b/i,
    riskLabel: "potentially_restrictive",
    explain: "A non-compete or similar post-employment restriction is referenced.",
    whyItMatters: "This may limit where you can work after leaving. Geography, duration, and scope matter for enforceability and planning.",
    question: "Please specify the non-compete duration, geographic scope (km or countries), role/sector limits, and whether monthly compensation is paid during the restriction.",
    broadUnlessContains: ["month", "maand", "year", "jaar", "km", "kilometer", "meter", "radius", "geographic", "geo", "functie", "role", "sector", "bedrijfstak"],
  },
  {
    id: "non-solicit",
    category: "restrictive_clauses",
    subcategory: "Non-solicitation / relations",
    re: /\b(non[\s-]?solicit|relatiebeding|client\s+non[\s-]?solicit|klantenbeding|niet\s+werven|verbod\s+op\s+werving)\b/i,
    riskLabel: "potentially_restrictive",
    explain: "Non-solicitation or client relationship restrictions may apply.",
    whyItMatters: "Can affect future client contact depending on scope.",
    question: "Which customers, prospects, or categories does the relatiebeding cover, for how long after termination, and does it restrict LinkedIn or passive approaches?",
  },
  {
    id: "confidentiality",
    category: "restrictive_clauses",
    subcategory: "Confidentiality",
    re: /\b(confidentiality|keep\s+confidential|confidential\s+information|confidential\s+all|non[\s-]?disclosure|geheimhouding|geheimhoudingsplicht|geheimhoudingsovereenkomst|stilzwijgen|vertrouwelijkheid|duty\s+of\s+confidence|NDA)\b/i,
    riskLabel: "common_standard",
    explain: "Confidentiality or secrecy obligations are mentioned.",
    whyItMatters: "Broad definitions of confidential information can affect side projects and public speaking.",
    question: "Are there carve-outs for publicly available information, general professional skills, and knowledge acquired before employment?",
  },
  {
    id: "ip-assignment",
    category: "restrictive_clauses",
    subcategory: "IP / inventions",
    re: /\b(intellectual\s+property|IP\s+rights?|intellectueel\s+eigendom|IE-rechten|inventions?\s+assignment|werk\s+in\s+dienstbetrekking|werkproduct|octrooi|patent\s+assignment|alle\s+rechten\s+berusten\s+bij|auteursrecht.*werkgever)\b/i,
    riskLabel: "worth_confirming",
    explain: "IP assignment or ownership of work product is addressed.",
    whyItMatters: "Side projects and prior inventions may need explicit carve-outs.",
    question: "How do I list prior inventions and open-source side projects as excluded, and who owns improvements made on personal time without company resources?",
  },
  {
    id: "side-job",
    category: "restrictive_clauses",
    subcategory: "Side work / nevenwerkzaamheden",
    re: /\b(nevenwerkzaamheden|nevenactiviteit|bijberoep|side\s+(job|employment|business|activity)|secondary\s+employment|andere\s+werkzaamheden|written\s+consent.*other\s+work|toestemming.*nevenwerk|zonder\s+toestemming\s+.*werk)\b/i,
    riskLabel: "worth_confirming",
    explain: "Restrictions or consent requirements for secondary work appear.",
    whyItMatters: "May require approval for freelance or advisory roles.",
    question: "Which paid or unpaid activities require prior written consent, what is the decision timeline, and are advisory board or teaching roles treated differently?",
  },
  {
    id: "penalty-clause",
    category: "restrictive_clauses",
    subcategory: "Penalty / damages clause",
    re: /\b(boetebeding|penalty\s+clause|liquidated\s+damages|forfeit|€\s*\d+.*per\s+(day|dag)|per\s+overtreding|contractuele\s+boete)\b/i,
    riskLabel: "review_before_signing",
    explain: "Penalty, forfeit, or liquidated-damages style wording may be present.",
    whyItMatters: "Financial exposure on breach should be understood before signing.",
    question: "Which specific breaches trigger penalties, are caps or mutual obligations included, and can penalties be challenged if disproportionate?",
  },
  {
    id: "working-hours",
    category: "working_time",
    subcategory: "Working hours / FTE",
    re: /\b(uren\s+per\s+week|hours\s+per\s+week|full[\s-]?time|part[\s-]?time|\d{1,3}\s*%\s*fte|arbeidsduur|work\s+schedule|parttime|deeltijd|normale\s+arbeidsduur)\b/i,
    riskLabel: "worth_confirming",
    explain: "Working time, FTE, or schedule language is present.",
    whyItMatters: "Clarifies expected availability and part-time vs full-time benefits.",
    question: "What are contracted weekly hours, core hours, and rules for changing schedule or FTE percentage?",
  },
  {
    id: "remote-hybrid",
    category: "working_time",
    subcategory: "Remote / hybrid / location",
    re: /\b(remote\s+work|hybrid|hybride\s+werken|thuiswerken|thuiswerkregeling|werk\s+op\s+afstand|werkplek|work\s+from\s+home|telewerk|telewerken|location\s+flexibility|kantoor\s+aanwezigheid|standplaats|plaats\s+van\s+tewerkstelling|werk(?:locatie|adres)|flexplek)\b/i,
    riskLabel: "worth_confirming",
    explain: "Remote, hybrid, workplace, or standplaats terms appear.",
    whyItMatters: "Immigration, tax residency, and 30% ruling context can depend on work location rules.",
    question: "What is the contractual standplaats, minimum office days, and policy on working briefly from another country?",
  },
  {
    id: "travel",
    category: "working_time",
    subcategory: "Travel obligation",
    re: /\b(business\s+travel|reisverplichting|travel\s+expectation|gereedheid\s+tot\s+reis|up\s+to\s+\d+\s*%\s+travel|dienstreizen)\b/i,
    riskLabel: "worth_confirming",
    explain: "Travel expectations are mentioned.",
    whyItMatters: "Affects lifestyle, compensation for travel time, and visa practicalities.",
    question: "What percentage of time is travel, how is travel time compensated versus working time, and which expenses are reimbursed?",
  },
  {
    id: "sick-reporting",
    category: "sick_leave_absence",
    subcategory: "Sickness reporting",
    re: /\b(ziekmelding|ziekmelden|report\s+sick|verzuim|arbo|company\s+doctor|bedrijfsarts|zwangerschaps|pregnancy\s+leave|ziekteverzuim)\b/i,
    riskLabel: "worth_confirming",
    explain: "Sickness reporting, company doctor, or absence process is referenced.",
    whyItMatters: "Dutch reintegration and gatekeeper rules are procedural; contract language should align.",
    question: "What is the first-day reporting process, when is the bedrijfsarts involved, and where is continued salary during illness defined (contract vs CAO)?",
  },
  {
    id: "annual-leave",
    category: "vacation_leave",
    subcategory: "Annual leave",
    re: /\b(vakantiedagen|annual\s+leave|vacation\s+days|verlofdagen|verlof\s+dagen|statutory\s+leave|wettelijke\s+vakantie|bovenwettelijk|vakantie-?uren)\b/i,
    riskLabel: "worth_confirming",
    explain: "Annual leave or vacation days are mentioned.",
    whyItMatters: "Statutory vs extra days and carry-over rules affect planning.",
    question: "How many statutory versus bovenwettelijke days apply, what is the carry-over limit, and when must days be taken by?",
  },
  {
    id: "visa-sponsor",
    category: "expat_immigration",
    subcategory: "Visa / sponsorship",
    re: /\b(highly\s+skilled\s+migrant|kennismigrant|hsm|erkenning\s+als\s+sponsor|recognised\s+sponsor|sponsorship|IND|work\s+permit|tewerkstellingsvergunning|TWV|tewerkstelling|residence\s+permit|verblijfsvergunning|werkvergunning)\b/i,
    riskLabel: "worth_confirming",
    explain: "Visa, permit, or recognised sponsor wording appears.",
    whyItMatters: "Termination and role changes can affect legal stay; obligations should be explicit.",
    question: "If my permit depends on this employer, what happens if the role title, salary, or hours change — and what notice will I get if sponsorship ends?",
  },
  {
    id: "relocation-repay",
    category: "expat_immigration",
    subcategory: "Relocation repayment",
    re: /\b(relocation|relocation\s+(allowance|costs)|verhuizing|verhuiskosten|verhuisvergoeding|vergoeding\s+verhuizing).{0,180}?\b(repay|repaid|repayment|clawback|terugvordering|terugbetaal|terugbetaling|recovery\s+of)|\b(moving\s+expenses).{0,100}?\b(repay|repaid)\b|terugbetalingsverplichting|kosten\s+verhuizing.{0,50}terug|relocation\s+costs.{0,80}?\b(refund|repay)\b/i,
    riskLabel: "potentially_restrictive",
    explain: "Relocation cost repayment or clawback may be required if you leave early.",
    whyItMatters: "Check proration, trigger events, and which costs count.",
    question: "Is relocation repayment prorated by months worked, which invoices count (tax, shipping, temp housing), and does voluntary resignation differ from redundancy?",
  },
  {
    id: "signing-bonus-repay",
    category: "expat_immigration",
    subcategory: "Signing / training repayment",
    re: /\b(sign[\s-]?on\s+bonus.{0,60}repay|repay.{0,40}sign[\s-]?on|training\s+costs.{0,40}repay|studiekosten|opleidingskosten.{0,40}terug|handtekeningbonus.{0,40}terug)\b/i,
    riskLabel: "potentially_restrictive",
    explain: "Repayment of signing bonus, training, or similar benefits may apply.",
    whyItMatters: "Early-leave exposure can be material.",
    question: "What is the repayment schedule for signing bonus or training costs, is it pro-rated, and are gross-up or tax gross-down amounts clarified?",
  },
  {
    id: "thirty-percent",
    category: "expat_immigration",
    subcategory: "30% ruling mention",
    re: /\b(30\s*%|30%-?regeling|30\s*%\s*ruling|thirty\s+percent\s+ruling|belastingvoordeel\s+expat|expatfaciliteit|faciliteit\s+voor\s+inkomende\s+werknemers|faciliteit\s+inkomende\s+werknemer)\b/i,
    riskLabel: "worth_confirming",
    explain: "The 30% ruling is mentioned in the document.",
    whyItMatters: "Mention in the contract does not guarantee eligibility or employer processing commitment.",
    question: "Is 30% ruling application a firm employer obligation with timelines, or discretionary / best-efforts — and who pays advisor fees if the application fails?",
  },
  {
    id: "thirty-percent-discretionary",
    category: "expat_immigration",
    subcategory: "30% ruling — discretionary wording",
    re: /\b(30\s*%|30%-?regeling).{0,120}?\b(naar\s+goeddunken|geen\s+garantie|no\s+guarantee|not\s+guaranteed|discretion|best\s+efforts|in\s+het\s+belang|afhankelijk\s+van|subject\s+to\s+approval|indien\s+toegekend)\b|\b(geen\s+recht\s+op\s+de\s+30|no\s+entitlement\s+to\s+the\s+30)\b/i,
    riskLabel: "worth_confirming",
    explain: "Language suggests 30% ruling support may be discretionary or not guaranteed.",
    whyItMatters: "Payroll tax treatment may differ from what you assumed when negotiating salary.",
    question: "If the 30% ruling is denied or ends early, how is gross salary adjusted — and is there a worked example in the offer?",
  },
  {
    id: "tax-equalization",
    category: "expat_immigration",
    subcategory: "Tax support / equalization",
    re: /\b(tax\s+equali[sz]ation|hypothetical\s+tax|tax\s+protection|employer\s+tax\s+support|belastingverhaal|cost\s+of\s+living\s+allowance|expat\s+allowance)\b/i,
    riskLabel: "worth_confirming",
    explain: "Tax equalization, protection, or expat allowance language may appear.",
    whyItMatters: "Scope and clawback of tax support packages vary widely.",
    question: "What is in scope for tax equalization or allowance, for how long, and what happens on repatriation or localisation?",
  },
];
