import { type ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Banknote, BriefcaseBusiness, Building2, CheckCircle2, ClipboardCheck, FileText, Globe2, Home, Landmark, Laptop, ReceiptText, Scale, ShieldCheck, WalletCards } from "lucide-react";
import { BreadcrumbJsonLd } from "@/components/content/breadcrumb-jsonld";
import { Container } from "@/components/ui/container";
import { cn } from "@/lib/cn";
import { activeBrightnessPress, transitionInteractive } from "@/lib/ui/interaction";
import { siteGuideColumnPadYClass, siteHeroFramedShellClass, siteHeroGlowPrimaryClass, siteHeroGlowSecondaryClass, siteHeroTopAccentClass, sitePageCanvasClass } from "@/lib/ui/site-shell-identity";
import { movingNlCardMicroLiftClass, movingNlSectionH2Class, movingNlSectionH2OnDarkClass, movingNlSignatureGradientClass } from "@/lib/ui/moving-nl-pillar-identity";
import { citiesFunnelHeroFigureClassName, CITIES_FUNNEL_INFO_CHIP, CITIES_FUNNEL_SECTION_SCROLL_MARGIN, CITIES_FUNNEL_SOFT_COPILOT_SURFACE } from "@/src/components/cities/shared/citiesFunnelPageUi";
import { doubleTaxationNetherlandsPage as page, type DoubleTaxationNetherlandsLink } from "./doubleTaxationNetherlandsPageModel";

const sectionClass = cn(CITIES_FUNNEL_SECTION_SCROLL_MARGIN, CITIES_FUNNEL_SOFT_COPILOT_SURFACE, "relative isolate overflow-hidden p-6 shadow-card ring-1 ring-slate-900/[0.04] before:pointer-events-none before:absolute before:inset-x-0 before:top-0 before:h-1 before:bg-gradient-to-r before:from-cyan-400/70 before:via-brand/80 before:to-emerald-300/70 after:pointer-events-none after:absolute after:-right-28 after:-top-28 after:h-56 after:w-56 after:rounded-full after:bg-cyan-200/15 after:blur-3xl sm:p-8 lg:p-10");
const sectionStackClass = "mt-8 space-y-6 sm:space-y-8 md:space-y-9";
const mutedCardClass = cn(CITIES_FUNNEL_SOFT_COPILOT_SURFACE, "relative overflow-hidden bg-white/90 p-5 shadow-sm ring-1 ring-slate-900/[0.04]", movingNlCardMicroLiftClass);
const cardIcons = [Globe2, Landmark, Home, Laptop, ReceiptText, BriefcaseBusiness, Banknote, Scale, FileText, WalletCards, Building2, ClipboardCheck, ShieldCheck] as const;
const snapshotIcons = [Globe2, ShieldCheck, Home, ReceiptText, Laptop, BriefcaseBusiness] as const;
const primaryCtaClass = cn("inline-flex min-h-[44px] items-center justify-center gap-2 rounded-xl border border-brand-strong/25 bg-brand px-5 py-2.5 text-sm font-semibold text-white shadow-card hover:bg-brand-strong focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2 focus-visible:ring-offset-canvas", transitionInteractive, activeBrightnessPress);
const secondaryCtaClass = cn("inline-flex min-h-[44px] items-center justify-center gap-2 rounded-xl border border-border bg-surface-raised px-5 py-2.5 text-sm font-semibold text-foreground shadow-card hover:border-border-strong hover:bg-surface-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2 focus-visible:ring-offset-canvas", transitionInteractive, activeBrightnessPress);

function SectionIntro({ eyebrow, title, children, tone = "default", fullWidth = false }: { eyebrow?: string; title: string; children?: ReactNode; tone?: "default" | "onDark"; fullWidth?: boolean }) {
  const onDark = tone === "onDark";
  return <div className={cn(fullWidth ? "w-full max-w-none" : "max-w-3xl")}>{eyebrow ? <p className={cn("text-xs font-bold uppercase tracking-[0.14em]", onDark ? "text-cyan-200" : "text-brand-strong")}>{eyebrow}</p> : null}<h2 className={cn(onDark ? movingNlSectionH2OnDarkClass : movingNlSectionH2Class, eyebrow ? "mt-2" : undefined)}>{title}</h2>{children ? <div className={cn("mt-3 w-full space-y-3 text-base leading-relaxed", fullWidth && "max-w-none lg:columns-2 lg:gap-x-10 [&>p]:break-inside-avoid", onDark ? "text-slate-300" : "text-foreground-muted")}>{children}</div> : null}</div>;
}

function HeroImage() {
  return <figure className={citiesFunnelHeroFigureClassName()}><div className={cn("absolute inset-x-0 top-0 z-10 h-1.5", movingNlSignatureGradientClass)} aria-hidden /><Image src={page.hero.image.src} alt={page.hero.image.alt} width={1600} height={900} priority sizes="(min-width: 1024px) 42vw, 100vw" className="h-full w-full object-cover" /><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-slate-950/24 via-transparent to-white/10" aria-hidden /><div className="pointer-events-none absolute inset-0 ring-1 ring-inset ring-white/35" aria-hidden /></figure>;
}

function HeroSignalStrip() {
  return (
    <div className="relative mt-5 grid gap-3 overflow-hidden rounded-[1.75rem] border border-slate-200/80 bg-white/82 p-3 shadow-card ring-1 ring-slate-900/[0.03] backdrop-blur-xl sm:grid-cols-2 lg:grid-cols-4">
      <div className={cn("absolute inset-x-0 top-0 h-1", movingNlSignatureGradientClass)} aria-hidden />
      {page.snapshotCards.slice(0, 4).map((card, index) => {
        const Icon = snapshotIcons[index % snapshotIcons.length];
        return (
          <div key={card.label} className="relative rounded-2xl border border-slate-200/70 bg-gradient-to-br from-white via-white to-copilot-bg-soft/70 p-4 shadow-sm">
            <div className="flex items-start gap-3">
              <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong shadow-sm ring-1 ring-copilot-primary/10">
                <Icon className="h-5 w-5" aria-hidden />
              </span>
              <span>
                <span className="block text-xs font-bold uppercase tracking-[0.14em] text-foreground-muted">{card.label}</span>
                <span className="mt-1 block text-sm font-bold leading-snug text-foreground">{card.value}</span>
              </span>
            </div>
          </div>
        );
      })}
    </div>
  );
}

function VisualFigure({ visual }: { visual: (typeof page.visuals)[keyof typeof page.visuals] }) {
  return <figure className={cn("relative isolate overflow-hidden rounded-[2rem] border border-slate-200/90 bg-white/95 shadow-expatos-xl ring-1 ring-slate-900/[0.05]", movingNlCardMicroLiftClass)}><div className={cn("h-1.5", movingNlSignatureGradientClass)} aria-hidden /><div className="pointer-events-none absolute -right-20 -top-20 h-44 w-44 rounded-full bg-cyan-200/25 blur-3xl" aria-hidden /><div className="relative aspect-[4/3] bg-gradient-to-br from-slate-50 via-white to-copilot-bg-soft p-2 sm:p-3"><Image src={visual.src} alt={visual.alt} fill sizes="(min-width: 1024px) 900px, 100vw" className="object-contain p-2 drop-shadow-sm sm:p-3" /></div><figcaption className="border-t border-slate-200/80 bg-slate-50/90 px-4 py-3 text-sm leading-relaxed text-foreground-muted sm:px-5">{visual.caption}</figcaption></figure>;
}

function StatCard({ label, value, iconIndex }: { label: string; value: string; iconIndex: number }) {
  const Icon = snapshotIcons[iconIndex % snapshotIcons.length];
  return <article className={cn(mutedCardClass, "min-h-full")}><div className={cn("absolute inset-x-0 top-0 h-1.5 rounded-t-2xl", movingNlSignatureGradientClass)} aria-hidden /><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong shadow-sm ring-1 ring-copilot-primary/10"><Icon className="h-5 w-5" aria-hidden /></span><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-foreground-muted">{label}</p><p className="mt-1 text-base font-bold leading-snug text-foreground">{value}</p></div></div></article>;
}

function FeatureCard({ title, body, iconIndex = 0 }: { title: string; body: string; iconIndex?: number }) {
  const Icon = cardIcons[iconIndex % cardIcons.length];
  return <article className={cn(mutedCardClass, "min-h-full")}><div className={cn("absolute inset-x-0 top-0 h-1 rounded-t-2xl", movingNlSignatureGradientClass)} aria-hidden /><div className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong shadow-sm ring-1 ring-copilot-primary/10"><Icon className="h-5 w-5" aria-hidden /></span><div><h3 className="text-base font-bold tracking-tight text-foreground">{title}</h3><p className="mt-2 text-sm leading-relaxed text-foreground-muted">{body}</p></div></div></article>;
}

function LinkCard({ item, iconIndex = 0, tone = "default" }: { item: DoubleTaxationNetherlandsLink; iconIndex?: number; tone?: "default" | "onDark" }) {
  const Icon = cardIcons[iconIndex % cardIcons.length];
  const isLive = item.status !== "comingSoon";
  const onDark = tone === "onDark";
  const shell = onDark ? "relative overflow-hidden rounded-2xl border border-white/10 bg-white/10 p-5 shadow-sm ring-1 ring-white/10" : cn(CITIES_FUNNEL_SOFT_COPILOT_SURFACE, "relative overflow-hidden p-5", movingNlCardMicroLiftClass);
  const body = <><div className={cn("absolute inset-x-0 top-0 h-1.5 rounded-t-2xl", isLive ? movingNlSignatureGradientClass : onDark ? "bg-white/20" : "bg-slate-200")} aria-hidden /><div className="flex gap-3"><span className={cn("flex h-10 w-10 shrink-0 items-center justify-center rounded-xl shadow-sm ring-1", onDark ? "bg-white/10 text-cyan-100 ring-white/15" : isLive ? "bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong ring-copilot-primary/10" : "bg-slate-100 text-slate-500 ring-slate-200")}><Icon className="h-5 w-5" aria-hidden /></span><span className="min-w-0"><span className={cn("text-sm font-bold", onDark ? "text-white" : "text-foreground")}>{item.label}</span>{!isLive ? <span className={cn("ml-2 rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-[0.1em]", onDark ? "bg-white/10 text-slate-300 ring-1 ring-white/10" : "bg-slate-100 text-slate-500")}>Coming soon</span> : null}{item.description ? <span className={cn("mt-2 block text-sm leading-relaxed", onDark ? "text-slate-300" : "text-foreground-muted")}>{item.description}</span> : null}</span></div>{isLive ? <span className={cn("mt-4 inline-flex items-center gap-1 text-xs font-semibold", onDark ? "text-cyan-200" : "text-link group-hover:text-link-hover")}>Open <ArrowRight className="h-3.5 w-3.5" aria-hidden /></span> : null}</>;
  if (!isLive) return <article className={cn(shell, "opacity-90")}>{body}</article>;
  return <Link href={item.href} className={cn(shell, "group block focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2", onDark ? "focus-visible:ring-offset-slate-950" : "focus-visible:ring-offset-canvas", !onDark && movingNlCardMicroLiftClass, transitionInteractive, activeBrightnessPress)}>{body}</Link>;
}

function BulletPanel({ title, items }: { title: string; items: readonly string[] }) {
  return <aside className={cn("relative overflow-hidden rounded-3xl border border-slate-200/90 bg-white/95 p-5 shadow-sm ring-1 ring-slate-900/[0.04]", movingNlCardMicroLiftClass)}><div className={cn("absolute inset-x-0 top-0 h-1 rounded-t-3xl", movingNlSignatureGradientClass)} aria-hidden /><h3 className="text-base font-bold tracking-tight text-foreground">{title}</h3><ul className="mt-4 grid gap-3">{items.map((item) => <li key={item} className="flex gap-3 text-sm leading-relaxed text-foreground-muted"><span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-copilot-bg-soft text-brand-strong ring-1 ring-copilot-primary/10"><CheckCircle2 className="h-3.5 w-3.5" aria-hidden /></span><span>{item}</span></li>)}</ul></aside>;
}

function ExampleTable({ title, columns, rows }: { title: string; columns: readonly string[]; rows: readonly Record<string, string>[] }) {
  return <div className={cn("relative overflow-hidden rounded-3xl border border-slate-200/90 bg-white/95 shadow-sm ring-1 ring-slate-900/[0.04]", movingNlCardMicroLiftClass)}><div className={cn("absolute inset-x-0 top-0 h-1", movingNlSignatureGradientClass)} aria-hidden /><div className="border-b border-slate-200/80 px-5 py-4"><h3 className="text-base font-bold tracking-tight text-foreground">{title}</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-slate-200/80 bg-slate-50/80">{columns.map((column) => <th key={column} scope="col" className="px-4 py-3 font-bold text-foreground">{column}</th>)}</tr></thead><tbody>{rows.map((row, rowIndex) => <tr key={`${title}-${rowIndex}`} className="border-b border-slate-100 last:border-0">{columns.map((column) => <td key={column} className="px-4 py-3 leading-relaxed text-foreground-muted">{row[column]}</td>)}</tr>)}</tbody></table></div></div>;
}

function SourcesSection() {
  return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{page.officialSources.map((source) => <a key={source.href} href={source.href} className={cn("group relative block overflow-hidden rounded-2xl border border-slate-200/90 bg-white/95 p-5 shadow-sm ring-1 ring-slate-900/[0.04] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2 focus-visible:ring-offset-canvas", movingNlCardMicroLiftClass, transitionInteractive, activeBrightnessPress)} target="_blank" rel="noreferrer"><div className={cn("absolute inset-x-0 top-0 h-1 rounded-t-2xl", movingNlSignatureGradientClass)} aria-hidden /><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong shadow-sm ring-1 ring-copilot-primary/10"><ShieldCheck className="h-5 w-5" aria-hidden /></span><span><span className="text-sm font-bold text-foreground">{source.label}</span><span className="mt-2 block text-sm leading-relaxed text-foreground-muted">{source.description}</span><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-link group-hover:text-link-hover">Open official source <ArrowRight className="h-3.5 w-3.5" aria-hidden /></span></span></div></a>)}</div>;
}

const crumbs = [{ name: "Home", item: "/" }, { name: "Netherlands", item: "/netherlands/" }, { name: "Taxes", item: page.relatedGuides[0].href }, { name: page.hero.pageTitle, item: page.path }];

export function DoubleTaxationNetherlandsView() {
  return (
    <>
      <BreadcrumbJsonLd crumbs={crumbs} />
      <main className={sitePageCanvasClass}>
        <Container className={cn("w-full max-w-screen-2xl", siteGuideColumnPadYClass)}>
          <section className={cn(siteHeroFramedShellClass, "overflow-hidden p-6 shadow-expatos-xl sm:p-8 lg:p-12")}>
            <div className={siteHeroTopAccentClass} aria-hidden /><div className={siteHeroGlowPrimaryClass} aria-hidden /><div className={siteHeroGlowSecondaryClass} aria-hidden />
            <div className="relative grid gap-8 lg:grid-cols-[minmax(0,1fr)_0.78fr] lg:items-center">
              <div><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-strong">{page.hero.eyebrow}</p><h1 className="mt-3 max-w-4xl text-4xl font-bold tracking-tight text-foreground sm:text-5xl lg:text-6xl">{page.hero.pageTitle}</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-foreground-muted sm:text-xl">{page.hero.subtitle}</p><div className="mt-6 flex flex-wrap gap-2">{page.hero.chips.map((chip) => <span key={chip} className={cn(CITIES_FUNNEL_INFO_CHIP, "shadow-sm ring-1 ring-slate-900/[0.03]")}>{chip}</span>)}</div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href={page.hero.primaryCta.href} className={primaryCtaClass}>{page.hero.primaryCta.label}<ArrowRight className="h-4 w-4" aria-hidden /></Link><Link href={page.hero.secondaryCta.href} className={secondaryCtaClass}>{page.hero.secondaryCta.label}</Link></div><p className="mt-5 max-w-3xl rounded-2xl border border-slate-200/80 bg-white/70 px-4 py-3 text-sm leading-relaxed text-foreground-muted shadow-sm ring-1 ring-slate-900/[0.03]">Educational orientation only. This page is not tax advice, legal advice or cross-border tax planning advice.</p></div>
              <HeroImage />
            </div>
          </section>
          <HeroSignalStrip />

          <nav className="sticky top-3 z-20 mt-6 flex gap-2 overflow-x-auto rounded-2xl border border-slate-200/80 bg-white/90 p-2 shadow-card ring-1 ring-slate-900/[0.04] backdrop-blur-xl" aria-label="Double taxation guide sections">{page.sectionNav.map((item) => <a key={item.href} href={item.href} className={cn("shrink-0 rounded-xl px-3 py-2 text-sm font-semibold text-foreground-muted hover:bg-copilot-bg-soft hover:text-brand-strong focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30", transitionInteractive, activeBrightnessPress)}>{item.label}</a>)}</nav>

          <div className={sectionStackClass}>
            <section id="intro" className={sectionClass}><SectionIntro eyebrow="Core concept" title="What Is Double Taxation?" fullWidth>{page.introPoints.map((point) => <p key={point}>{point}</p>)}</SectionIntro></section>
            <section id="snapshot" className={sectionClass}><SectionIntro eyebrow="At a glance" title="Double Taxation at a Glance" /><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{page.snapshotCards.map((card, index) => <StatCard key={card.label} label={card.label} value={card.value} iconIndex={index} />)}</div><div className="mt-6"><BulletPanel title="How to use this snapshot" items={page.snapshotUseTips} /></div></section>
            <section id="treaties" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Treaty basics" title="How Tax Treaties Work"><p>Countries may create tax treaties to avoid double taxation, clarify taxing rights and reduce uncertainty. Treaties differ by country and income category.</p></SectionIntro><VisualFigure visual={page.visuals.treaty} /></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><BulletPanel title="Treaty principles" items={page.treatyPrinciples} /><ExampleTable title="Conceptual treaty examples" columns={["Situation", "Possible issue", "Treaty concept", "What to verify"]} rows={page.treatyExamples.map((row) => ({ Situation: row.situation, "Possible issue": row.possibleIssue, "Treaty concept": row.treatyConcept, "What to verify": row.whatToVerify }))} /></div><div className="mt-6"><ExampleTable title="Illustrative treaty-relief examples" columns={["Example", "Amount", "Possible relief question", "What to bring"]} rows={page.treatyReliefExamples.map((row) => ({ Example: row.example, Amount: row.amount, "Possible relief question": row.possibleReliefQuestion, "What to bring": row.whatToBring }))} /></div></section>
            <section id="residency" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Residency" title="Understanding Dutch Tax Residency"><p>Tax residency may depend on where you live, work, keep family ties and center your economic life. Avoid oversimplifying residency to nationality or a single document.</p></SectionIntro><VisualFigure visual={page.visuals.residency} /></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><BulletPanel title="Residency factors to map" items={page.residencyFactors} /><ExampleTable title="Residency scenario examples" columns={["Profile", "Fact pattern", "Risk", "Next step"]} rows={page.residencyScenarios.map((row) => ({ Profile: row.profile, "Fact pattern": row.factPattern, Risk: row.risk, "Next step": row.nextStep }))} /></div><div className="mt-6"><ExampleTable title="Tax-year timing examples" columns={["Timeline", "NL days", "Common question", "Useful records"]} rows={page.residencyTimelineExamples.map((row) => ({ Timeline: row.timeline, "NL days": row.nlDays, "Common question": row.commonQuestion, "Useful records": row.usefulRecords }))} /></div></section>
            <section id="scenarios" className={sectionClass}><SectionIntro eyebrow="Common scenarios" title="Common Situations Expats Face" /><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.scenarioCards.map((card, index) => <FeatureCard key={card.title} title={card.title} body={card.body} iconIndex={index} />)}</div><div className="mt-6"><BulletPanel title="Turn scenarios into records" items={page.scenarioUseTips} /></div></section>
            <section id="foreign-income" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Foreign income" title="Foreign Income and Dutch Taxes"><p>Expats may have salary, rental, dividend, freelance, pension or investment income abroad. Foreign income may still need reporting even where treaties apply.</p></SectionIntro><VisualFigure visual={page.visuals.foreignIncome} /></div><div className="mt-6"><ExampleTable title="Foreign income examples" columns={["Income type", "Common concern", "Practical check"]} rows={page.foreignIncomeExamples.map((row) => ({ "Income type": row.incomeType, "Common concern": row.commonConcern, "Practical check": row.practicalCheck }))} /></div><div className="mt-6"><ExampleTable title="Foreign income scenario figures" columns={["Profile", "Example amount", "What can get complex", "Useful next step"]} rows={page.foreignIncomeScenarioExamples.map((row) => ({ Profile: row.profile, "Example amount": row.exampleAmount, "What can get complex": row.whatCanGetComplex, "Useful next step": row.usefulNextStep }))} /></div><div className="mt-6"><BulletPanel title="Useful reporting preparation" items={page.foreignIncomeUseTips} /></div></section>
            <section id="remote-work" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Remote work" title="Remote Work and Cross-Border Tax Complexity"><p>Remote work has increased international tax complexity. Living in the Netherlands while working for a foreign employer can raise tax, payroll and social-security questions.</p></SectionIntro><VisualFigure visual={page.visuals.remoteWork} /></div><div className="mt-6"><ExampleTable title="Remote work scenario examples" columns={["Pattern", "Complexity", "Practical move"]} rows={page.remoteWorkScenarios.map((row) => ({ Pattern: row.pattern, Complexity: row.complexity, "Practical move": row.practicalMove }))} /></div><div className="mt-6"><ExampleTable title="Workday split examples" columns={["Pattern", "Workday split", "Likely question", "Records to keep"]} rows={page.remoteWorkdayExamples.map((row) => ({ Pattern: row.pattern, "Workday split": row.workdaySplit, "Likely question": row.likelyQuestion, "Records to keep": row.recordsToKeep }))} /></div><div className="mt-6"><BulletPanel title="Useful remote-work records" items={page.remoteWorkUseTips} /></div></section>
            <section id="ruling" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="30% ruling" title="Double Taxation and the 30% Ruling"><p>The 30% ruling may affect taxable income and expat tax structure, but it does not automatically eliminate foreign-income reporting or treaty questions.</p></SectionIntro><VisualFigure visual={page.visuals.ruling} /></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><BulletPanel title="How to frame it" items={page.rulingPoints} /><LinkCard item={page.relatedGuides[2]} iconIndex={2} /></div></section>
            <section id="countries" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Treaty countries" title="Netherlands Tax Treaties by Country"><p>Each treaty differs. Use region cards as orientation only, then verify the current treaty text and get advice before applying it.</p></SectionIntro><VisualFigure visual={page.visuals.treatyCountries} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{page.countryTreatyCards.map((card, index) => <FeatureCard key={card.region} title={card.region} body={`${card.examples}. ${card.note}`} iconIndex={index} />)}</div><div className="mt-6"><ExampleTable title="Country-context examples" columns={["Country context", "Example concern", "Typical documents", "Advice signal"]} rows={page.countryComparisonExamples.map((row) => ({ "Country context": row.countryContext, "Example concern": row.exampleConcern, "Typical documents": row.typicalDocuments, "Advice signal": row.adviceSignal }))} /></div><div className="mt-6"><BulletPanel title="Use country groups carefully" items={page.countryTreatyUseTips} /></div></section>
            <section id="freelancers" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Freelancers" title="Freelancers, Contractors and Business Owners"><p>International freelancers often face multi-country tax, invoicing, VAT and residency questions. Professional guidance is commonly recommended.</p></SectionIntro><VisualFigure visual={page.visuals.freelancers} /></div><div className="mt-6"><ExampleTable title="Freelancer and business examples" columns={["Profile", "Example revenue", "Issue to check", "Useful record"]} rows={page.freelancerScenarioExamples.map((row) => ({ Profile: row.profile, "Example revenue": row.exampleRevenue, "Issue to check": row.issueToCheck, "Useful record": row.usefulRecord }))} /></div><div className="mt-6"><BulletPanel title="Freelancer considerations" items={page.freelancerPoints} /></div></section>
            <section id="assets" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Foreign assets" title="Foreign Assets and Reporting Requirements"><p>Foreign accounts, investments, pensions, real estate and crypto assets may need reporting analysis. Reporting does not always mean the same thing as being taxed twice.</p></SectionIntro><VisualFigure visual={page.visuals.foreignAssetsAdvice} /></div><div className="mt-6"><ExampleTable title="Foreign asset examples" columns={["Asset type", "Example figure", "Why it matters", "Record to keep"]} rows={page.foreignAssetExamples.map((row) => ({ "Asset type": row.assetType, "Example figure": row.exampleFigure, "Why it matters": row.whyItMatters, "Record to keep": row.recordToKeep }))} /></div><div className="mt-6"><BulletPanel title="Records to keep organized" items={page.assetReportingPoints} /></div></section>
            <section id="mistakes" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Avoidable mistakes" title="Common Double Taxation Mistakes" /><VisualFigure visual={page.visuals.mistakes} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.mistakeCards.map((card, index) => <FeatureCard key={card.title} title={card.title} body={card.body} iconIndex={index} />)}</div><div className="mt-6"><BulletPanel title="Use mistakes as a pre-filing checklist" items={page.mistakeUseTips} /></div></section>
            <section id="advice" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Professional advice" title="When Professional Tax Advice Is Worth Considering"><p>International taxation can become complex quickly. Advice is especially useful when facts cross countries, income types or filing systems.</p></SectionIntro><VisualFigure visual={page.visuals.foreignAssetsAdvice} /></div><div className="mt-6"><ExampleTable title="Advisor brief examples" columns={["Situation", "Numbers to bring", "Documents to bring"]} rows={page.advisorBriefExamples.map((row) => ({ Situation: row.situation, "Numbers to bring": row.numbersToBring, "Documents to bring": row.documentsToBring }))} /></div><div className="mt-6"><BulletPanel title="Advice triggers" items={page.adviceTriggers} /></div></section>
            <section id="questions" className={sectionClass}><SectionIntro eyebrow="Common questions" title="Questions Expats Often Ask" /><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.expatQuestions.map((item, index) => <FeatureCard key={item.q} title={item.q} body={item.a} iconIndex={index} />)}</div><div className="mt-6"><BulletPanel title="Turn questions into next steps" items={page.questionUseTips} /></div></section>
            <section id="related-guides" className={sectionClass}><SectionIntro eyebrow="Internal planning hub" title="Related Expat Tax Guides" /><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.relatedGuides.map((link, index) => <LinkCard key={link.href} item={link} iconIndex={index} />)}</div><div className="mt-6"><BulletPanel title="Recommended reading order" items={page.relatedGuideUseTips} /></div></section>
            <section id="services" className={sectionClass}><SectionIntro eyebrow="Professional help" title="Professional Services That May Help"><p>The right professional depends on whether your issue is filing, payroll, residency, immigration or financial planning.</p></SectionIntro><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{page.services.map((link, index) => <LinkCard key={link.href} item={link} iconIndex={index} />)}</div><div className="mt-6"><BulletPanel title="Choose the right professional" items={page.serviceSelectionTips} /></div></section>
            <section id="faq" className={sectionClass}><SectionIntro eyebrow="FAQ" title="Frequently Asked Questions" /><div className="mt-6 grid gap-4 md:grid-cols-2">{page.faq.map((item, index) => <FeatureCard key={item.q} title={item.q} body={item.a} iconIndex={index} />)}</div><div className="mt-6"><BulletPanel title="How to use the FAQ safely" items={page.faqUseTips} /></div></section>
            <section id="sources" className={sectionClass}><SectionIntro eyebrow="Official sources" title="Official Sources"><p>{page.sourcesDisclaimer}</p></SectionIntro><div className="mt-6"><SourcesSection /></div><div className="mt-6"><BulletPanel title="Where to verify what" items={page.sourceVerificationTips} /></div></section>
            <section className={cn("relative isolate overflow-hidden rounded-[2rem] bg-slate-950 p-6 shadow-expatos-xl ring-1 ring-white/10 sm:p-8 lg:p-10")}><div className={cn("absolute inset-x-0 top-0 h-1.5", movingNlSignatureGradientClass)} aria-hidden /><div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-cyan-400/20 blur-3xl" aria-hidden /><div className="pointer-events-none absolute -bottom-28 left-1/4 h-72 w-72 rounded-full bg-emerald-300/10 blur-3xl" aria-hidden /><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(255,255,255,0.08),transparent_34%)]" aria-hidden /><SectionIntro eyebrow="Explore next" title="Continue Your Expat Tax Planning" tone="onDark"><p>Move from double-taxation concepts into expat taxes, payroll, salary and relocation timing.</p></SectionIntro><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{page.exploreNextCards.map((link, index) => <LinkCard key={link.href} item={link} iconIndex={index} tone="onDark" />)}</div></section>
          </div>
        </Container>
      </main>
    </>
  );
}
