import { Children, type ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Banknote, BriefcaseBusiness, Building2, CheckCircle2, ClipboardCheck, FileText, Globe2, Home, Landmark, Laptop, ReceiptText, Scale, ShieldCheck, WalletCards } from "lucide-react";
import { BreadcrumbJsonLd } from "@/components/content/breadcrumb-jsonld";
import { Container } from "@/components/ui/container";
import { cn } from "@/lib/cn";
import { activeBrightnessPress, transitionInteractive } from "@/lib/ui/interaction";
import { siteGuideColumnPadYClass, siteHeroFramedShellClass, siteHeroGlowPrimaryClass, siteHeroGlowSecondaryClass, siteHeroTopAccentClass, sitePageCanvasClass } from "@/lib/ui/site-shell-identity";
import { movingNlCardMicroLiftClass, movingNlSectionH2Class, movingNlSectionH2OnDarkClass, movingNlSignatureGradientClass } from "@/lib/ui/moving-nl-pillar-identity";
import { citiesFunnelHeroFigureClassName, CITIES_FUNNEL_INFO_CHIP, CITIES_FUNNEL_SECTION_SCROLL_MARGIN, CITIES_FUNNEL_SOFT_COPILOT_SURFACE } from "@/src/components/cities/shared/citiesFunnelPageUi";
import { foreignIncomeNetherlandsPage as page, type ForeignIncomeNetherlandsLink } from "./foreignIncomeNetherlandsPageModel";

const sectionClass = cn(CITIES_FUNNEL_SECTION_SCROLL_MARGIN, CITIES_FUNNEL_SOFT_COPILOT_SURFACE, "relative isolate overflow-hidden p-6 shadow-card ring-1 ring-slate-900/[0.04] before:pointer-events-none before:absolute before:inset-x-0 before:top-0 before:h-1 before:bg-gradient-to-r before:from-cyan-400/70 before:via-brand/80 before:to-emerald-300/70 after:pointer-events-none after:absolute after:-right-28 after:-top-28 after:h-56 after:w-56 after:rounded-full after:bg-cyan-200/15 after:blur-3xl sm:p-8 lg:p-10");
const sectionStackClass = "mt-8 space-y-6 sm:space-y-8 md:space-y-9";
const mutedCardClass = cn(CITIES_FUNNEL_SOFT_COPILOT_SURFACE, "relative overflow-hidden bg-white/90 p-5 shadow-sm ring-1 ring-slate-900/[0.04]", movingNlCardMicroLiftClass);
const icons = [Globe2, Landmark, Home, Laptop, ReceiptText, BriefcaseBusiness, Banknote, Scale, FileText, WalletCards, Building2, ClipboardCheck, ShieldCheck] as const;
const primaryCtaClass = cn("inline-flex min-h-[44px] items-center justify-center gap-2 rounded-xl border border-brand-strong/25 bg-brand px-5 py-2.5 text-sm font-semibold text-white shadow-card hover:bg-brand-strong focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2 focus-visible:ring-offset-canvas", transitionInteractive, activeBrightnessPress);
const secondaryCtaClass = cn("inline-flex min-h-[44px] items-center justify-center gap-2 rounded-xl border border-border bg-surface-raised px-5 py-2.5 text-sm font-semibold text-foreground shadow-card hover:border-border-strong hover:bg-surface-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2 focus-visible:ring-offset-canvas", transitionInteractive, activeBrightnessPress);

function SectionIntro({ eyebrow, title, children, tone = "default", fullWidth = false }: { eyebrow?: string; title: string; children?: ReactNode; tone?: "default" | "onDark"; fullWidth?: boolean }) {
  const onDark = tone === "onDark";
  const useColumnLayout = fullWidth && Children.count(children) > 1;
  return <div className={cn(fullWidth ? "w-full max-w-none" : "max-w-3xl")}>{eyebrow ? <p className={cn("text-xs font-bold uppercase tracking-[0.14em]", onDark ? "text-cyan-200" : "text-brand-strong")}>{eyebrow}</p> : null}<h2 className={cn(onDark ? movingNlSectionH2OnDarkClass : movingNlSectionH2Class, eyebrow ? "mt-2" : undefined)}>{title}</h2>{children ? <div className={cn("mt-3 w-full space-y-3 text-base leading-relaxed", useColumnLayout && "max-w-none lg:columns-2 lg:gap-x-10 [&>p]:break-inside-avoid", onDark ? "text-slate-300" : "text-foreground-muted")}>{children}</div> : null}</div>;
}

function VisualFigure({ visual }: { visual: (typeof page.visuals)[keyof typeof page.visuals] }) {
  return <figure className={cn("relative isolate overflow-hidden rounded-[2rem] border border-slate-200/90 bg-white/95 shadow-expatos-xl ring-1 ring-slate-900/[0.05]", movingNlCardMicroLiftClass)}><div className={cn("h-1.5", movingNlSignatureGradientClass)} aria-hidden /><div className="pointer-events-none absolute -right-20 -top-20 h-44 w-44 rounded-full bg-cyan-200/25 blur-3xl" aria-hidden /><div className="relative aspect-[3/2] bg-gradient-to-br from-slate-50 via-white to-copilot-bg-soft"><Image src={visual.src} alt={visual.alt} fill sizes="(min-width: 1024px) 900px, 100vw" className="object-contain drop-shadow-sm" /></div><figcaption className="border-t border-slate-200/80 bg-slate-50/90 px-4 py-3 text-sm leading-relaxed text-foreground-muted sm:px-5">{visual.caption}</figcaption></figure>;
}

function HeroImage() {
  return <figure className={citiesFunnelHeroFigureClassName()}><div className={cn("absolute inset-x-0 top-0 z-10 h-1.5", movingNlSignatureGradientClass)} aria-hidden /><Image src={page.hero.image.src} alt={page.hero.image.alt} width={1600} height={900} priority sizes="(min-width: 1024px) 42vw, 100vw" className="h-full w-full object-cover" /><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-slate-950/24 via-transparent to-white/10" aria-hidden /><div className="pointer-events-none absolute inset-0 ring-1 ring-inset ring-white/35" aria-hidden /></figure>;
}

function HeroSignalStrip() {
  return <div className="relative mt-5 grid gap-3 overflow-hidden rounded-[1.75rem] border border-slate-200/80 bg-white/82 p-3 shadow-card ring-1 ring-slate-900/[0.03] backdrop-blur-xl sm:grid-cols-2 lg:grid-cols-4"><div className={cn("absolute inset-x-0 top-0 h-1", movingNlSignatureGradientClass)} aria-hidden />{page.snapshotCards.slice(0, 4).map((card, index) => <StatCard key={card.label} label={card.label} value={card.value} iconIndex={index} />)}</div>;
}

function StatCard({ label, value, iconIndex }: { label: string; value: string; iconIndex: number }) {
  const Icon = icons[iconIndex % icons.length];
  return <article className={cn(mutedCardClass, "min-h-full")}><div className={cn("absolute inset-x-0 top-0 h-1.5 rounded-t-2xl", movingNlSignatureGradientClass)} aria-hidden /><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong shadow-sm ring-1 ring-copilot-primary/10"><Icon className="h-5 w-5" aria-hidden /></span><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-foreground-muted">{label}</p><p className="mt-1 text-base font-bold leading-snug text-foreground">{value}</p></div></div></article>;
}

function FeatureCard({ title, body, iconIndex = 0 }: { title: string; body: string; iconIndex?: number }) {
  const Icon = icons[iconIndex % icons.length];
  return <article className={cn(mutedCardClass, "min-h-full")}><div className={cn("absolute inset-x-0 top-0 h-1 rounded-t-2xl", movingNlSignatureGradientClass)} aria-hidden /><div className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong shadow-sm ring-1 ring-copilot-primary/10"><Icon className="h-5 w-5" aria-hidden /></span><div><h3 className="text-base font-bold tracking-tight text-foreground">{title}</h3><p className="mt-2 text-sm leading-relaxed text-foreground-muted">{body}</p></div></div></article>;
}

function LinkCard({ item, iconIndex = 0, tone = "default" }: { item: ForeignIncomeNetherlandsLink; iconIndex?: number; tone?: "default" | "onDark" }) {
  const Icon = icons[iconIndex % icons.length];
  const isLive = item.status !== "comingSoon";
  const onDark = tone === "onDark";
  const shell = onDark ? "relative overflow-hidden rounded-2xl border border-white/10 bg-white/10 p-5 shadow-sm ring-1 ring-white/10" : cn(CITIES_FUNNEL_SOFT_COPILOT_SURFACE, "relative overflow-hidden p-5", movingNlCardMicroLiftClass);
  const body = <><div className={cn("absolute inset-x-0 top-0 h-1.5 rounded-t-2xl", isLive ? movingNlSignatureGradientClass : onDark ? "bg-white/20" : "bg-slate-200")} aria-hidden /><div className="flex gap-3"><span className={cn("flex h-10 w-10 shrink-0 items-center justify-center rounded-xl shadow-sm ring-1", onDark ? "bg-white/10 text-cyan-100 ring-white/15" : isLive ? "bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong ring-copilot-primary/10" : "bg-slate-100 text-slate-500 ring-slate-200")}><Icon className="h-5 w-5" aria-hidden /></span><span className="min-w-0"><span className={cn("text-sm font-bold", onDark ? "text-white" : "text-foreground")}>{item.label}</span>{!isLive ? <span className={cn("ml-2 rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-[0.1em]", onDark ? "bg-white/10 text-slate-300 ring-1 ring-white/10" : "bg-slate-100 text-slate-500")}>Coming soon</span> : null}{item.description ? <span className={cn("mt-2 block text-sm leading-relaxed", onDark ? "text-slate-300" : "text-foreground-muted")}>{item.description}</span> : null}</span></div>{isLive ? <span className={cn("mt-4 inline-flex items-center gap-1 text-xs font-semibold", onDark ? "text-cyan-200" : "text-link group-hover:text-link-hover")}>Open <ArrowRight className="h-3.5 w-3.5" aria-hidden /></span> : null}</>;
  if (!isLive) return <article className={cn(shell, "opacity-90")}>{body}</article>;
  return <Link href={item.href} className={cn(shell, "group block focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2", onDark ? "focus-visible:ring-offset-slate-950" : "focus-visible:ring-offset-canvas", transitionInteractive, activeBrightnessPress)}>{body}</Link>;
}

function BulletPanel({ title, items }: { title: string; items: readonly string[] }) {
  return <aside className={cn("relative overflow-hidden rounded-3xl border border-slate-200/90 bg-white/95 p-5 shadow-sm ring-1 ring-slate-900/[0.04]", movingNlCardMicroLiftClass)}><div className={cn("absolute inset-x-0 top-0 h-1 rounded-t-3xl", movingNlSignatureGradientClass)} aria-hidden /><h3 className="text-base font-bold tracking-tight text-foreground">{title}</h3><ul className="mt-4 grid gap-3">{items.map((item) => <li key={item} className="flex gap-3 text-sm leading-relaxed text-foreground-muted"><span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-copilot-bg-soft text-brand-strong ring-1 ring-copilot-primary/10"><CheckCircle2 className="h-3.5 w-3.5" aria-hidden /></span><span>{item}</span></li>)}</ul></aside>;
}

function ExampleTable({ title, columns, rows }: { title: string; columns: readonly string[]; rows: readonly Record<string, string>[] }) {
  return <div className={cn("relative overflow-hidden rounded-3xl border border-slate-200/90 bg-white/95 shadow-sm ring-1 ring-slate-900/[0.04]", movingNlCardMicroLiftClass)}><div className={cn("absolute inset-x-0 top-0 h-1", movingNlSignatureGradientClass)} aria-hidden /><div className="border-b border-slate-200/80 px-5 py-4"><h3 className="text-base font-bold tracking-tight text-foreground">{title}</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-slate-200/80 bg-slate-50/80">{columns.map((column) => <th key={column} scope="col" className="px-4 py-3 font-bold text-foreground">{column}</th>)}</tr></thead><tbody>{rows.map((row, rowIndex) => <tr key={`${title}-${rowIndex}`} className="border-b border-slate-100 last:border-0">{columns.map((column) => <td key={column} className="px-4 py-3 leading-relaxed text-foreground-muted">{row[column]}</td>)}</tr>)}</tbody></table></div></div>;
}

function SourcesSection() {
  return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{page.officialSources.map((source) => <a key={source.href} href={source.href} className={cn("group relative block overflow-hidden rounded-2xl border border-slate-200/90 bg-white/95 p-5 shadow-sm ring-1 ring-slate-900/[0.04] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2 focus-visible:ring-offset-canvas", movingNlCardMicroLiftClass, transitionInteractive, activeBrightnessPress)} target="_blank" rel="noreferrer"><div className={cn("absolute inset-x-0 top-0 h-1 rounded-t-2xl", movingNlSignatureGradientClass)} aria-hidden /><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong shadow-sm ring-1 ring-copilot-primary/10"><ShieldCheck className="h-5 w-5" aria-hidden /></span><span><span className="text-sm font-bold text-foreground">{source.label}</span><span className="mt-2 block text-sm leading-relaxed text-foreground-muted">{source.description}</span><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-link group-hover:text-link-hover">Open official source <ArrowRight className="h-3.5 w-3.5" aria-hidden /></span></span></div></a>)}</div>;
}

const crumbs = [{ name: "Home", item: "/" }, { name: "Netherlands", item: "/netherlands/" }, { name: "Taxes", item: page.relatedGuides[7].href }, { name: page.hero.pageTitle, item: page.path }];

export function ForeignIncomeNetherlandsView() {
  return (
    <>
      <BreadcrumbJsonLd crumbs={crumbs} />
      <main className={sitePageCanvasClass}>
        <Container className={cn("w-full max-w-screen-2xl", siteGuideColumnPadYClass)}>
          <section className={cn(siteHeroFramedShellClass, "overflow-hidden p-6 shadow-expatos-xl sm:p-8 lg:p-12")}>
            <div className={siteHeroTopAccentClass} aria-hidden /><div className={siteHeroGlowPrimaryClass} aria-hidden /><div className={siteHeroGlowSecondaryClass} aria-hidden />
            <div className="relative grid gap-8 lg:grid-cols-[minmax(0,1fr)_0.78fr] lg:items-center">
              <div><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-strong">{page.hero.eyebrow}</p><h1 className="mt-3 max-w-4xl text-4xl font-bold tracking-tight text-foreground sm:text-5xl lg:text-6xl">{page.hero.pageTitle}</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-foreground-muted sm:text-xl">{page.hero.subtitle}</p><div className="mt-6 flex flex-wrap gap-2">{page.hero.chips.map((chip) => <span key={chip} className={cn(CITIES_FUNNEL_INFO_CHIP, "shadow-sm ring-1 ring-slate-900/[0.03]")}>{chip}</span>)}</div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href={page.hero.primaryCta.href} className={primaryCtaClass}>{page.hero.primaryCta.label}<ArrowRight className="h-4 w-4" aria-hidden /></Link><Link href={page.hero.secondaryCta.href} className={secondaryCtaClass}>{page.hero.secondaryCta.label}</Link></div><p className="mt-5 max-w-3xl rounded-2xl border border-slate-200/80 bg-white/70 px-4 py-3 text-sm leading-relaxed text-foreground-muted shadow-sm ring-1 ring-slate-900/[0.03]">Educational orientation only. This page is not tax advice, legal advice or international tax planning advice.</p></div>
              <HeroImage />
            </div>
          </section>
          <HeroSignalStrip />

          <nav className="sticky top-3 z-20 mt-6 flex gap-2 overflow-x-auto rounded-2xl border border-slate-200/80 bg-white/90 p-2 shadow-card ring-1 ring-slate-900/[0.04] backdrop-blur-xl" aria-label="Foreign income guide sections">{page.sectionNav.map((item) => <a key={item.href} href={item.href} className={cn("shrink-0 rounded-xl px-3 py-2 text-sm font-semibold text-foreground-muted hover:bg-copilot-bg-soft hover:text-brand-strong focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30", transitionInteractive, activeBrightnessPress)}>{item.label}</a>)}</nav>

          <div className={sectionStackClass}>
            <section id="intro" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Core concept" title="What Counts as Foreign Income?" fullWidth>{page.introPoints.map((point) => <p key={point}>{point}</p>)}</SectionIntro><VisualFigure visual={page.visuals.intro} /></div></section>
            <section id="snapshot" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="At a glance" title="Foreign Income at a Glance" /><VisualFigure visual={page.visuals.snapshot} /></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{page.snapshotCards.map((card, index) => <StatCard key={card.label} label={card.label} value={card.value} iconIndex={index} />)}</div><div className="mt-6"><BulletPanel title="How to use this snapshot" items={page.snapshotUseTips} /></div><div className="mt-6"><ExampleTable title="Common foreign-income scenarios" columns={["Profile", "Example", "Likely question", "Useful records"]} rows={page.scenarioExamples.map((row) => ({ Profile: row.profile, Example: row.example, "Likely question": row.likelyQuestion, "Useful records": row.usefulRecords }))} /></div></section>
            <section id="residency" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Dutch tax residency" title="Why Tax Residency Matters"><p>Dutch tax residency strongly affects reporting obligations, taxable income scope and international tax treatment. The analysis is usually factual, not a single yes-or-no shortcut.</p></SectionIntro><VisualFigure visual={page.visuals.residency} /></div><div className="mt-6"><BulletPanel title="Residency factors to map" items={page.residencyFactors} /></div></section>
            <section id="worldwide-income" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Scope" title="Worldwide Income Concepts"><p>In some situations, Dutch tax residency may involve considering worldwide income. That does not automatically mean double taxation, identical treatment for every income type or the same result in every country pair.</p></SectionIntro><VisualFigure visual={page.visuals.worldwide} /></div><div className="mt-6"><BulletPanel title="What to remember" items={page.worldwideConcepts} /></div><div className="mt-6"><ExampleTable title="Worldwide-income scenario examples" columns={["Situation", "Figures", "What it shows", "Avoid assuming"]} rows={page.worldwideScenarioExamples.map((row) => ({ Situation: row.situation, Figures: row.figures, "What it shows": row.whatItShows, "Avoid assuming": row.avoidAssuming }))} /></div></section>
            <section id="income-types" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Income categories" title="Common Foreign Income Types for Expats"><p>Expats may have foreign salary, rental income, dividends, pensions, freelance income, overseas business income, remote-work income or crypto assets. Each category deserves its own record trail.</p></SectionIntro><VisualFigure visual={page.visuals.incomeTypes} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.incomeTypeCards.map((card, index) => <FeatureCard key={card.title} title={card.title} body={card.body} iconIndex={index} />)}</div></section>
            <section id="remote-work" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Foreign employers" title="Working Remotely for Foreign Employers"><p>Common scenarios include living in the Netherlands while employed abroad, hybrid cross-border work, digital nomad setups and temporary overseas assignments.</p></SectionIntro><VisualFigure visual={page.visuals.remoteWork} /></div><div className="mt-6"><ExampleTable title="Remote work scenario examples" columns={["Pattern", "Complexity", "Practical move"]} rows={page.remoteWorkScenarios.map((row) => ({ Pattern: row.pattern, Complexity: row.complexity, "Practical move": row.practicalMove }))} /></div><div className="mt-6"><ExampleTable title="Workday split examples" columns={["Pattern", "Workday split", "Likely question", "Records"]} rows={page.remoteWorkdayExamples.map((row) => ({ Pattern: row.pattern, "Workday split": row.workdaySplit, "Likely question": row.likelyQuestion, Records: row.records }))} /></div></section>
            <section id="property" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Foreign property" title="Foreign Property and Rental Income"><p>Many expats keep rental property, investment homes or family homes abroad. Foreign property may still have Dutch reporting implications depending on circumstances.</p></SectionIntro><VisualFigure visual={page.visuals.property} /></div><div className="mt-6"><ExampleTable title="Foreign property examples" columns={["Profile", "Example figure", "What to check", "Records"]} rows={page.propertyExamples.map((row) => ({ Profile: row.profile, "Example figure": row.exampleFigure, "What to check": row.whatToCheck, Records: row.records }))} /></div></section>
            <section id="investments" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Accounts and assets" title="Foreign Investments and Bank Accounts"><p>Expats may hold overseas bank accounts, brokerage accounts, dividends, investment portfolios, pensions or crypto assets. International reporting obligations can become complex.</p></SectionIntro><VisualFigure visual={page.visuals.investments} /></div><div className="mt-6"><ExampleTable title="Investment and account examples" columns={["Asset type", "Practical concern", "Useful records"]} rows={page.investmentExamples.map((row) => ({ "Asset type": row.assetType, "Practical concern": row.practicalConcern, "Useful records": row.usefulRecords }))} /></div><div className="mt-6"><ExampleTable title="Investment examples with figures" columns={["Asset type", "Example figure", "Practical check"]} rows={page.investmentScenarioExamples.map((row) => ({ "Asset type": row.assetType, "Example figure": row.exampleFigure, "Practical check": row.practicalCheck }))} /></div></section>
            <section id="treaties" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Double taxation" title="How Double Taxation Treaties Relate to Foreign Income"><p>Tax treaties may help reduce double taxation, clarify taxing rights or coordinate international tax treatment. Each treaty differs.</p></SectionIntro><VisualFigure visual={page.visuals.treaties} /></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><BulletPanel title="Treaty concepts" items={page.treatyPoints} /><LinkCard item={page.relatedGuides[0]} iconIndex={1} /></div></section>
            <section id="ruling" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="30% ruling" title="Foreign Income and the 30% Ruling"><p>The 30% ruling may affect tax treatment, expat tax structure and partial non-resident concepts where applicable. It should not be treated as a blanket answer.</p></SectionIntro><VisualFigure visual={page.visuals.ruling} /></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><BulletPanel title="How to frame it" items={page.rulingPoints} /><LinkCard item={page.relatedGuides[2]} iconIndex={2} /></div></section>
            <section id="moving-year" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Transition years" title="Moving During the Tax Year"><p>Many expats arrive mid-year, leave mid-year or split work between countries. This can create partial-year residency issues, multiple filing considerations and foreign income reporting questions.</p></SectionIntro><VisualFigure visual={page.visuals.movingYear} /></div><div className="mt-6"><ExampleTable title="Moving-year examples" columns={["Situation", "What changes", "Useful records"]} rows={page.movingYearExamples.map((row) => ({ Situation: row.situation, "What changes": row.whatChanges, "Useful records": row.usefulRecords }))} /></div></section>
            <section id="freelancers" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Self-employed" title="Freelancers, Contractors and Entrepreneurs"><p>International freelancers often face multi-country invoicing, cross-border VAT questions, remote-work complexity and possible business-presence concerns.</p></SectionIntro><VisualFigure visual={page.visuals.freelancers} /></div><div className="mt-6"><BulletPanel title="Freelancer considerations" items={page.freelancerPoints} /></div><div className="mt-6"><ExampleTable title="Freelancer scenario figures" columns={["Profile", "Revenue", "Issue to check", "Useful record"]} rows={page.freelancerScenarioExamples.map((row) => ({ Profile: row.profile, Revenue: row.revenue, "Issue to check": row.issueToCheck, "Useful record": row.usefulRecord }))} /></div></section>
            <section id="mistakes" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Avoidable mistakes" title="Common Foreign Income Mistakes" /><VisualFigure visual={page.visuals.mistakes} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.mistakeCards.map((card, index) => <FeatureCard key={card.title} title={card.title} body={card.body} iconIndex={index} />)}</div></section>
            <section id="advice" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Professional advice" title="Situations Where Professional Advice Is Valuable"><p>International taxation can become complex quickly when several countries, income types or filing systems overlap.</p></SectionIntro><VisualFigure visual={page.visuals.advice} /></div><div className="mt-6"><BulletPanel title="Advice is especially useful when" items={page.adviceTriggers} /></div><div className="mt-6"><ExampleTable title="Advisor brief examples" columns={["Situation", "Numbers to bring", "Documents to bring"]} rows={page.advisorBriefExamples.map((row) => ({ Situation: row.situation, "Numbers to bring": row.numbersToBring, "Documents to bring": row.documentsToBring }))} /></div></section>
            <section id="questions" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Common questions" title="Questions Expats Often Ask" /><VisualFigure visual={page.visuals.questions} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.expatQuestions.map((item, index) => <FeatureCard key={item.q} title={item.q} body={item.a} iconIndex={index} />)}</div></section>
            <section id="related-tax-guides" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Internal planning hub" title="Related Expat Tax Guides" /><VisualFigure visual={page.visuals.relatedGuides} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.relatedGuides.map((link, index) => <LinkCard key={link.href} item={link} iconIndex={index} />)}</div></section>
            <section id="services" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Professional help" title="Professional Services That May Help"><p>The right professional depends on whether your issue is filing, payroll, residency, immigration or financial planning.</p></SectionIntro><VisualFigure visual={page.visuals.services} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{page.services.map((link, index) => <LinkCard key={link.href} item={link} iconIndex={index} />)}</div></section>
            <section id="faq" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="FAQ" title="Frequently Asked Questions" /><VisualFigure visual={page.visuals.faq} /></div><div className="mt-6 grid gap-4 md:grid-cols-2">{page.faq.map((item, index) => <FeatureCard key={item.q} title={item.q} body={item.a} iconIndex={index} />)}</div></section>
            <section id="sources" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Official sources" title="Official Sources"><p>{page.sourcesDisclaimer}</p></SectionIntro><VisualFigure visual={page.visuals.sources} /></div><div className="mt-6"><SourcesSection /></div></section>
            <section className={cn("relative isolate overflow-hidden rounded-[2rem] bg-slate-950 p-6 shadow-expatos-xl ring-1 ring-white/10 sm:p-8 lg:p-10")}><div className={cn("absolute inset-x-0 top-0 h-1.5", movingNlSignatureGradientClass)} aria-hidden /><div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-cyan-400/20 blur-3xl" aria-hidden /><div className="pointer-events-none absolute -bottom-28 left-1/4 h-72 w-72 rounded-full bg-emerald-300/10 blur-3xl" aria-hidden /><div className="relative space-y-6"><SectionIntro eyebrow="Explore next" title="Continue Your Expat Tax Planning" tone="onDark"><p>Move from foreign-income awareness into double taxation, expat taxes, payroll and relocation timing.</p></SectionIntro><VisualFigure visual={page.visuals.exploreNext} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{page.exploreNextCards.map((link, index) => <LinkCard key={link.href} item={link} iconIndex={index} tone="onDark" />)}</div></section>
          </div>
        </Container>
      </main>
    </>
  );
}
