export const LEAVING_NETHERLANDS_TAX_PATH = "/netherlands/taxes/leaving-netherlands-tax/" as const;
export const TAXES_HUB_PATH = "/netherlands/taxes/" as const;

export type LeavingNetherlandsTaxLink = {
  label: string;
  href: string;
  description?: string;
  status?: "live" | "comingSoon";
};

const visual = (name: string, alt: string, caption: string) => ({
  src: `/images/infographics/netherlands-leaving-tax-${name}-premium-v6.png`,
  alt,
  caption,
});

export const leavingNetherlandsTaxPage = {
  slug: "leaving-netherlands-tax",
  path: LEAVING_NETHERLANDS_TAX_PATH,
  publish: true,
  publishDate: "2026-08-05",
  seo: {
    title: "Taxes When Leaving the Netherlands | Expat Exit Tax Guide",
    description:
      "Learn what happens tax-wise when leaving the Netherlands, including tax residency, final tax returns, pensions, allowances and common expat exit considerations.",
    keywords: [
      "leaving netherlands tax",
      "leaving netherlands taxes",
      "expat leaving netherlands tax",
      "moving away from netherlands taxes",
      "dutch exit tax expat",
      "final tax return netherlands",
      "deregister netherlands taxes",
      "tax after leaving netherlands",
      "30 ruling after leaving",
      "leaving netherlands pension",
    ],
  },
  hero: {
    eyebrow: "Netherlands · Taxes · Global mobility",
    pageTitle: "Taxes When Leaving the Netherlands",
    subtitle:
      "Understand the key tax considerations expats may face when leaving the Netherlands, including tax residency, final tax returns, pensions, allowances and international tax transitions.",
    primaryCta: { label: "Understand Exit Tax Considerations", href: "#intro" },
    secondaryCta: { label: "Explore Expat Tax Guides", href: TAXES_HUB_PATH },
    chips: ["Deregistration", "Final tax return", "Tax residency", "Pensions"],
    image: {
      src: "/images/heroes/netherlands-leaving-tax-hero-v1.png",
      alt: "Premium editorial image of an expat calmly organizing departure documents in a Dutch apartment before leaving the Netherlands.",
    },
  },
  visuals: {
    intro: visual("intro", "Exit tax roadmap infographic showing timing, deregistration, payroll, ties, records and advice steps when leaving the Netherlands.", "The roadmap turns a stressful exit into a practical sequence: decide timing, update records, close payroll, map ties, build a file and ask early when facts overlap."),
    snapshot: visual("snapshot", "Snapshot infographic showing six tax considerations when leaving the Netherlands.", "Use the snapshot to separate immediate exit admin from questions that depend on residency, income, benefits and pensions."),
    deregister: visual("deregister", "Deregistration infographic showing how municipality departure records affect taxes and benefits.", "Deregistration can create the official date trail used by tax, healthcare, benefit and municipality systems."),
    residency: visual("residency", "Tax residency infographic showing facts to map after leaving the Netherlands.", "The residency map keeps the analysis factual: home, family, work, economic ties, timing and destination all matter."),
    finalReturn: visual("final-return", "Final Dutch tax return record-builder infographic for expats leaving the Netherlands.", "The record builder shows the practical files often needed for a leaving year: payroll, foreign income, allowances and property records."),
    midYear: visual("mid-year", "Timeline infographic for leaving the Netherlands during the tax year.", "The timeline shows how one calendar year can split across Dutch payroll, deregistration, new-country income and later filing questions."),
    ruling: visual("30-ruling", "Infographic about the 30 percent ruling after leaving the Netherlands.", "The triage visual shows why employment end date, approval status, transfer timing and final payslips matter."),
    foreignIncome: visual("foreign-income", "Foreign income map for expats after leaving the Netherlands.", "The income map helps identify which Dutch and non-Dutch income streams may still need records after departure."),
    pensions: visual("pensions", "Pension questions infographic for expats leaving the Netherlands.", "The pension visual separates employer pensions, AOW context, private products and record keeping without giving pension advice."),
    propertyInvestments: visual("property-investments", "Dutch property and investments infographic for expats moving abroad.", "Use the asset map to list Dutch property, rentals, investments, businesses and valuations that may keep a Netherlands connection."),
    allowances: visual("allowances", "Allowances after leaving infographic showing healthcare, rent, childcare and child benefit checks.", "The allowance matrix turns benefit names into practical update points: dates, household, income estimates and official messages."),
    healthcare: visual("healthcare", "Health insurance exit checks infographic for leaving the Netherlands.", "The healthcare visual links deregistration, policy ending, new-country coverage and benefit updates."),
    remoteWork: visual("remote-work", "Remote work and international employment infographic after leaving the Netherlands.", "The remote-work map keeps the key facts visible: employer country, workdays, treaty context, payroll and records."),
    mistakes: visual("mistakes", "Common tax mistakes infographic for expats leaving the Netherlands.", "The mistake radar highlights the assumptions that commonly cause exit-year confusion."),
    advice: visual("advice", "Professional advice infographic for complex exit-tax situations.", "The advice map helps identify when multiple countries, pensions, property, remote work or high compensation justify professional review."),
    questions: visual("questions", "Questions expats ask about taxes when leaving the Netherlands infographic.", "The question router turns broad exit worries into concrete facts to verify."),
    relatedGuides: visual("related-guides", "Related tax guides infographic for leaving the Netherlands.", "The reading path connects exit questions to double taxation, foreign income, expat taxes, the 30% ruling and arrival tax guides."),
    relocationEcosystem: visual("relocation-ecosystem", "Relocation and tax ecosystem infographic showing how the leaving tax guide connects to taxes, foreign income, pensions, healthcare, relocation and services.", "The ecosystem map helps users choose the next guide by question type: tax, foreign income, pensions, relocation admin, healthcare or professional help."),
    services: visual("services", "Professional services map for expats leaving the Netherlands.", "The service map matches the issue to the likely provider type: tax, international tax, relocation, immigration, financial or payroll."),
    faq: visual("faq", "FAQ fact-filter infographic for leaving the Netherlands tax questions.", "The FAQ filter keeps answers grounded in dates, income types, country pairs, allowances, pensions and workdays."),
    sources: visual("sources", "Official sources checklist for taxes when leaving the Netherlands.", "The source checklist points to official portals for tax, relocation, business, cross-border and pension/benefit context."),
    exploreNext: visual("explore-next", "Explore next infographic for tax and relocation guides after leaving the Netherlands.", "Use the next-step visual to choose the specialist guide that fits your remaining exit question."),
  },
  sectionNav: [
    { label: "Intro", href: "#intro" },
    { label: "Deregister", href: "#deregister" },
    { label: "Residency", href: "#residency" },
    { label: "Final return", href: "#final-return" },
    { label: "30% ruling", href: "#ruling" },
    { label: "Foreign income", href: "#foreign-income" },
    { label: "Pensions", href: "#pensions" },
    { label: "Allowances", href: "#allowances" },
    { label: "Mistakes", href: "#mistakes" },
    { label: "Providers", href: "#support-providers" },
    { label: "FAQ", href: "#faq" },
  ],
  introPoints: [
    "Leaving the Netherlands often involves more than booking flights, ending a lease and moving belongings. Many expats also need to think about tax residency changes, final tax filings, payroll transitions, allowances, pensions and foreign-income situations.",
    "International tax transitions can become complex quickly because departure dates, workdays, income sources, family location, property and destination-country rules may all interact.",
    "This guide is a practical awareness roadmap. It helps you collect the right records, ask better questions and know which official sources or professional services may be relevant.",
  ],
  snapshotCards: [
    { label: "Deregistration", value: "Deregistration is important" },
    { label: "Final return", value: "Final tax returns may apply" },
    { label: "Residency", value: "Tax residency may change" },
    { label: "Foreign income", value: "Foreign income questions may arise" },
    { label: "Allowances", value: "Allowances may stop or change" },
    { label: "Pensions", value: "Pension questions are common" },
  ],
  exitSnapshotExamples: [
    { topic: "Departure date", exampleFigure: "Deregister 30 June; new country registration 3 July", whyItMatters: "The dates help explain part-year residency, insurance and allowance timing.", recordToKeep: "Municipality confirmation, travel booking, new registration proof" },
    { topic: "Final salary", exampleFigure: "EUR 42,000 Dutch salary Jan-Jun plus EUR 6,000 holiday/bonus payout", whyItMatters: "Late payroll items can appear after you physically leave.", recordToKeep: "Final payslip, jaaropgaaf, employer payment letter" },
    { topic: "Ongoing Dutch tie", exampleFigure: "Amsterdam apartment rented for EUR 1,650/month after departure", whyItMatters: "Dutch property can keep tax and record questions open.", recordToKeep: "Lease, rent ledger, mortgage and expense records" },
    { topic: "Benefit change", exampleFigure: "Healthcare allowance EUR 110/month received until policy ends", whyItMatters: "Benefit dates should align with insurance, income and residency changes.", recordToKeep: "Toeslagen messages, insurer confirmation, bank payments" },
  ],
  exitChecklistCards: [
    { title: "Deregister from your municipality", body: "Municipality deregistration can create the official departure record used across Dutch admin systems." },
    { title: "Save payroll and tax records", body: "Keep final payslips, annual statements, employer letters and any bonus or severance details." },
    { title: "Update allowances", body: "Healthcare, rent, childcare and family benefits may need updates when income, household or residence changes." },
    { title: "Check health insurance timing", body: "Confirm when Dutch health insurance should end and how to avoid coverage gaps in the destination country." },
    { title: "Map residency facts", body: "List where home, family, work, income and long-term intentions move after departure." },
    { title: "Inventory Dutch assets", body: "Record any Dutch property, investments, business interests, pensions or remaining income streams." },
  ],
  deregistrationPoints: [
    "Many residents deregister from the municipality when leaving the Netherlands for a longer period.",
    "Deregistration may affect residency records, taxes, benefits, healthcare, municipal registrations and official correspondence.",
    "Keep confirmation of your deregistration, departure date, destination country and any official messages you receive.",
  ],
  deregistrationScenarioExamples: [
    { situation: "Clean single move", timeline: "Lease ends 31 May; deregistration 1 June; new job starts 10 June", practicalImpact: "Records line up cleanly across housing, tax and payroll.", usefulRecord: "Lease end letter, deregistration confirmation, new contract" },
    { situation: "Family staggered move", timeline: "Employee leaves 15 April; partner and children leave 20 August", practicalImpact: "Household, benefits and residency facts may not all change on one date.", usefulRecord: "Family BRP dates, school records, travel calendar, benefit letters" },
    { situation: "Short overlap", timeline: "Deregister 30 June but keep Dutch employer until 31 July", practicalImpact: "Payroll, work location and insurance questions can overlap.", usefulRecord: "Employer letter, July payslip, workday log, insurer message" },
  ],
  residencyFactors: [
    "Where you move and whether the new country becomes your main home.",
    "Where your partner, children or close household ties are located.",
    "Where you work after leaving and whether Dutch workdays continue.",
    "Whether you keep Dutch property, investments, business interests or recurring income.",
    "How long-term intentions, travel patterns and registrations change after departure.",
  ],
  residencyScenarioExamples: [
    { profile: "Clean employment move", facts: "Leaves 30 June, deregisters, starts foreign employer 1 July, no Dutch property", question: "Which records show the timing of departure and new-country payroll?", records: "Deregistration, final payslip, new contract, travel record" },
    { profile: "Family stays behind", facts: "Employee leaves in April; partner and children remain in Rotterdam until August", question: "How do family and home ties affect the residency picture?", records: "Family move dates, leases, school records, travel calendar" },
    { profile: "Keeps Dutch apartment", facts: "Leaves for Spain, keeps Amsterdam apartment rented at EUR 1,650/month", question: "Which Dutch asset and rental records may remain relevant?", records: "Rental contract, mortgage statements, expenses, valuations" },
  ],
  finalReturnConsiderations: [
    "Part-year residency or a split year between the Netherlands and another country.",
    "Dutch payroll adjustments, final payslip corrections, bonuses or severance.",
    "Foreign income earned before or after departure.",
    "Allowance changes, repayments, income estimates or final benefit decisions.",
    "Dutch property, investments, pension records or other ongoing Dutch connections.",
  ],
  finalReturnExamples: [
    { scenario: "Leaving-year salary split", figures: "EUR 38,000 Dutch salary Jan-Jun; EUR 44,000 foreign salary Jul-Dec", practicalQuestion: "Which payroll periods and workdays belong to each country?", records: "Dutch jaaropgaaf, foreign payslips, deregistration date, workday log" },
    { scenario: "Bonus after departure", figures: "EUR 7,500 bonus paid in September after a May departure", practicalQuestion: "How does the employer report and withhold on the payment?", records: "Bonus letter, payslip, employment end date, tax correspondence" },
    { scenario: "Allowance adjustment", figures: "Healthcare allowance received for 5 months; policy ends after deregistration", practicalQuestion: "Were income and residence changes updated on time?", records: "Toeslagen messages, policy end date, income estimate, bank records" },
  ],
  midYearExamples: [
    { timeline: "Arrive and leave in same year", example: "Arrives 1 February and leaves 30 November; Dutch salary EUR 55,000 for 10 months", practicalRecord: "BRP dates, contract dates, payslips, travel records" },
    { timeline: "Leave in spring", example: "Leaves 15 April; Dutch salary EUR 22,000 and foreign salary EUR 68,000 later in the year", practicalRecord: "Final Dutch payslip, foreign payroll records, move date evidence" },
    { timeline: "Hybrid work transition", example: "Leaves Amsterdam but works 20 Dutch workdays after moving abroad", practicalRecord: "Calendar, employer letters, travel bookings, project records" },
  ],
  rulingPoints: [
    "The 30% ruling may end or change when employment ends, residency changes or relocation occurs.",
    "Some situations involve transfer periods, new employers, final payroll corrections or international assignment transitions.",
    "Do not assume the ruling continues automatically after leaving; keep the approval letter, employer correspondence and final payslips.",
  ],
  rulingExamples: [
    { scenario: "Employment ends", figures: "Ruling approved until 2028, employment ends 31 May 2026", practicalQuestion: "How does final payroll handle the ruling up to departure?", records: "Approval letter, employment end letter, final payslip" },
    { scenario: "Transfer to group company", figures: "Dutch employer ends 30 June; foreign group contract starts 1 July", practicalQuestion: "Are there transfer, payroll or employer-application questions?", records: "Both contracts, transfer letter, ruling correspondence" },
    { scenario: "Bonus after leaving", figures: "EUR 12,000 performance bonus paid 2 months after deregistration", practicalQuestion: "How is the late payment treated in payroll records?", records: "Bonus agreement, payslip, withholding statement" },
  ],
  foreignIncomeExamples: [
    { profile: "Dutch income continues", example: "Consulting fee of EUR 4,000 from a Dutch client after moving abroad", question: "Does the Dutch-source income create ongoing filing or withholding questions?" },
    { profile: "New foreign employment", example: "Foreign salary of EUR 6,500/month starts after deregistration", question: "How do departure date, workdays and country pair affect reporting?" },
    { profile: "Pension or investment income", example: "Dutch pension accrual plus EUR 85,000 brokerage account", question: "Which year-end statements and withholding records should be saved?" },
    { profile: "Remote work overlap", example: "Works remotely from Portugal for a Dutch employer for 45 days", question: "Which payroll, treaty and social-security questions need professional review?" },
  ],
  pensionCards: [
    { title: "Employer pension", body: "Keep provider names, policy numbers, annual statements and employer pension correspondence." },
    { title: "AOW considerations", body: "AOW is separate from private tax planning; use SVB and official sources for current state-pension context." },
    { title: "Private retirement products", body: "Private pensions or retirement products may have provider-specific rules and cross-border implications." },
    { title: "Destination-country questions", body: "The country you move to can affect future taxation, reporting and practical access to pension information." },
  ],
  pensionExamples: [
    { pensionType: "Employer pension", example: "Worked in the Netherlands for 4 years with an employer pension provider", practicalQuestion: "How do you keep access to provider statements after moving?", records: "Provider login, policy number, annual UPO statement, employer pension letter" },
    { pensionType: "AOW context", example: "Lived in the Netherlands for 6 years before moving abroad", practicalQuestion: "Where can you check official state-pension context later?", records: "SVB correspondence, residence periods, deregistration date, destination-country records" },
    { pensionType: "Private retirement product", example: "Private pension or investment wrapper remains open after departure", practicalQuestion: "Does the provider allow non-resident access and what tax records are needed?", records: "Provider terms, statements, contribution history, destination address updates" },
  ],
  propertyInvestmentExamples: [
    { asset: "Dutch rental apartment", example: "Rent EUR 1,650/month, mortgage EUR 950/month, service costs EUR 180/month", practicalCheck: "Keep lease, rent ledger, mortgage and expense records." },
    { asset: "Sale after departure", example: "Apartment sold 4 months after deregistration for EUR 475,000", practicalCheck: "Keep notary documents, valuation, mortgage closeout and tax records." },
    { asset: "Dutch business interest", example: "Freelance KVK registration remains open with EUR 8,000 final invoices", practicalCheck: "Check business closure, VAT, income and client-country records." },
  ],
  allowanceCards: [
    { title: "Healthcare allowance", body: "May stop or change when Dutch insurance, income, partner status or residency changes." },
    { title: "Rent allowance", body: "May change when you leave the address, end the lease or deregister from the municipality." },
    { title: "Childcare allowance", body: "May change when childcare use, work status, income or country of residence changes." },
    { title: "Child benefit", body: "Family benefits can have separate rules; check SVB and official correspondence." },
  ],
  allowanceExamples: [
    { allowance: "Healthcare allowance", exampleInputs: "Allowance received EUR 110/month; policy ends 30 June", whatToCheck: "Whether policy end, income and residence changes are updated.", usefulRecord: "Policy end confirmation, Toeslagen decision, bank payments" },
    { allowance: "Rent allowance", exampleInputs: "Rent EUR 820/month; lease ends 15 May; deregistration 20 May", whatToCheck: "Which date ends eligibility and how service costs are treated.", usefulRecord: "Lease termination, deregistration, Toeslagen messages" },
    { allowance: "Childcare allowance", exampleInputs: "Childcare EUR 1,350/month until family move in August", whatToCheck: "Work status, childcare hours, provider invoices and move dates.", usefulRecord: "Invoices, contracts, employer letters, family BRP records" },
    { allowance: "Child benefit", exampleInputs: "Two children move abroad 2 months after parent departure", whatToCheck: "How family move timing affects official family benefit rules.", usefulRecord: "SVB letters, school records, family registration dates" },
  ],
  healthcareExamples: [
    { scenario: "Single employee leaves", timeline: "Deregister 31 July, foreign job starts 1 August", practicalQuestion: "When does Dutch insurance end and new-country coverage start?", records: "Deregistration, insurer confirmation, new policy" },
    { scenario: "Family moves later", timeline: "Employee leaves May; family leaves August", practicalQuestion: "Do family members have different insurance and allowance dates?", records: "Individual policies, family move dates, official messages" },
    { scenario: "Remote Dutch payroll", timeline: "Leaves NL but keeps Dutch employer for 3 months", practicalQuestion: "Does employment status affect insurance or social security?", records: "Employer letter, payroll records, insurer correspondence" },
  ],
  remoteWorkExamples: [
    { pattern: "Dutch employer, abroad full-time", complexity: "Payroll, residency, social security and treaty questions may overlap.", practicalMove: "Keep workday logs and get employer/payroll confirmation." },
    { pattern: "Foreign employer, Dutch clients", complexity: "Client location, business presence and invoicing may matter.", practicalMove: "Keep contracts, invoices, KVK/VAT records and location evidence." },
    { pattern: "Hybrid international travel", complexity: "Several countries can create overlapping workday and reporting questions.", practicalMove: "Track physical workdays by country with calendar evidence." },
  ],
  mistakeCards: [
    { title: "Forgetting deregistration", body: "Without an official date trail, later tax, benefit and healthcare questions can become harder to explain." },
    { title: "Ignoring final tax obligations", body: "Leaving the country does not automatically close every Dutch tax or payroll question." },
    { title: "Overlooking foreign income", body: "New-country salary, remote work, pensions or investments may interact with Dutch exit-year records." },
    { title: "Assuming taxes end immediately", body: "Dutch-source income, property, business interests or pensions can keep questions open." },
    { title: "Forgetting allowance changes", body: "Benefits may need updates when residence, insurance, rent, childcare or income changes." },
    { title: "Ignoring pension implications", body: "Lost provider details and missing statements can create practical problems years later." },
    { title: "Delaying professional advice", body: "Multi-country situations are easier to review before records are scattered." },
    { title: "Assuming home-country rules apply", body: "Your destination country may use different residency, payroll and filing concepts." },
  ],
  mistakeScenarioExamples: [
    { mistake: "Allowance not updated", example: "Receives EUR 110/month healthcare allowance for 3 months after Dutch policy ends", possibleConsequence: "Later correction or repayment request if eligibility changed.", betterRecord: "Policy end date, Toeslagen update confirmation, bank payments" },
    { mistake: "No workday log", example: "Works 45 days from abroad for Dutch employer after moving", possibleConsequence: "Harder to explain payroll, treaty and social-security facts.", betterRecord: "Calendar, travel bookings, employer confirmation" },
    { mistake: "Lost pension provider details", example: "Leaves after 4 years of pension accrual and loses login/provider name", possibleConsequence: "Harder to retrieve statements or update address later.", betterRecord: "Provider portal, policy number, annual UPO statement" },
    { mistake: "Assuming tax is finished", example: "EUR 7,500 bonus paid 2 months after departure", possibleConsequence: "Late Dutch payroll and final return questions can be missed.", betterRecord: "Bonus letter, payslip, employment end letter" },
  ],
  adviceTriggers: [
    "Two or more countries involved in the same tax year.",
    "Dutch or foreign property, rental income, investments or business interests.",
    "Pensions, AOW questions or private retirement products.",
    "Remote work, foreign employers, Dutch clients or self-employment.",
    "Bonuses, severance, equity compensation or highly compensated roles.",
    "Family moves at different times or keeps ties in more than one country.",
  ],
  advisorBriefExamples: [
    { situation: "Two-country salary year", numbersToBring: "EUR 36,000 Dutch salary and EUR 54,000 foreign salary", documentsToBring: "Deregistration, contracts, payslips, workday calendar" },
    { situation: "Dutch apartment kept", numbersToBring: "EUR 1,650 monthly rent, EUR 950 mortgage, EUR 180 costs", documentsToBring: "Lease, mortgage statement, notary/valuation records" },
    { situation: "Remote work transition", numbersToBring: "45 Dutch workdays after move, 120 foreign workdays", documentsToBring: "Calendar, travel records, employer letters, payroll records" },
  ],
  expatQuestions: [
    { q: "Do I need to file taxes after leaving?", a: "Many expats file or receive tax correspondence after departure, especially for part-year residency, payroll corrections, allowances or foreign-income questions." },
    { q: "What happens to the 30% ruling?", a: "It may end or change when employment, residency or payroll facts change. Keep the approval letter and ask the employer how final payroll is handled." },
    { q: "Do allowances stop automatically?", a: "Do not assume that benefits stop correctly without updates. Check healthcare, rent, childcare and family benefit messages through official sources." },
    { q: "What about Dutch pensions?", a: "Leaving does not erase pension history. Keep employer pension records and check SVB for official AOW-related information." },
    { q: "What if I keep Dutch property?", a: "Dutch real estate, rental income or a sale after departure can keep Dutch tax questions open and deserves organized records." },
    { q: "What happens if I move mid-year?", a: "A mid-year departure can create a split year with Dutch payroll, foreign income and residency timing questions." },
    { q: "Do I still owe Dutch taxes abroad?", a: "That depends on your personal facts, income sources, residency and country pair. This page helps identify questions, not guarantee outcomes." },
    { q: "What if I work remotely?", a: "Remote work can involve payroll, treaty, workday and social-security questions. Track physical work locations and employer arrangements." },
  ],
  questionScenarioExamples: [
    { question: "Do I need to file after leaving?", exampleFacts: "Dutch salary EUR 38,000 Jan-Jun, foreign salary EUR 44,000 Jul-Dec", firstCheck: "Look for tax authority messages and organize both payroll periods.", usefulRecord: "Jaaropgaaf, foreign payslips, deregistration confirmation" },
    { question: "Do allowances stop automatically?", exampleFacts: "Rent allowance linked to EUR 820/month lease ending 15 May", firstCheck: "Check whether benefit records reflect the lease and address change.", usefulRecord: "Lease termination, BRP confirmation, Toeslagen letters" },
    { question: "What if I keep property?", exampleFacts: "Property sold 4 months after departure for EUR 475,000", firstCheck: "Keep sale, mortgage, valuation and notary records together.", usefulRecord: "Notary deed, mortgage closeout, valuation and expense records" },
    { question: "What if I work remotely?", exampleFacts: "20 Dutch workdays before leaving and 45 abroad for same employer", firstCheck: "Separate physical workdays by country before discussing tax treatment.", usefulRecord: "Calendar, travel records, employer letter" },
  ],
  relatedGuides: [
    { label: "Expat Taxes Netherlands", href: "/netherlands/taxes/expat-taxes-netherlands/", description: "A broad guide to Dutch tax concepts for expats." },
    { label: "Double Taxation Netherlands", href: "/netherlands/taxes/double-taxation-netherlands/", description: "Understand treaty concepts and double-taxation relief awareness." },
    { label: "Foreign Income Netherlands", href: "/netherlands/taxes/foreign-income-netherlands/", description: "Map overseas income, assets and cross-border records." },
    { label: "30% Ruling", href: "/netherlands/taxes/30-percent-ruling/", description: "Learn how the expat tax facility works conceptually." },
    { label: "Taxes After Moving Netherlands", href: "/netherlands/taxes/taxes-after-moving-netherlands/", description: "Read the arrival-side companion to this exit guide." },
    { label: "Permanent residence guide", href: "/netherlands/citizenship/permanent-residence/", description: "Long-term stay planning before you decide to leave or naturalise." },
    { label: "Dutch citizenship guide", href: "/netherlands/citizenship/dutch-citizenship/", description: "Naturalisation and dual nationality context if exit timing is uncertain." },
  ] satisfies LeavingNetherlandsTaxLink[],
  services: [
    { label: "Expat tax advisors", href: "/netherlands/services/expat-tax-services/", description: "For final return, residency and cross-border tax questions." },
    { label: "International tax specialists", href: "/netherlands/services/tax-advisors/", description: "For complex multi-country tax and treaty situations." },
    { label: "Relocation services", href: "/netherlands/services/relocation-services/", description: "For departure admin, records and move coordination." },
    { label: "Immigration lawyers", href: "/netherlands/services/immigration-lawyers/", description: "For immigration status and cross-border mobility questions." },
    { label: "Financial advisors", href: "/netherlands/services/financial-advisors/", description: "For pension, investment and long-term planning context." },
  ] satisfies LeavingNetherlandsTaxLink[],
  serviceScenarioExamples: [
    { provider: "Expat tax advisor", exampleCase: "Moved 30 June with EUR 42,000 Dutch salary and EUR 44,000 foreign salary", usefulFor: "Leaving-year return, income split and record checklist.", documents: "Payslips, jaaropgaaf, deregistration, foreign salary records" },
    { provider: "International tax specialist", exampleCase: "Keeps Dutch property rented at EUR 1,650/month while resident abroad", usefulFor: "Multi-country property, treaty and ongoing Dutch-source questions.", documents: "Lease, mortgage, rent ledger, destination-country records" },
    { provider: "Relocation service", exampleCase: "Family leaves in two stages over 4 months", usefulFor: "Coordinating deregistration, address changes, schools and document trails.", documents: "BRP confirmations, travel dates, school/lease records" },
    { provider: "Financial advisor", exampleCase: "Employer pension from 6 Dutch working years plus EUR 85,000 investments", usefulFor: "Organizing pension, investments and long-term record access.", documents: "Pension statements, brokerage statements, provider letters" },
  ],
  faq: [
    { q: "What happens tax-wise when leaving the Netherlands?", a: "Leaving can affect tax residency, final tax returns, payroll, allowances, pensions, healthcare and foreign-income records. The exact outcome depends on personal facts and destination country." },
    { q: "Do I need to file taxes after leaving?", a: "Many expats may still need to file or respond to tax correspondence after leaving, especially if they moved mid-year, had Dutch payroll, received allowances or kept Dutch assets." },
    { q: "What happens to the 30% ruling?", a: "The 30% ruling may end or change when employment ends, residency changes or payroll moves. Eligibility and timing should be checked with official records and employer guidance." },
    { q: "What happens to Dutch pensions?", a: "Dutch employer pension rights and AOW-related questions do not disappear when you leave. Keep provider statements and use SVB for official state-pension context." },
    { q: "What if I keep Dutch property?", a: "Keeping Dutch property, rental income or a Dutch business interest can continue creating Dutch tax considerations after relocation." },
    { q: "Do allowances stop automatically?", a: "Do not rely on assumptions. Healthcare, rent, childcare and family benefits may need updates when residence, income, insurance or household facts change." },
    { q: "What if I move mid-year?", a: "A mid-year departure can create part-year residency, two-country income and final payroll questions. Keep dates, payslips, travel records and official messages." },
    { q: "Do I still owe Dutch taxes abroad?", a: "That depends on residency, income source, Dutch ties, tax treaties and personal circumstances. This guide is educational and does not provide tax advice." },
  ],
  officialSources: [
    { label: "Belastingdienst", href: "https://www.belastingdienst.nl/", description: "Official Dutch tax authority for tax returns, assessments, residency and filing context." },
    { label: "Government.nl", href: "https://www.government.nl/", description: "Official English-language government information about Dutch public administration and leaving-related topics." },
    { label: "NederlandWereldwijd", href: "https://www.nederlandwereldwijd.nl/", description: "Official cross-border information for Dutch and Netherlands-linked international situations." },
    { label: "Business.gov.nl", href: "https://business.gov.nl/", description: "Official business and self-employment information for entrepreneurs and freelancers." },
    { label: "SVB", href: "https://www.svb.nl/", description: "Official source for AOW and selected family benefit information." },
  ],
  sourcesDisclaimer:
    "Tax residency, pensions, benefits and reporting obligations may vary significantly depending on personal circumstances and destination country. Use official sources for current rules and professional advice for your situation.",
  relatedFooterGuides: [
    { label: "Taxes Hub", href: "/netherlands/taxes/", description: "Start from the main Dutch tax guide hub." },
    { label: "Taxes After Moving", href: "/netherlands/taxes/taxes-after-moving-netherlands/", description: "Understand first tax steps after arriving." },
    { label: "Double Taxation", href: "/netherlands/taxes/double-taxation-netherlands/", description: "Explore treaty and double-taxation concepts." },
    { label: "Foreign Income", href: "/netherlands/taxes/foreign-income-netherlands/", description: "Map cross-border income and records." },
    { label: "30% Ruling", href: "/netherlands/taxes/30-percent-ruling/", description: "Learn about the expat tax facility." },
    { label: "Moving to the Netherlands", href: "/netherlands/moving-to-the-netherlands/", description: "Read the broader relocation guide." },
  ] satisfies LeavingNetherlandsTaxLink[],
  exploreNextCards: [
    { label: "Double Taxation", href: "/netherlands/taxes/double-taxation-netherlands/", description: "Understand treaty concepts before assuming where income is taxed." },
    { label: "Foreign Income", href: "/netherlands/taxes/foreign-income-netherlands/", description: "Inventory salary, property, pensions and investments across borders." },
    { label: "Expat Taxes", href: "/netherlands/taxes/expat-taxes-netherlands/", description: "Review the broader Dutch tax framework for expats." },
    { label: "30% Ruling", href: "/netherlands/taxes/30-percent-ruling/", description: "Check the conceptual rules around the expat tax facility." },
    { label: "Moving to the Netherlands", href: "/netherlands/moving-to-the-netherlands/", description: "Return to the broader relocation ecosystem." },
    { label: "Permanent residence", href: "/netherlands/citizenship/permanent-residence/", description: "Long-term stay planning if exit timing is still open." },
  ] satisfies LeavingNetherlandsTaxLink[],
} as const;
