import { Children, type ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Banknote, BriefcaseBusiness, Building2, CheckCircle2, ClipboardCheck, FileText, Globe2, HeartPulse, Home, Landmark, Laptop, ReceiptText, Scale, ShieldCheck, WalletCards } from "lucide-react";
import { BreadcrumbJsonLd } from "@/components/content/breadcrumb-jsonld";
import { Container } from "@/components/ui/container";
import { cn } from "@/lib/cn";
import { activeBrightnessPress, transitionInteractive } from "@/lib/ui/interaction";
import { siteGuideColumnPadYClass, siteHeroFramedShellClass, siteHeroGlowPrimaryClass, siteHeroGlowSecondaryClass, siteHeroTopAccentClass, sitePageCanvasClass } from "@/lib/ui/site-shell-identity";
import { movingNlCardMicroLiftClass, movingNlSectionH2Class, movingNlSectionH2OnDarkClass, movingNlSignatureGradientClass } from "@/lib/ui/moving-nl-pillar-identity";
import { AffiliateBlockView } from "@/src/components/affiliates/AffiliateBlockView";
import { citiesFunnelHeroFigureClassName, CITIES_FUNNEL_INFO_CHIP, CITIES_FUNNEL_SECTION_SCROLL_MARGIN, CITIES_FUNNEL_SOFT_COPILOT_SURFACE } from "@/src/components/cities/shared/citiesFunnelPageUi";
import { loadPlacementWithProviders } from "@/src/lib/affiliates/loadAffiliates";
import { leavingNetherlandsTaxPage as page, type LeavingNetherlandsTaxLink } from "./leavingNetherlandsTaxPageModel";

const sectionClass = cn(CITIES_FUNNEL_SECTION_SCROLL_MARGIN, CITIES_FUNNEL_SOFT_COPILOT_SURFACE, "relative isolate overflow-hidden p-6 shadow-card ring-1 ring-slate-900/[0.04] before:pointer-events-none before:absolute before:inset-x-0 before:top-0 before:h-1 before:bg-gradient-to-r before:from-cyan-400/70 before:via-brand/80 before:to-emerald-300/70 after:pointer-events-none after:absolute after:-right-28 after:-top-28 after:h-56 after:w-56 after:rounded-full after:bg-cyan-200/15 after:blur-3xl sm:p-8 lg:p-10");
const sectionStackClass = "mt-8 space-y-6 sm:space-y-8 md:space-y-9";
const mutedCardClass = cn(CITIES_FUNNEL_SOFT_COPILOT_SURFACE, "relative overflow-hidden bg-white/90 p-5 shadow-sm ring-1 ring-slate-900/[0.04]", movingNlCardMicroLiftClass);
const icons = [Globe2, Landmark, Home, Laptop, ReceiptText, BriefcaseBusiness, Banknote, Scale, FileText, WalletCards, Building2, ClipboardCheck, ShieldCheck, HeartPulse] as const;
const primaryCtaClass = cn("inline-flex min-h-[44px] items-center justify-center gap-2 rounded-xl border border-brand-strong/25 bg-brand px-5 py-2.5 text-sm font-semibold text-white shadow-card hover:bg-brand-strong focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2 focus-visible:ring-offset-canvas", transitionInteractive, activeBrightnessPress);
const secondaryCtaClass = cn("inline-flex min-h-[44px] items-center justify-center gap-2 rounded-xl border border-border bg-surface-raised px-5 py-2.5 text-sm font-semibold text-foreground shadow-card hover:border-border-strong hover:bg-surface-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2 focus-visible:ring-offset-canvas", transitionInteractive, activeBrightnessPress);

function SectionIntro({ eyebrow, title, children, tone = "default", fullWidth = false }: { eyebrow?: string; title: string; children?: ReactNode; tone?: "default" | "onDark"; fullWidth?: boolean }) {
  const onDark = tone === "onDark";
  const useColumnLayout = fullWidth && Children.count(children) > 1;
  return <div className={cn(fullWidth ? "w-full max-w-none" : "max-w-3xl")}>{eyebrow ? <p className={cn("text-xs font-bold uppercase tracking-[0.14em]", onDark ? "text-cyan-200" : "text-brand-strong")}>{eyebrow}</p> : null}<h2 className={cn(onDark ? movingNlSectionH2OnDarkClass : movingNlSectionH2Class, eyebrow ? "mt-2" : undefined)}>{title}</h2>{children ? <div className={cn("mt-3 w-full space-y-3 text-base leading-relaxed", useColumnLayout && "max-w-none lg:columns-2 lg:gap-x-10 [&>p]:break-inside-avoid", onDark ? "text-slate-300" : "text-foreground-muted")}>{children}</div> : null}</div>;
}

function VisualFigure({ visual }: { visual: (typeof page.visuals)[keyof typeof page.visuals] }) {
  return <figure className={cn("relative isolate overflow-hidden rounded-[2rem] border border-slate-200/90 bg-white/95 shadow-expatos-xl ring-1 ring-slate-900/[0.05]", movingNlCardMicroLiftClass)}><div className={cn("h-1.5", movingNlSignatureGradientClass)} aria-hidden /><div className="pointer-events-none absolute -right-20 -top-20 h-44 w-44 rounded-full bg-cyan-200/25 blur-3xl" aria-hidden /><div className="relative aspect-[4/3] bg-gradient-to-br from-slate-50 via-white to-copilot-bg-soft p-2 sm:p-3"><Image src={visual.src} alt={visual.alt} fill sizes="(min-width: 1024px) 900px, 100vw" className="object-contain p-2 sm:p-3 drop-shadow-sm" /></div><figcaption className="border-t border-slate-200/80 bg-slate-50/90 px-4 py-3 text-sm leading-relaxed text-foreground-muted sm:px-5">{visual.caption}</figcaption></figure>;
}

function HeroImage() {
  return <figure className={citiesFunnelHeroFigureClassName()}><div className={cn("absolute inset-x-0 top-0 z-10 h-1.5", movingNlSignatureGradientClass)} aria-hidden /><Image src={page.hero.image.src} alt={page.hero.image.alt} width={1600} height={900} priority sizes="(min-width: 1024px) 42vw, 100vw" className="h-full w-full object-cover" /><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-slate-950/24 via-transparent to-white/10" aria-hidden /><div className="pointer-events-none absolute inset-0 ring-1 ring-inset ring-white/35" aria-hidden /></figure>;
}

function HeroSignalStrip() {
  return <div className="relative mt-5 grid gap-3 overflow-hidden rounded-[1.75rem] border border-slate-200/80 bg-white/82 p-3 shadow-card ring-1 ring-slate-900/[0.03] backdrop-blur-xl sm:grid-cols-2 lg:grid-cols-4"><div className={cn("absolute inset-x-0 top-0 h-1", movingNlSignatureGradientClass)} aria-hidden />{page.snapshotCards.slice(0, 4).map((card, index) => <StatCard key={card.label} label={card.label} value={card.value} iconIndex={index} />)}</div>;
}

function StatCard({ label, value, iconIndex }: { label: string; value: string; iconIndex: number }) {
  const Icon = icons[iconIndex % icons.length];
  return <article className={cn(mutedCardClass, "min-h-full")}><div className={cn("absolute inset-x-0 top-0 h-1.5 rounded-t-2xl", movingNlSignatureGradientClass)} aria-hidden /><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong shadow-sm ring-1 ring-copilot-primary/10"><Icon className="h-5 w-5" aria-hidden /></span><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-foreground-muted">{label}</p><p className="mt-1 text-base font-bold leading-snug text-foreground">{value}</p></div></div></article>;
}

function FeatureCard({ title, body, iconIndex = 0 }: { title: string; body: string; iconIndex?: number }) {
  const Icon = icons[iconIndex % icons.length];
  return <article className={cn(mutedCardClass, "min-h-full")}><div className={cn("absolute inset-x-0 top-0 h-1 rounded-t-2xl", movingNlSignatureGradientClass)} aria-hidden /><div className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong shadow-sm ring-1 ring-copilot-primary/10"><Icon className="h-5 w-5" aria-hidden /></span><div><h3 className="text-base font-bold tracking-tight text-foreground">{title}</h3><p className="mt-2 text-sm leading-relaxed text-foreground-muted">{body}</p></div></div></article>;
}

function LinkCard({ item, iconIndex = 0, tone = "default" }: { item: LeavingNetherlandsTaxLink; iconIndex?: number; tone?: "default" | "onDark" }) {
  const Icon = icons[iconIndex % icons.length];
  const isLive = item.status !== "comingSoon";
  const onDark = tone === "onDark";
  const shell = onDark ? "relative overflow-hidden rounded-2xl border border-white/10 bg-white/10 p-5 shadow-sm ring-1 ring-white/10" : cn(CITIES_FUNNEL_SOFT_COPILOT_SURFACE, "relative overflow-hidden p-5", movingNlCardMicroLiftClass);
  const body = <><div className={cn("absolute inset-x-0 top-0 h-1.5 rounded-t-2xl", isLive ? movingNlSignatureGradientClass : onDark ? "bg-white/20" : "bg-slate-200")} aria-hidden /><div className="flex gap-3"><span className={cn("flex h-10 w-10 shrink-0 items-center justify-center rounded-xl shadow-sm ring-1", onDark ? "bg-white/10 text-cyan-100 ring-white/15" : isLive ? "bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong ring-copilot-primary/10" : "bg-slate-100 text-slate-500 ring-slate-200")}><Icon className="h-5 w-5" aria-hidden /></span><span className="min-w-0"><span className={cn("text-sm font-bold", onDark ? "text-white" : "text-foreground")}>{item.label}</span>{!isLive ? <span className={cn("ml-2 rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-[0.1em]", onDark ? "bg-white/10 text-slate-300 ring-1 ring-white/10" : "bg-slate-100 text-slate-500")}>Coming soon</span> : null}{item.description ? <span className={cn("mt-2 block text-sm leading-relaxed", onDark ? "text-slate-300" : "text-foreground-muted")}>{item.description}</span> : null}</span></div>{isLive ? <span className={cn("mt-4 inline-flex items-center gap-1 text-xs font-semibold", onDark ? "text-cyan-200" : "text-link group-hover:text-link-hover")}>Open <ArrowRight className="h-3.5 w-3.5" aria-hidden /></span> : null}</>;
  if (!isLive) return <article className={cn(shell, "opacity-90")}>{body}</article>;
  return <Link href={item.href} className={cn(shell, "group block focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2", onDark ? "focus-visible:ring-offset-slate-950" : "focus-visible:ring-offset-canvas", transitionInteractive, activeBrightnessPress)}>{body}</Link>;
}

function BulletPanel({ title, items }: { title: string; items: readonly string[] }) {
  return <aside className={cn("relative overflow-hidden rounded-3xl border border-slate-200/90 bg-white/95 p-5 shadow-sm ring-1 ring-slate-900/[0.04]", movingNlCardMicroLiftClass)}><div className={cn("absolute inset-x-0 top-0 h-1 rounded-t-3xl", movingNlSignatureGradientClass)} aria-hidden /><h3 className="text-base font-bold tracking-tight text-foreground">{title}</h3><ul className="mt-4 grid gap-3">{items.map((item) => <li key={item} className="flex gap-3 text-sm leading-relaxed text-foreground-muted"><span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-copilot-bg-soft text-brand-strong ring-1 ring-copilot-primary/10"><CheckCircle2 className="h-3.5 w-3.5" aria-hidden /></span><span>{item}</span></li>)}</ul></aside>;
}

function ExampleTable({ title, columns, rows }: { title: string; columns: readonly string[]; rows: readonly Record<string, string>[] }) {
  return <div className={cn("relative overflow-hidden rounded-3xl border border-slate-200/90 bg-white/95 shadow-sm ring-1 ring-slate-900/[0.04]", movingNlCardMicroLiftClass)}><div className={cn("absolute inset-x-0 top-0 h-1", movingNlSignatureGradientClass)} aria-hidden /><div className="border-b border-slate-200/80 px-5 py-4"><h3 className="text-base font-bold tracking-tight text-foreground">{title}</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-slate-200/80 bg-slate-50/80">{columns.map((column) => <th key={column} scope="col" className="px-4 py-3 font-bold text-foreground">{column}</th>)}</tr></thead><tbody>{rows.map((row, rowIndex) => <tr key={`${title}-${rowIndex}`} className="border-b border-slate-100 last:border-0">{columns.map((column) => <td key={column} className="px-4 py-3 leading-relaxed text-foreground-muted">{row[column]}</td>)}</tr>)}</tbody></table></div></div>;
}

function SourcesSection() {
  return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{page.officialSources.map((source) => <a key={source.href} href={source.href} className={cn("group relative block overflow-hidden rounded-2xl border border-slate-200/90 bg-white/95 p-5 shadow-sm ring-1 ring-slate-900/[0.04] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2 focus-visible:ring-offset-canvas", movingNlCardMicroLiftClass, transitionInteractive, activeBrightnessPress)} target="_blank" rel="noreferrer"><div className={cn("absolute inset-x-0 top-0 h-1 rounded-t-2xl", movingNlSignatureGradientClass)} aria-hidden /><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong shadow-sm ring-1 ring-copilot-primary/10"><ShieldCheck className="h-5 w-5" aria-hidden /></span><span><span className="text-sm font-bold text-foreground">{source.label}</span><span className="mt-2 block text-sm leading-relaxed text-foreground-muted">{source.description}</span><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-link group-hover:text-link-hover">Open official source <ArrowRight className="h-3.5 w-3.5" aria-hidden /></span></span></div></a>)}</div>;
}

const crumbs = [{ name: "Home", item: "/" }, { name: "Netherlands", item: "/netherlands/" }, { name: "Taxes", item: "/netherlands/taxes/" }, { name: page.hero.pageTitle, item: page.path }];
const supportProviders = loadPlacementWithProviders("nl-taxes-leaving-netherlands-tax-support-providers", "netherlands", undefined);

export function LeavingNetherlandsTaxView() {
  return (
    <>
      <BreadcrumbJsonLd crumbs={crumbs} />
      <main className={sitePageCanvasClass}>
        <Container className={cn("w-full max-w-screen-2xl", siteGuideColumnPadYClass)}>
          <section className={cn(siteHeroFramedShellClass, "overflow-hidden p-6 shadow-expatos-xl sm:p-8 lg:p-12")}>
            <div className={siteHeroTopAccentClass} aria-hidden /><div className={siteHeroGlowPrimaryClass} aria-hidden /><div className={siteHeroGlowSecondaryClass} aria-hidden />
            <div className="relative grid gap-8 lg:grid-cols-[minmax(0,1fr)_0.78fr] lg:items-center">
              <div><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-strong">{page.hero.eyebrow}</p><h1 className="mt-3 max-w-4xl text-4xl font-bold tracking-tight text-foreground sm:text-5xl lg:text-6xl">{page.hero.pageTitle}</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-foreground-muted sm:text-xl">{page.hero.subtitle}</p><div className="mt-6 flex flex-wrap gap-2">{page.hero.chips.map((chip) => <span key={chip} className={cn(CITIES_FUNNEL_INFO_CHIP, "shadow-sm ring-1 ring-slate-900/[0.03]")}>{chip}</span>)}</div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href={page.hero.primaryCta.href} className={primaryCtaClass}>{page.hero.primaryCta.label}<ArrowRight className="h-4 w-4" aria-hidden /></Link><Link href={page.hero.secondaryCta.href} className={secondaryCtaClass}>{page.hero.secondaryCta.label}</Link></div><p className="mt-5 max-w-3xl rounded-2xl border border-slate-200/80 bg-white/70 px-4 py-3 text-sm leading-relaxed text-foreground-muted shadow-sm ring-1 ring-slate-900/[0.03]">Educational orientation only. This page is not tax advice, legal advice, personalized filing advice or emigration planning advice.</p></div>
              <HeroImage />
            </div>
          </section>
          <HeroSignalStrip />
          <nav className="sticky top-3 z-20 mt-6 flex gap-2 overflow-x-auto rounded-2xl border border-slate-200/80 bg-white/90 p-2 shadow-card ring-1 ring-slate-900/[0.04] backdrop-blur-xl" aria-label="Leaving the Netherlands tax guide sections">{page.sectionNav.map((item) => <a key={item.href} href={item.href} className={cn("shrink-0 rounded-xl px-3 py-2 text-sm font-semibold text-foreground-muted hover:bg-copilot-bg-soft hover:text-brand-strong focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30", transitionInteractive, activeBrightnessPress)}>{item.label}</a>)}</nav>

          <div className={sectionStackClass}>
            <section id="intro" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Core concept" title="What Happens Tax-Wise When Leaving the Netherlands?" fullWidth>{page.introPoints.map((point) => <p key={point}>{point}</p>)}</SectionIntro><VisualFigure visual={page.visuals.intro} /></div></section>
            <section id="snapshot" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="At a glance" title="Leaving the Netherlands at a Glance"><p>Use this as an exit triage checklist: confirm what changes immediately, what depends on facts and which records to keep for the leaving year.</p></SectionIntro><VisualFigure visual={page.visuals.snapshot} /></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{page.snapshotCards.map((card, index) => <StatCard key={card.label} label={card.label} value={card.value} iconIndex={index} />)}</div><div className="mt-6"><ExampleTable title="Exit snapshot examples with figures" columns={["Topic", "Example figure", "Why it matters", "Record to keep"]} rows={page.exitSnapshotExamples.map((row) => ({ Topic: row.topic, "Example figure": row.exampleFigure, "Why it matters": row.whyItMatters, "Record to keep": row.recordToKeep }))} /></div></section>
            <section id="deregister" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Municipality records" title="Deregistering From Your Municipality"><p>Many residents deregister when leaving the Netherlands. This may affect residency records, taxes, benefits, healthcare and municipal registrations.</p></SectionIntro><VisualFigure visual={page.visuals.deregister} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{page.exitChecklistCards.map((card, index) => <FeatureCard key={card.title} title={card.title} body={card.body} iconIndex={index} />)}</div><div className="mt-6"><BulletPanel title="Deregistration points to remember" items={page.deregistrationPoints} /></div><div className="mt-6"><ExampleTable title="Deregistration scenario examples" columns={["Situation", "Timeline", "Practical impact", "Useful record"]} rows={page.deregistrationScenarioExamples.map((row) => ({ Situation: row.situation, Timeline: row.timeline, "Practical impact": row.practicalImpact, "Useful record": row.usefulRecord }))} /></div></section>
            <section id="residency" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Tax residency" title="What Happens to Dutch Tax Residency?"><p>Tax residency may change depending on where you move, family location, economic ties, work arrangements and long-term intentions. Leaving physically does not always create immediate tax simplicity.</p></SectionIntro><VisualFigure visual={page.visuals.residency} /></div><div className="mt-6"><BulletPanel title="Residency facts to map" items={page.residencyFactors} /></div><div className="mt-6"><ExampleTable title="Tax residency scenario examples" columns={["Profile", "Facts", "Question", "Records"]} rows={page.residencyScenarioExamples.map((row) => ({ Profile: row.profile, Facts: row.facts, Question: row.question, Records: row.records }))} /></div></section>
            <section id="final-return" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Final filing" title="Final Tax Returns in the Netherlands"><p>Many expats file a final Dutch tax return after leaving. Possible considerations include part-year residency, foreign income, payroll adjustments, deductions and allowances.</p></SectionIntro><VisualFigure visual={page.visuals.finalReturn} /></div><div className="mt-6"><BulletPanel title="Final return considerations" items={page.finalReturnConsiderations} /></div><div className="mt-6"><ExampleTable title="Final return examples with figures" columns={["Scenario", "Figures", "Practical question", "Records"]} rows={page.finalReturnExamples.map((row) => ({ Scenario: row.scenario, Figures: row.figures, "Practical question": row.practicalQuestion, Records: row.records }))} /></div></section>
            <section id="mid-year" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Timing" title="Leaving During the Tax Year"><p>Many expats arrive mid-year, leave mid-year or split work across countries. This can create partial residency, multi-country reporting and foreign-income questions.</p></SectionIntro><VisualFigure visual={page.visuals.midYear} /></div><div className="mt-6"><ExampleTable title="Mid-tax-year departure examples" columns={["Timeline", "Example", "Practical record"]} rows={page.midYearExamples.map((row) => ({ Timeline: row.timeline, Example: row.example, "Practical record": row.practicalRecord }))} /></div></section>
            <section id="ruling" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="30% ruling" title="The 30% Ruling After Leaving"><p>The 30% ruling may end or change when employment ends, residency changes or relocation occurs. Some situations involve transfer periods, new employers and international transitions.</p></SectionIntro><VisualFigure visual={page.visuals.ruling} /></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><BulletPanel title="How to frame the 30% ruling" items={page.rulingPoints} /><LinkCard item={page.relatedGuides[3]} iconIndex={3} /></div><div className="mt-6"><ExampleTable title="30% ruling exit examples" columns={["Scenario", "Figures", "Practical question", "Records"]} rows={page.rulingExamples.map((row) => ({ Scenario: row.scenario, Figures: row.figures, "Practical question": row.practicalQuestion, Records: row.records }))} /></div></section>
            <section id="foreign-income" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="International income" title="Foreign Income and International Tax Questions"><p>After leaving, expats may still have Dutch income, Dutch investments, foreign employment, pensions or remote work income. Cross-border tax situations can remain complex after relocation.</p></SectionIntro><VisualFigure visual={page.visuals.foreignIncome} /></div><div className="mt-6"><ExampleTable title="Foreign-income scenarios after leaving" columns={["Profile", "Example", "Question"]} rows={page.foreignIncomeExamples.map((row) => ({ Profile: row.profile, Example: row.example, Question: row.question }))} /></div><div className="mt-6 grid gap-4 md:grid-cols-2"><LinkCard item={page.relatedGuides[2]} iconIndex={2} /><LinkCard item={page.relatedGuides[1]} iconIndex={1} /></div></section>
            <section id="pensions" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Retirement records" title="Pensions and Retirement Considerations"><p>Expats may have employer pensions, AOW considerations and private retirement products. Leaving the Netherlands does not necessarily eliminate pension considerations.</p></SectionIntro><VisualFigure visual={page.visuals.pensions} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.pensionCards.map((card, index) => <FeatureCard key={card.title} title={card.title} body={card.body} iconIndex={index} />)}</div><div className="mt-6"><ExampleTable title="Pension record examples" columns={["Pension type", "Example", "Practical question", "Records"]} rows={page.pensionExamples.map((row) => ({ "Pension type": row.pensionType, Example: row.example, "Practical question": row.practicalQuestion, Records: row.records }))} /></div></section>
            <section id="property-investments" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Assets" title="Keeping Dutch Property or Investments"><p>Some expats leave while still owning Dutch property, rental apartments, investments or businesses. These may continue creating Dutch tax considerations.</p></SectionIntro><VisualFigure visual={page.visuals.propertyInvestments} /></div><div className="mt-6"><ExampleTable title="Dutch property and investment examples" columns={["Asset", "Example", "Practical check"]} rows={page.propertyInvestmentExamples.map((row) => ({ Asset: row.asset, Example: row.example, "Practical check": row.practicalCheck }))} /></div></section>
            <section id="allowances" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Benefits" title="What Happens to Allowances?"><p>Allowances may stop or change after relocation. Eligibility and timing depend on personal circumstances, income, household, insurance and official records.</p></SectionIntro><VisualFigure visual={page.visuals.allowances} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.allowanceCards.map((card, index) => <FeatureCard key={card.title} title={card.title} body={card.body} iconIndex={index} />)}</div><div className="mt-6"><ExampleTable title="Allowance exit examples" columns={["Allowance", "Example inputs", "What to check", "Useful record"]} rows={page.allowanceExamples.map((row) => ({ Allowance: row.allowance, "Example inputs": row.exampleInputs, "What to check": row.whatToCheck, "Useful record": row.usefulRecord }))} /></div></section>
            <section id="healthcare" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Insurance" title="Health Insurance and Leaving the Netherlands"><p>Many expats must consider ending Dutch health insurance, relocation timing, coverage gaps and municipality records.</p></SectionIntro><VisualFigure visual={page.visuals.healthcare} /></div><div className="mt-6"><ExampleTable title="Healthcare exit scenarios" columns={["Scenario", "Timeline", "Practical question", "Records"]} rows={page.healthcareExamples.map((row) => ({ Scenario: row.scenario, Timeline: row.timeline, "Practical question": row.practicalQuestion, Records: row.records }))} /></div></section>
            <section id="remote-work" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Cross-border work" title="Remote Work and International Employment"><p>Modern work arrangements can create multi-country payroll situations, residency questions, treaty considerations and remote-work tax complexity.</p></SectionIntro><VisualFigure visual={page.visuals.remoteWork} /></div><div className="mt-6"><ExampleTable title="Remote-work exit scenarios" columns={["Pattern", "Complexity", "Practical move"]} rows={page.remoteWorkExamples.map((row) => ({ Pattern: row.pattern, Complexity: row.complexity, "Practical move": row.practicalMove }))} /></div></section>
            <section id="mistakes" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Avoidable mistakes" title="Common Tax Mistakes When Leaving"><p>Exit-year mistakes usually start with assumptions: taxes end instantly, allowances update automatically, pensions can wait or home-country rules apply everywhere.</p></SectionIntro><VisualFigure visual={page.visuals.mistakes} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.mistakeCards.map((card, index) => <FeatureCard key={card.title} title={card.title} body={card.body} iconIndex={index} />)}</div><div className="mt-6"><ExampleTable title="Mistake examples with practical consequences" columns={["Mistake", "Example", "Possible consequence", "Better record"]} rows={page.mistakeScenarioExamples.map((row) => ({ Mistake: row.mistake, Example: row.example, "Possible consequence": row.possibleConsequence, "Better record": row.betterRecord }))} /></div></section>
            <section id="advice" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Professional advice" title="When Professional Advice Is Worth Considering"><p>International relocation taxes can become complex quickly when multiple countries, foreign property, pensions, remote work, self-employment, investments or high compensation overlap.</p></SectionIntro><VisualFigure visual={page.visuals.advice} /></div><div className="mt-6"><BulletPanel title="Advice is especially worth considering when" items={page.adviceTriggers} /></div><div className="mt-6"><ExampleTable title="Advisor brief examples" columns={["Situation", "Numbers to bring", "Documents to bring"]} rows={page.advisorBriefExamples.map((row) => ({ Situation: row.situation, "Numbers to bring": row.numbersToBring, "Documents to bring": row.documentsToBring }))} /></div></section>
            <section id="questions" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Common questions" title="Questions Expats Often Ask"><p>These common questions help identify the missing fact: departure date, residency ties, income source, allowance status, pension record or workday location.</p></SectionIntro><VisualFigure visual={page.visuals.questions} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.expatQuestions.map((item, index) => <FeatureCard key={item.q} title={item.q} body={item.a} iconIndex={index} />)}</div><div className="mt-6"><ExampleTable title="Question examples with facts to gather" columns={["Question", "Example facts", "First check", "Useful record"]} rows={page.questionScenarioExamples.map((row) => ({ Question: row.question, "Example facts": row.exampleFacts, "First check": row.firstCheck, "Useful record": row.usefulRecord }))} /></div></section>
            <section id="related-tax-guides" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Internal guide hub" title="Related Expat Tax Guides"><p>Use these guides as a reading path from exit questions into specialist pages for expat taxes, double taxation, foreign income, the 30% ruling and arrival tax setup.</p></SectionIntro><VisualFigure visual={page.visuals.relatedGuides} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{page.relatedGuides.map((link, index) => <LinkCard key={link.href} item={link} iconIndex={index} />)}</div></section>
            <section id="services" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Professional help" title="Professional Services That May Help"><p>The right provider depends on whether your issue is final tax filing, international tax, relocation admin, immigration status, pensions or financial planning.</p></SectionIntro><VisualFigure visual={page.visuals.services} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{page.services.map((link, index) => <LinkCard key={link.href} item={link} iconIndex={index} />)}</div><div className="mt-6"><ExampleTable title="Which professional might help?" columns={["Provider", "Example case", "Useful for", "Documents"]} rows={page.serviceScenarioExamples.map((row) => ({ Provider: row.provider, "Example case": row.exampleCase, "Useful for": row.usefulFor, Documents: row.documents }))} /></div></section>
            {supportProviders?.items.length ? <section id="support-providers" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Provider discovery" title="Affiliates and Tax Providers That May Assist"><p>These provider cards are a discovery starting point for users who want help with final returns, M-forms, cross-border tax questions, 30% ruling changes, allowances or Dutch property after leaving. They are not endorsements or tax advice.</p></SectionIntro><AffiliateBlockView placement={supportProviders.placement} items={supportProviders.items} hidePlacementTitle /></div></section> : null}
            <section id="faq" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="FAQ" title="Frequently Asked Questions"><p>Use the FAQ for orientation before checking official sources, payroll records or professional advice for your personal situation.</p></SectionIntro><VisualFigure visual={page.visuals.faq} /></div><div className="mt-6 grid gap-4 md:grid-cols-2">{page.faq.map((item, index) => <FeatureCard key={item.q} title={item.q} body={item.a} iconIndex={index} />)}</div></section>
            <section id="sources" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Official sources" title="Official Sources"><p>{page.sourcesDisclaimer}</p></SectionIntro><VisualFigure visual={page.visuals.sources} /></div><div className="mt-6"><SourcesSection /></div></section>
            <section id="related-guides" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Related guides" title="Continue Through the Relocation and Tax Ecosystem"><p>This exit guide sits between international tax, foreign income, pensions, benefits and relocation admin. Use the related guides to continue without jumping into generic tax planning.</p></SectionIntro><VisualFigure visual={page.visuals.relocationEcosystem} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{page.relatedFooterGuides.map((link, index) => <LinkCard key={link.href} item={link} iconIndex={index} />)}</div></section>
            <section className={cn("relative isolate overflow-hidden rounded-[2rem] bg-slate-950 p-6 shadow-expatos-xl ring-1 ring-white/10 sm:p-8 lg:p-10")}><div className={cn("absolute inset-x-0 top-0 h-1.5", movingNlSignatureGradientClass)} aria-hidden /><div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-cyan-400/20 blur-3xl" aria-hidden /><div className="pointer-events-none absolute -bottom-28 left-1/4 h-72 w-72 rounded-full bg-emerald-300/10 blur-3xl" aria-hidden /><div className="relative space-y-6"><SectionIntro eyebrow="Explore next" title="Plan the Next Tax Question" tone="onDark"><p>Move from leaving-year awareness into double taxation, foreign income, expat tax foundations, the 30% ruling and relocation lifecycle guidance.</p></SectionIntro><VisualFigure visual={page.visuals.exploreNext} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{page.exploreNextCards.map((link, index) => <LinkCard key={link.href} item={link} iconIndex={index} tone="onDark" />)}</div></section>
          </div>
        </Container>
      </main>
    </>
  );
}
