export const TAXES_AFTER_MOVING_NETHERLANDS_PATH = "/netherlands/taxes/taxes-after-moving-netherlands/" as const;
export const TAXES_HUB_PATH = "/netherlands/taxes/" as const;

export type TaxesAfterMovingNetherlandsLink = {
  label: string;
  href: string;
  description?: string;
  status?: "live" | "comingSoon";
};

export const taxesAfterMovingNetherlandsPage = {
  slug: "taxes-after-moving-netherlands",
  path: TAXES_AFTER_MOVING_NETHERLANDS_PATH,
  publish: true,
  publishDate: "2026-08-02",
  seo: {
    title: "Taxes After Moving to the Netherlands | Expat Tax Starter Guide",
    description:
      "Learn what happens tax-wise after moving to the Netherlands, including tax residency, payroll tax, allowances, foreign income and key expat tax steps.",
    keywords: [
      "taxes after moving netherlands",
      "expat taxes netherlands",
      "moving to netherlands taxes",
      "dutch taxes expats",
      "tax guide netherlands expats",
      "first tax steps netherlands",
      "tax residency netherlands",
      "30 ruling netherlands",
      "payroll tax netherlands",
      "foreign income netherlands",
    ],
  },
  hero: {
    eyebrow: "Netherlands · Taxes · Expat onboarding",
    pageTitle: "Taxes After Moving to the Netherlands",
    subtitle:
      "Understand the most important tax concepts, registrations, deductions and benefits expats encounter after relocating to the Netherlands.",
    primaryCta: { label: "Understand Dutch Taxes", href: "#intro" },
    secondaryCta: { label: "Explore Expat Tax Guides", href: TAXES_HUB_PATH },
    chips: ["First tax steps", "Payroll tax", "Tax residency", "Allowances"],
    image: {
      src: "/images/heroes/netherlands-taxes-after-moving-hero-v1.png",
      alt: "Premium editorial image of a newly arrived expat calmly organizing relocation and tax onboarding documents in a Dutch city apartment.",
    },
  },
  visuals: {
    intro: {
      src: "/images/infographics/netherlands-taxes-after-moving-first-steps-premium-v6.png",
      alt: "Premium ExpatLife infographic showing first tax steps after moving to the Netherlands from registration to tax terminology.",
      caption: "Use the roadmap as a practical first-weeks sequence: registration, BSN, insurance, payroll, DigiD, allowances and tax terminology.",
    },
    snapshot: {
      src: "/images/infographics/netherlands-taxes-after-moving-snapshot-premium-v6.png",
      alt: "Premium ExpatLife snapshot infographic showing six tax questions after moving to the Netherlands.",
      caption: "The snapshot separates immediate admin from questions that depend on your residency, income, household and first-year records.",
    },
    firstSteps: {
      src: "/images/infographics/netherlands-taxes-after-moving-first-steps-premium-v6.png",
      alt: "Premium ExpatLife step infographic showing the first tax-related steps after arrival in the Netherlands.",
      caption: "These steps are interconnected: missing one can delay payroll, benefits, official access or later tax checks.",
    },
    residency: {
      src: "/images/infographics/netherlands-taxes-after-moving-residency-premium-v6.png",
      alt: "Premium ExpatLife residency compass infographic for Dutch tax residency facts.",
      caption: "Residency should be mapped with facts such as home base, family, work, timing and economic ties.",
    },
    payroll: {
      src: "/images/infographics/netherlands-taxes-after-moving-payroll-premium-v6.png",
      alt: "Premium ExpatLife infographic explaining payroll tax and the difference between gross salary and net salary.",
      caption: "The payroll waterfall shows why a EUR 70,000 gross offer is not the same as monthly take-home pay.",
    },
    ruling: {
      src: "/images/infographics/netherlands-taxes-after-moving-30-ruling-premium-v6.png",
      alt: "Premium ExpatLife infographic explaining the 30 percent ruling as a conditional expat tax facility.",
      caption: "The triage flow shows why recruitment, employer application, salary thresholds, timing and official approval all matter.",
    },
    foreignIncome: {
      src: "/images/infographics/netherlands-taxes-after-moving-foreign-income-premium-v6.png",
      alt: "Premium ExpatLife infographic mapping foreign income questions after moving to the Netherlands.",
      caption: "Use the inventory map to list each country, payer, date range, withholding record and income type before filing season.",
    },
    allowances: {
      src: "/images/infographics/netherlands-taxes-after-moving-allowances-premium-v6.png",
      alt: "Premium ExpatLife infographic showing Dutch allowances expats should know after moving.",
      caption: "The allowance matrix turns broad benefit names into the inputs you need to check: income, household, rent, childcare and records.",
    },
    healthcare: {
      src: "/images/infographics/netherlands-taxes-after-moving-healthcare-premium-v6.png",
      alt: "Premium ExpatLife infographic connecting Dutch health insurance and healthcare allowance.",
      caption: "The healthcare visual connects insurance requirements, indicative monthly premium ranges and possible healthcare allowance checks.",
    },
    taxReturn: {
      src: "/images/infographics/netherlands-taxes-after-moving-tax-return-premium-v6.png",
      alt: "Premium ExpatLife infographic showing common annual tax return triggers for expats.",
      caption: "The record builder shows which documents often explain a first Dutch tax year: payslips, move dates, allowances and foreign income.",
    },
    midYear: {
      src: "/images/infographics/netherlands-taxes-after-moving-mid-year-premium-v6.png",
      alt: "Premium ExpatLife timeline infographic for moving to the Netherlands during the tax year.",
      caption: "The timeline shows how a year can split into salary abroad, arrival evidence, Dutch payroll and filing-season records.",
    },
    remoteWork: {
      src: "/images/infographics/netherlands-taxes-after-moving-remote-work-premium-v6.png",
      alt: "Premium ExpatLife infographic showing remote work and foreign employer tax questions after moving.",
      caption: "The remote-work map highlights the facts to collect before assumptions: employer country, NL home base, workday calendar and social security.",
    },
    mistakes: {
      src: "/images/infographics/netherlands-taxes-after-moving-mistakes-premium-v6.png",
      alt: "Premium ExpatLife infographic showing common expat tax mistakes after relocating.",
      caption: "The mistake radar shows the first-year assumptions that most often create confusion before forms are even involved.",
    },
    lifeStage: {
      src: "/images/infographics/netherlands-taxes-after-moving-life-stage-premium-v6.png",
      alt: "Premium ExpatLife infographic showing how tax questions change by expat life stage.",
      caption: "Use the situation map to choose the right first checks for employees, couples, families, remote workers, freelancers and HSMs.",
    },
    questions: {
      src: "/images/infographics/netherlands-taxes-after-moving-questions-premium-v6.png",
      alt: "Premium ExpatLife infographic showing questions expats often ask about taxes after moving.",
      caption: "The question router turns broad worries into the missing facts and specialist guide paths that help next.",
    },
    relatedGuides: {
      src: "/images/infographics/netherlands-taxes-after-moving-related-guides-premium-v6.png",
      alt: "Premium ExpatLife infographic showing related expat tax guides after moving to the Netherlands.",
      caption: "The reading path connects onboarding into payroll, the 30% ruling, foreign income, double taxation and the main tax hub.",
    },
    relocationEcosystem: {
      src: "/images/infographics/netherlands-taxes-after-moving-relocation-ecosystem-premium-v6.png",
      alt: "Premium ExpatLife infographic showing how taxes after moving connects to relocation, healthcare, expat tax, foreign income and official source guides.",
      caption: "Use the ecosystem map to move from first-year tax setup into relocation, healthcare, salary, foreign-income and official-source guidance.",
    },
    services: {
      src: "/images/infographics/netherlands-taxes-after-moving-services-premium-v6.png",
      alt: "Premium ExpatLife infographic mapping professional services that may help after moving.",
      caption: "The service map helps match the issue to the provider: tax advisor, payroll specialist, relocation service, immigration lawyer or financial advisor.",
    },
    faq: {
      src: "/images/infographics/netherlands-taxes-after-moving-faq-premium-v6.png",
      alt: "Premium ExpatLife FAQ infographic for taxes after moving to the Netherlands.",
      caption: "The FAQ filter keeps each answer grounded in facts to verify, not generic promises about tax outcomes.",
    },
    sources: {
      src: "/images/infographics/netherlands-taxes-after-moving-sources-premium-v6.png",
      alt: "Premium ExpatLife infographic showing official Dutch tax and allowance sources.",
      caption: "The source checklist points users to the right official portals for tax, relocation, cross-border and allowance verification.",
    },
    exploreNext: {
      src: "/images/infographics/netherlands-taxes-after-moving-explore-next-premium-v6.png",
      alt: "Premium ExpatLife infographic showing next guides to read after taxes after moving to the Netherlands.",
      caption: "Use the next-step visual to choose the guide that fits your concrete question: salary, benefits, foreign income or relocation setup.",
    },
  },
  sectionNav: [
    { label: "Intro", href: "#intro" },
    { label: "First steps", href: "#first-steps" },
    { label: "Residency", href: "#residency" },
    { label: "Payroll", href: "#payroll" },
    { label: "30% ruling", href: "#ruling" },
    { label: "Foreign income", href: "#foreign-income" },
    { label: "Allowances", href: "#allowances" },
    { label: "Annual returns", href: "#annual-returns" },
    { label: "Mistakes", href: "#mistakes" },
    { label: "Guides", href: "#related-tax-guides" },
    { label: "FAQ", href: "#faq" },
  ],
  introPoints: [
    "After relocating to the Netherlands, many expats suddenly encounter Dutch payroll taxes, social contributions, healthcare insurance, allowances, annual tax returns and pension deductions.",
    "The Dutch system may feel very different from your home-country system because payroll, benefits, tax residency, health insurance and annual filing can interact.",
    "Understanding the basics early helps reduce confusion later and gives you a practical checklist for what to arrange, what to track and which questions need professional review.",
  ],
  snapshotCards: [
    { label: "BSN", value: "BSN registration is important" },
    { label: "Payroll", value: "Payroll tax usually starts immediately" },
    { label: "Residency", value: "Tax residency matters" },
    { label: "Foreign income", value: "Foreign income may become relevant" },
    { label: "Benefits", value: "Tax benefits may exist" },
    { label: "Returns", value: "Annual tax returns are common" },
  ],
  firstStepsCards: [
    { title: "Register at municipality", body: "Municipality registration normally starts the official Dutch admin chain and helps establish your local records." },
    { title: "Obtain BSN", body: "Your BSN is needed for employment, payroll, healthcare, many official services and tax correspondence." },
    { title: "Arrange health insurance", body: "Many residents need Dutch health insurance; timing and eligibility depend on your situation." },
    { title: "Start employment/payroll setup", body: "Your employer usually needs identity, address, BSN and payroll details before the first salary run." },
    { title: "Obtain DigiD", body: "DigiD gives access to many Dutch government and tax services, including allowance and tax portals." },
    { title: "Understand allowances", body: "Healthcare, rent and childcare support can depend on income, household, rent level and timing." },
    { title: "Learn basic tax terminology", body: "Gross salary, net salary, loonheffing, annual return, tax residency and 30% ruling are useful starter terms." },
  ],
  arrivalTimingExamples: [
    { step: "Municipality registration", typicalTiming: "Often targeted within 5 days if staying over 4 months", example: "Arrive 3 August, book gemeente appointment for 6 August", recordToKeep: "Appointment confirmation, rental/address document, registration proof" },
    { step: "BSN and payroll", typicalTiming: "Before or soon after first salary run", example: "Job starts 15 August; employer asks for BSN before September payroll", recordToKeep: "BSN letter, employment contract, first payslip" },
    { step: "Health insurance", typicalTiming: "Often within 4 months if Dutch basic insurance is required", example: "Arrive 1 September, policy arranged by November; premium EUR 145/month", recordToKeep: "Policy document, premium invoice, allowance application status" },
    { step: "DigiD and allowances", typicalTiming: "After BSN and address setup", example: "Apply for DigiD in week 2; check healthcare allowance once income estimate is known", recordToKeep: "DigiD activation, Toeslagen messages, income estimate" },
  ],
  residencyFactors: [
    "Long-term stay plans and where your main home is located.",
    "Where you work, where your employer is based and where salary is paid.",
    "Family location, household ties and where daily life is centered.",
    "Economic ties such as business activity, bank accounts, clients, property or recurring income.",
    "Arrival date, departure plans and whether the tax year is split between countries.",
  ],
  residencyScenarioExamples: [
    { profile: "Permanent job move", facts: "Arrives 1 February, 11-month Dutch lease, Dutch employer, partner moves in April", practicalQuestion: "From when do Dutch residency and reporting questions become relevant?", usefulRecords: "Lease, BRP date, employment start date, partner arrival date" },
    { profile: "Trial move", facts: "Arrives 1 June, 6-month contract, keeps home abroad and returns monthly", practicalQuestion: "Which ties point to the Netherlands and which remain abroad?", usefulRecords: "Travel calendar, housing contracts, payroll records, family location" },
    { profile: "Remote employee", facts: "Lives in Utrecht from 1 September, foreign employer pays EUR 6,500/month", practicalQuestion: "How do work location, payroll and residence facts interact?", usefulRecords: "Employer letter, payslips, workday log, residence registration" },
  ],
  payrollTopics: [
    { label: "Payroll tax Netherlands", href: "/netherlands/taxes/payroll-tax-netherlands/", description: "Learn how Dutch payroll withholding appears on salary and payslips." },
    { label: "Gross vs Net Salary", href: "/netherlands/taxes/gross-vs-net-salary/", description: "Understand why contract salary and take-home pay differ." },
    { label: "Net Salary in the Netherlands", href: "/netherlands/taxes/net-salary-netherlands/", description: "Estimate the salary concepts behind monthly net pay.", status: "comingSoon" },
    { label: "Holiday Allowance", href: "/netherlands/jobs/holiday-allowance-netherlands/", description: "Understand the Dutch holiday allowance concept.", status: "comingSoon" },
    { label: "Bonus Tax Netherlands", href: "/netherlands/taxes/bonus-tax-netherlands/", description: "Learn why bonuses can have different payroll withholding." },
  ] satisfies TaxesAfterMovingNetherlandsLink[],
  payrollExampleRows: [
    { profile: "Starter employee", grossSalary: "EUR 42,000/year", monthlyGross: "EUR 3,500", likelyPayslipQuestion: "Why is take-home lower than EUR 3,500?", whatToCompare: "Payroll tax, tax credits, pension, holiday allowance treatment" },
    { profile: "Highly skilled migrant", grossSalary: "EUR 72,000/year", monthlyGross: "EUR 6,000", likelyPayslipQuestion: "Does the 30% ruling apply from the first payslip?", whatToCompare: "Employer application, approval date, taxable salary, payroll adjustment" },
    { profile: "Bonus month", grossSalary: "EUR 60,000 + EUR 8,000 bonus", monthlyGross: "EUR 5,000 regular month", likelyPayslipQuestion: "Why does the bonus month show high withholding?", whatToCompare: "Special-rate withholding, annual reconciliation, bonus tax guide" },
    { profile: "Partner starts later", grossSalary: "EUR 55,000 + partner EUR 28,000 from October", monthlyGross: "EUR 4,583 before partner income", likelyPayslipQuestion: "Do household changes affect allowances?", whatToCompare: "Household income estimate, allowance updates, tax return records" },
  ],
  rulingPoints: [
    "The 30% ruling may apply to some highly skilled migrants recruited from abroad.",
    "It can affect taxable salary, net income and expat compensation, but it is not automatic.",
    "Eligibility depends on conditions, employer involvement, salary thresholds, timing and official approval.",
  ],
  rulingScenarioExamples: [
    { scenario: "Offer before relocation", figures: "EUR 78,000 gross salary; employer applies after start date", usefulQuestion: "When, if ever, does payroll reflect approval?", records: "Offer, employment contract, application date, decision letter" },
    { scenario: "Salary threshold concern", figures: "EUR 52,000 salary with age/education questions", usefulQuestion: "Which threshold and exception rules apply for the tax year?", records: "Diploma, age, contract, employer ruling correspondence" },
    { scenario: "Late payroll adjustment", figures: "First 2 payslips without ruling; later approval from tax authority", usefulQuestion: "How does employer correct payroll after approval?", records: "First payslips, approval decision, corrected payslip" },
  ],
  foreignIncomeExamples: [
    { profile: "Foreign salary overlaps with move", example: "EUR 70,000 contract; 5 months abroad and 7 months in NL", question: "Which workdays and payroll periods need review?" },
    { profile: "Rental home abroad", example: "EUR 1,250 monthly rent from old apartment", question: "How should foreign property and local tax records be organized?" },
    { profile: "Foreign investments", example: "EUR 45,000 brokerage account plus dividends", question: "Which statements, withholding and year-end balances are relevant?" },
    { profile: "Remote work", example: "Foreign employer, 3 days from Amsterdam, 2 days abroad", question: "Which tax, payroll and social-security facts need checking?" },
  ],
  allowanceCards: [
    { title: "Healthcare allowance", body: "A benefit that may help with Dutch health insurance costs when income and other conditions are met." },
    { title: "Rent allowance", body: "Housing support that depends on rent, income, household and whether the home meets official conditions." },
    { title: "Childcare allowance", body: "Support for registered childcare that depends on work, childcare use, income and family circumstances." },
    { title: "Child benefit", body: "Family support with its own rules and administration; do not assume it follows tax-return logic." },
  ],
  allowanceScenarioExamples: [
    { allowance: "Healthcare allowance", exampleInputs: "Single person, estimated income EUR 34,000, premium EUR 145/month", whatToCheck: "Income threshold, partner status, Dutch insurance start date", usefulRecord: "Policy, income estimate, Toeslagen decision" },
    { allowance: "Rent allowance", exampleInputs: "Rent EUR 875/month, service costs separate, registered address", whatToCheck: "Rent limit, household income, property conditions", usefulRecord: "Rental contract, rent breakdown, BRP registration" },
    { allowance: "Childcare allowance", exampleInputs: "2 working parents, childcare EUR 1,200/month, registered provider", whatToCheck: "Work requirement, childcare hours, hourly rate cap", usefulRecord: "Childcare contract, invoices, work contracts" },
    { allowance: "Child benefit", exampleInputs: "Family arrives with 2 children aged 4 and 8", whatToCheck: "Residence, child registration and relevant authority rules", usefulRecord: "BRP extracts, school/child records, official letters" },
  ],
  healthcareCostExamples: [
    { scenario: "Single employee", monthlyPremium: "EUR 140-160/month", allowanceQuestion: "Is healthcare allowance possible based on estimated income?", records: "Policy, income estimate, BSN/DigiD access" },
    { scenario: "Couple both working", monthlyPremium: "EUR 280-320/month combined", allowanceQuestion: "Does combined household income change eligibility?", records: "Both policies, both payslips, partner income estimate" },
    { scenario: "Family arrival", monthlyPremium: "Adults pay premiums; children are usually insured differently", allowanceQuestion: "Which family members need separate policies or benefit checks?", records: "Family registration, insurer confirmation, official messages" },
  ],
  taxReturnReasons: [
    "Salary adjustments, multiple employers or payroll corrections.",
    "Allowances, benefits or income changes during the year.",
    "Foreign income, overseas assets or cross-border work questions.",
    "Moving mid-year, leaving mid-year or splitting the year between countries.",
    "Potential refunds, additional assessments or official filing requests.",
  ],
  annualReturnScenarioExamples: [
    { trigger: "Moved mid-year", exampleFigure: "Arrived 1 July; EUR 32,000 salary abroad and EUR 34,000 Dutch salary", whyItMatters: "Two salary periods and move timing may need explanation", records: "Foreign payslips, Dutch jaaropgaaf, BRP date" },
    { trigger: "Allowance income changed", exampleFigure: "Estimated EUR 34,000 income became EUR 41,000 after bonus", whyItMatters: "Allowance entitlement may need recalculation", records: "Bonus payslip, Toeslagen messages, annual income statement" },
    { trigger: "Foreign property retained", exampleFigure: "Apartment abroad worth EUR 220,000 with EUR 1,100 monthly rent", whyItMatters: "Foreign property and rental records may be relevant", records: "Valuation, rental ledger, local tax statement" },
    { trigger: "Multiple employers", exampleFigure: "Dutch employer A paid EUR 28,000; employer B paid EUR 18,000", whyItMatters: "Payroll withholding may not match final annual position", records: "Both annual statements, start/end dates" },
  ],
  midYearExamples: [
    { timeline: "Arrived 1 March", example: "2 months salary abroad, 10 months Dutch payroll; EUR 9,000 abroad and EUR 45,000 in NL", practicalRecord: "Move date, payslips from both countries, employment contract" },
    { timeline: "Arrived 1 July", example: "Half year abroad, half year Netherlands; EUR 30,000 foreign salary and EUR 32,000 Dutch salary", practicalRecord: "BRP registration, workday calendar, foreign income records" },
    { timeline: "Moved with partner later", example: "One partner arrives in April, the other in September; partner income starts at EUR 2,800/month", practicalRecord: "Household timeline, partner income, allowance dates" },
  ],
  remoteWorkScenarios: [
    { pattern: "Foreign employer after relocation", complexity: "EUR 6,500/month paid by foreign employer while living in Rotterdam; payroll, tax residency and employer compliance can overlap.", practicalMove: "Keep employer approval, contract, payslips and workday location records." },
    { pattern: "Hybrid international work", complexity: "3 days/week from the Netherlands and 2 days/week abroad; physical workdays can matter when several countries are involved.", practicalMove: "Track days worked in each country and travel dates." },
    { pattern: "Digital nomad transition", complexity: "90 days in NL, 60 days in another EU country, then Dutch lease; visa, tax, residence and social-security questions can diverge.", practicalMove: "Do not rely on tax assumptions from a previous country." },
  ],
  remoteWorkdayExamples: [
    { pattern: "Mostly Netherlands", workdaySplit: "180 NL workdays / 40 foreign workdays", likelyQuestion: "Does foreign employer need Dutch payroll or local advice?", records: "Workday calendar, travel bookings, employer approval" },
    { pattern: "Balanced cross-border", workdaySplit: "110 NL workdays / 105 foreign workdays", likelyQuestion: "Which country has taxing or social-security rights for which days?", records: "Daily location log, payslips, assignment letters" },
    { pattern: "Short arrival year", workdaySplit: "75 NL workdays after 1 September arrival", likelyQuestion: "How should the move year be documented?", records: "Arrival date, BRP registration, foreign employer payslips" },
  ],
  mistakeCards: [
    { title: "Ignoring foreign income questions", body: "Overseas salary, property, dividends or pensions may still need review after moving." },
    { title: "Missing allowance applications", body: "Benefits are not always automatic and eligibility can depend on timing." },
    { title: "Confusing gross vs net salary", body: "A Dutch offer amount is not the same as monthly take-home pay." },
    { title: "Not understanding tax residency", body: "Residency is usually factual and should not be reduced to nationality or visa status." },
    { title: "Delaying DigiD setup", body: "Without DigiD, official tax and allowance admin can become harder." },
    { title: "Assuming home-country rules still apply", body: "Dutch payroll, benefits and returns may follow different logic." },
    { title: "Ignoring annual tax obligations", body: "Annual filing may become relevant because of salary, move timing, allowances or foreign income." },
    { title: "Misunderstanding the 30% ruling", body: "The ruling is conditional; it is not a universal expat discount." },
  ],
  lifeStageCards: [
    { title: "Single employee", body: "Focus on BSN, payroll, net salary, DigiD, health insurance and annual filing basics." },
    { title: "Couple relocating", body: "Consider partner income, timing, household registration, allowances and foreign-income links." },
    { title: "Family with children", body: "Childcare allowance, child benefit, school timing and partner work status may matter." },
    { title: "Remote worker", body: "Foreign employer, workday location, payroll and social-security questions can become complex." },
    { title: "Freelancer", body: "Business registration, VAT, invoicing, deductions and income records become central." },
    { title: "Homeowner", body: "Buying, mortgage, property tax and foreign-property questions may enter the tax picture." },
    { title: "Highly skilled migrant", body: "The 30% ruling, salary thresholds, employer application and relocation benefits are key topics." },
  ],
  lifeStageScenarioExamples: [
    { lifeStage: "Single employee", exampleNumbers: "EUR 48,000 salary, EUR 150/month insurance, first Dutch payslip in month 1", firstChecks: "BSN, payroll, DigiD, health insurance, net salary" },
    { lifeStage: "Couple relocating", exampleNumbers: "Partner A EUR 68,000 salary; partner B starts EUR 3,200/month in October", firstChecks: "Household income, allowances, partner registration, annual return records" },
    { lifeStage: "Family with children", exampleNumbers: "Childcare invoice EUR 1,350/month; 2 children registered after arrival", firstChecks: "Childcare allowance, child benefit, school/child records, partner work status" },
    { lifeStage: "Freelancer", exampleNumbers: "EUR 85,000 projected revenue; 6 foreign clients and 3 Dutch clients", firstChecks: "Business registration, VAT, invoicing, deductions, foreign-client records" },
    { lifeStage: "Homeowner", exampleNumbers: "Foreign property worth EUR 240,000 plus Dutch rental home EUR 1,750/month", firstChecks: "Foreign property records, housing costs, future mortgage/property-tax links" },
  ],
  expatQuestions: [
    { q: "What taxes do I pay after moving?", a: "Most employees first notice payroll withholding, income tax concepts, social contributions and possible pension deductions." },
    { q: "Do I become a Dutch tax resident immediately?", a: "Residency depends on facts such as home, work, family, timing and economic ties. Avoid one-document shortcuts." },
    { q: "What happens to foreign income?", a: "Foreign income can still be relevant after relocation, especially salary, property, investments, pensions and remote work." },
    { q: "What is the 30% ruling?", a: "A conditional facility for some qualifying employees recruited from abroad; eligibility is not guaranteed." },
    { q: "Do I need to file taxes?", a: "Many expats eventually file annual returns because of payroll, move timing, allowances, foreign income or official requests." },
    { q: "What allowances exist?", a: "Healthcare, rent, childcare and child-related benefits may be relevant depending on income and household facts." },
    { q: "Why is my net salary lower?", a: "Payroll tax, social contributions, pension deductions and benefit-related calculations can reduce take-home pay." },
    { q: "What if I moved mid-year?", a: "Build a timeline of arrival, workdays, salary periods, registration and foreign income records." },
  ],
  relatedGuides: [
    { label: "Expat Taxes Netherlands", href: "/netherlands/taxes/expat-taxes-netherlands/", description: "The broader expat tax foundation for the Netherlands." },
    { label: "30% Ruling", href: "/netherlands/taxes/30-percent-ruling/", description: "Understand the expat tax facility and eligibility context." },
    { label: "Payroll Tax Netherlands", href: "/netherlands/taxes/payroll-tax-netherlands/", description: "Learn how payroll tax and withholding affect salary." },
    { label: "Foreign Income Netherlands", href: "/netherlands/taxes/foreign-income-netherlands/", description: "Understand overseas income, remote work and cross-border reporting awareness." },
    { label: "Double Taxation Netherlands", href: "/netherlands/taxes/double-taxation-netherlands/", description: "Learn treaty and double-taxation concepts for expats." },
  ] satisfies TaxesAfterMovingNetherlandsLink[],
  services: [
    { label: "Expat tax advisors", href: "/netherlands/services/expat-tax-services/", description: "Professional support for Dutch and cross-border expat tax questions." },
    { label: "Payroll specialists", href: "/netherlands/services/payroll-services/", description: "Help with payroll setup, salary deductions and employer admin." },
    { label: "Relocation services", href: "/netherlands/services/relocation-services/", description: "Support for practical arrival steps such as registration and settling in." },
    { label: "Immigration lawyers", href: "/netherlands/services/immigration-lawyers/", description: "Help when tax questions overlap with work and residence status." },
    { label: "Financial advisors", href: "/netherlands/services/financial-advisors/", description: "Planning support for savings, pension, investments and long-term finances." },
  ] satisfies TaxesAfterMovingNetherlandsLink[],
  faq: [
    { q: "What taxes do expats pay after moving?", a: "Employees usually encounter Dutch payroll withholding, income tax concepts, social contributions and sometimes pension deductions. Other taxes or filings depend on the person's situation." },
    { q: "What is Dutch tax residency?", a: "Dutch tax residency is a facts-based concept that can consider where you live, work, keep family ties and center your economic life. It should not be oversimplified." },
    { q: "What happens to foreign income?", a: "Foreign income such as salary, rental income, investments, pensions or remote work may create Dutch tax considerations after moving. The treatment depends on facts and sometimes treaty rules." },
    { q: "What is the 30% ruling?", a: "The 30% ruling is a conditional Dutch facility for some qualifying employees recruited from abroad. It may affect taxable salary and net income, but eligibility is not guaranteed." },
    { q: "Do expats file annual taxes?", a: "Many expats eventually file annual Dutch tax returns because of salary adjustments, allowances, moving mid-year, foreign income or official filing requests." },
    { q: "What allowances exist?", a: "Relevant allowances can include healthcare allowance, rent allowance, childcare allowance and child benefit, depending on income, household, rent, childcare and other conditions." },
    { q: "Why is my net salary lower?", a: "Net salary is lower than gross salary because payroll tax, social contributions, pension deductions and other payroll items may be withheld before payment." },
    { q: "What if I moved mid-year?", a: "Moving mid-year can create split-year timing, foreign income, payroll and partial-residency questions. Keep clear records of arrival date, workdays, payslips and registration." },
  ],
  officialSources: [
    { label: "Belastingdienst", href: "https://www.belastingdienst.nl/", description: "Official Dutch Tax Administration information on taxes, returns and tax matters." },
    { label: "Government.nl", href: "https://www.government.nl/", description: "Official government information about living and working in the Netherlands." },
    { label: "NederlandWereldwijd", href: "https://www.nederlandwereldwijd.nl/", description: "Official information for Dutch and international cross-border situations." },
    { label: "Toeslagen", href: "https://www.toeslagen.nl/", description: "Official portal for Dutch allowances and benefit administration." },
    { label: "Business.gov.nl", href: "https://business.gov.nl/", description: "Official information for entrepreneurs, freelancers and businesses in the Netherlands." },
  ],
  sourcesDisclaimer:
    "Tax residency, reporting obligations and allowances depend on personal circumstances and may change over time. Use official sources and professional advice for personal decisions.",
  relatedFooterGuides: [
    { label: "Netherlands Taxes Hub", href: "/netherlands/taxes/", description: "Start with the main Dutch tax hub." },
    { label: "Expat Taxes Netherlands", href: "/netherlands/taxes/expat-taxes-netherlands/", description: "Understand the broader tax system for expats." },
    { label: "30% Ruling", href: "/netherlands/taxes/30-percent-ruling/", description: "Review the expat tax facility." },
    { label: "Foreign Income Netherlands", href: "/netherlands/taxes/foreign-income-netherlands/", description: "Handle cross-border income questions." },
    { label: "Double Taxation Netherlands", href: "/netherlands/taxes/double-taxation-netherlands/", description: "Learn treaty and double-taxation concepts." },
    { label: "Moving to the Netherlands", href: "/netherlands/moving-to-the-netherlands/", description: "Connect tax onboarding with relocation planning." },
    { label: "Healthcare in the Netherlands", href: "/netherlands/healthcare/", description: "Understand healthcare after arrival." },
  ] satisfies TaxesAfterMovingNetherlandsLink[],
  exploreNextCards: [
    { label: "Expat Taxes", href: "/netherlands/taxes/expat-taxes-netherlands/", description: "Build your full Dutch tax foundation." },
    { label: "30% Ruling", href: "/netherlands/taxes/30-percent-ruling/", description: "Check the expat facility context." },
    { label: "Healthcare Allowance", href: "/netherlands/taxes/healthcare-allowance-netherlands/", description: "Learn about healthcare benefit eligibility.", status: "live" },
    { label: "Foreign Income", href: "/netherlands/taxes/foreign-income-netherlands/", description: "Review overseas income and remote work." },
    { label: "Moving to the Netherlands", href: "/netherlands/moving-to-the-netherlands/", description: "Continue relocation onboarding." },
  ] satisfies TaxesAfterMovingNetherlandsLink[],
};
