import { Children, type ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Banknote, BriefcaseBusiness, Building2, CheckCircle2, ClipboardCheck, FileText, Globe2, HeartPulse, Home, Landmark, Laptop, ReceiptText, Scale, ShieldCheck, WalletCards } from "lucide-react";
import { BreadcrumbJsonLd } from "@/components/content/breadcrumb-jsonld";
import { Container } from "@/components/ui/container";
import { cn } from "@/lib/cn";
import { activeBrightnessPress, transitionInteractive } from "@/lib/ui/interaction";
import { siteGuideColumnPadYClass, siteHeroFramedShellClass, siteHeroGlowPrimaryClass, siteHeroGlowSecondaryClass, siteHeroTopAccentClass, sitePageCanvasClass } from "@/lib/ui/site-shell-identity";
import { movingNlCardMicroLiftClass, movingNlSectionH2Class, movingNlSectionH2OnDarkClass, movingNlSignatureGradientClass } from "@/lib/ui/moving-nl-pillar-identity";
import { citiesFunnelHeroFigureClassName, CITIES_FUNNEL_INFO_CHIP, CITIES_FUNNEL_SECTION_SCROLL_MARGIN, CITIES_FUNNEL_SOFT_COPILOT_SURFACE } from "@/src/components/cities/shared/citiesFunnelPageUi";
import { taxesAfterMovingNetherlandsPage as page, type TaxesAfterMovingNetherlandsLink } from "./taxesAfterMovingNetherlandsPageModel";

const sectionClass = cn(CITIES_FUNNEL_SECTION_SCROLL_MARGIN, CITIES_FUNNEL_SOFT_COPILOT_SURFACE, "relative isolate overflow-hidden p-6 shadow-card ring-1 ring-slate-900/[0.04] before:pointer-events-none before:absolute before:inset-x-0 before:top-0 before:h-1 before:bg-gradient-to-r before:from-cyan-400/70 before:via-brand/80 before:to-emerald-300/70 after:pointer-events-none after:absolute after:-right-28 after:-top-28 after:h-56 after:w-56 after:rounded-full after:bg-cyan-200/15 after:blur-3xl sm:p-8 lg:p-10");
const sectionStackClass = "mt-8 space-y-6 sm:space-y-8 md:space-y-9";
const mutedCardClass = cn(CITIES_FUNNEL_SOFT_COPILOT_SURFACE, "relative overflow-hidden bg-white/90 p-5 shadow-sm ring-1 ring-slate-900/[0.04]", movingNlCardMicroLiftClass);
const icons = [Globe2, Landmark, Home, Laptop, ReceiptText, BriefcaseBusiness, Banknote, Scale, FileText, WalletCards, Building2, ClipboardCheck, ShieldCheck, HeartPulse] as const;
const primaryCtaClass = cn("inline-flex min-h-[44px] items-center justify-center gap-2 rounded-xl border border-brand-strong/25 bg-brand px-5 py-2.5 text-sm font-semibold text-white shadow-card hover:bg-brand-strong focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2 focus-visible:ring-offset-canvas", transitionInteractive, activeBrightnessPress);
const secondaryCtaClass = cn("inline-flex min-h-[44px] items-center justify-center gap-2 rounded-xl border border-border bg-surface-raised px-5 py-2.5 text-sm font-semibold text-foreground shadow-card hover:border-border-strong hover:bg-surface-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2 focus-visible:ring-offset-canvas", transitionInteractive, activeBrightnessPress);

function SectionIntro({ eyebrow, title, children, tone = "default", fullWidth = false }: { eyebrow?: string; title: string; children?: ReactNode; tone?: "default" | "onDark"; fullWidth?: boolean }) {
  const onDark = tone === "onDark";
  const useColumnLayout = fullWidth && Children.count(children) > 1;
  return <div className={cn(fullWidth ? "w-full max-w-none" : "max-w-3xl")}>{eyebrow ? <p className={cn("text-xs font-bold uppercase tracking-[0.14em]", onDark ? "text-cyan-200" : "text-brand-strong")}>{eyebrow}</p> : null}<h2 className={cn(onDark ? movingNlSectionH2OnDarkClass : movingNlSectionH2Class, eyebrow ? "mt-2" : undefined)}>{title}</h2>{children ? <div className={cn("mt-3 w-full space-y-3 text-base leading-relaxed", useColumnLayout && "max-w-none lg:columns-2 lg:gap-x-10 [&>p]:break-inside-avoid", onDark ? "text-slate-300" : "text-foreground-muted")}>{children}</div> : null}</div>;
}

function VisualFigure({ visual }: { visual: (typeof page.visuals)[keyof typeof page.visuals] }) {
  return <figure className={cn("relative isolate overflow-hidden rounded-[2rem] border border-slate-200/90 bg-white/95 shadow-expatos-xl ring-1 ring-slate-900/[0.05]", movingNlCardMicroLiftClass)}><div className={cn("h-1.5", movingNlSignatureGradientClass)} aria-hidden /><div className="pointer-events-none absolute -right-20 -top-20 h-44 w-44 rounded-full bg-cyan-200/25 blur-3xl" aria-hidden /><div className="relative aspect-[4/3] bg-gradient-to-br from-slate-50 via-white to-copilot-bg-soft p-2 sm:p-3"><Image src={visual.src} alt={visual.alt} fill sizes="(min-width: 1024px) 900px, 100vw" className="object-contain p-2 sm:p-3 drop-shadow-sm" /></div><figcaption className="border-t border-slate-200/80 bg-slate-50/90 px-4 py-3 text-sm leading-relaxed text-foreground-muted sm:px-5">{visual.caption}</figcaption></figure>;
}

function HeroImage() {
  return <figure className={citiesFunnelHeroFigureClassName()}><div className={cn("absolute inset-x-0 top-0 z-10 h-1.5", movingNlSignatureGradientClass)} aria-hidden /><Image src={page.hero.image.src} alt={page.hero.image.alt} width={1600} height={900} priority sizes="(min-width: 1024px) 42vw, 100vw" className="h-full w-full object-cover" /><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-slate-950/24 via-transparent to-white/10" aria-hidden /><div className="pointer-events-none absolute inset-0 ring-1 ring-inset ring-white/35" aria-hidden /></figure>;
}

function HeroSignalStrip() {
  return <div className="relative mt-5 grid gap-3 overflow-hidden rounded-[1.75rem] border border-slate-200/80 bg-white/82 p-3 shadow-card ring-1 ring-slate-900/[0.03] backdrop-blur-xl sm:grid-cols-2 lg:grid-cols-4"><div className={cn("absolute inset-x-0 top-0 h-1", movingNlSignatureGradientClass)} aria-hidden />{page.snapshotCards.slice(0, 4).map((card, index) => <StatCard key={card.label} label={card.label} value={card.value} iconIndex={index} />)}</div>;
}

function StatCard({ label, value, iconIndex }: { label: string; value: string; iconIndex: number }) {
  const Icon = icons[iconIndex % icons.length];
  return <article className={cn(mutedCardClass, "min-h-full")}><div className={cn("absolute inset-x-0 top-0 h-1.5 rounded-t-2xl", movingNlSignatureGradientClass)} aria-hidden /><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong shadow-sm ring-1 ring-copilot-primary/10"><Icon className="h-5 w-5" aria-hidden /></span><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-foreground-muted">{label}</p><p className="mt-1 text-base font-bold leading-snug text-foreground">{value}</p></div></div></article>;
}

function FeatureCard({ title, body, iconIndex = 0 }: { title: string; body: string; iconIndex?: number }) {
  const Icon = icons[iconIndex % icons.length];
  return <article className={cn(mutedCardClass, "min-h-full")}><div className={cn("absolute inset-x-0 top-0 h-1 rounded-t-2xl", movingNlSignatureGradientClass)} aria-hidden /><div className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong shadow-sm ring-1 ring-copilot-primary/10"><Icon className="h-5 w-5" aria-hidden /></span><div><h3 className="text-base font-bold tracking-tight text-foreground">{title}</h3><p className="mt-2 text-sm leading-relaxed text-foreground-muted">{body}</p></div></div></article>;
}

function LinkCard({ item, iconIndex = 0, tone = "default" }: { item: TaxesAfterMovingNetherlandsLink; iconIndex?: number; tone?: "default" | "onDark" }) {
  const Icon = icons[iconIndex % icons.length];
  const isLive = item.status !== "comingSoon";
  const onDark = tone === "onDark";
  const shell = onDark ? "relative overflow-hidden rounded-2xl border border-white/10 bg-white/10 p-5 shadow-sm ring-1 ring-white/10" : cn(CITIES_FUNNEL_SOFT_COPILOT_SURFACE, "relative overflow-hidden p-5", movingNlCardMicroLiftClass);
  const body = <><div className={cn("absolute inset-x-0 top-0 h-1.5 rounded-t-2xl", isLive ? movingNlSignatureGradientClass : onDark ? "bg-white/20" : "bg-slate-200")} aria-hidden /><div className="flex gap-3"><span className={cn("flex h-10 w-10 shrink-0 items-center justify-center rounded-xl shadow-sm ring-1", onDark ? "bg-white/10 text-cyan-100 ring-white/15" : isLive ? "bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong ring-copilot-primary/10" : "bg-slate-100 text-slate-500 ring-slate-200")}><Icon className="h-5 w-5" aria-hidden /></span><span className="min-w-0"><span className={cn("text-sm font-bold", onDark ? "text-white" : "text-foreground")}>{item.label}</span>{!isLive ? <span className={cn("ml-2 rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-[0.1em]", onDark ? "bg-white/10 text-slate-300 ring-1 ring-white/10" : "bg-slate-100 text-slate-500")}>Coming soon</span> : null}{item.description ? <span className={cn("mt-2 block text-sm leading-relaxed", onDark ? "text-slate-300" : "text-foreground-muted")}>{item.description}</span> : null}</span></div>{isLive ? <span className={cn("mt-4 inline-flex items-center gap-1 text-xs font-semibold", onDark ? "text-cyan-200" : "text-link group-hover:text-link-hover")}>Open <ArrowRight className="h-3.5 w-3.5" aria-hidden /></span> : null}</>;
  if (!isLive) return <article className={cn(shell, "opacity-90")}>{body}</article>;
  return <Link href={item.href} className={cn(shell, "group block focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2", onDark ? "focus-visible:ring-offset-slate-950" : "focus-visible:ring-offset-canvas", transitionInteractive, activeBrightnessPress)}>{body}</Link>;
}

function BulletPanel({ title, items }: { title: string; items: readonly string[] }) {
  return <aside className={cn("relative overflow-hidden rounded-3xl border border-slate-200/90 bg-white/95 p-5 shadow-sm ring-1 ring-slate-900/[0.04]", movingNlCardMicroLiftClass)}><div className={cn("absolute inset-x-0 top-0 h-1 rounded-t-3xl", movingNlSignatureGradientClass)} aria-hidden /><h3 className="text-base font-bold tracking-tight text-foreground">{title}</h3><ul className="mt-4 grid gap-3">{items.map((item) => <li key={item} className="flex gap-3 text-sm leading-relaxed text-foreground-muted"><span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-copilot-bg-soft text-brand-strong ring-1 ring-copilot-primary/10"><CheckCircle2 className="h-3.5 w-3.5" aria-hidden /></span><span>{item}</span></li>)}</ul></aside>;
}

function ExampleTable({ title, columns, rows }: { title: string; columns: readonly string[]; rows: readonly Record<string, string>[] }) {
  return <div className={cn("relative overflow-hidden rounded-3xl border border-slate-200/90 bg-white/95 shadow-sm ring-1 ring-slate-900/[0.04]", movingNlCardMicroLiftClass)}><div className={cn("absolute inset-x-0 top-0 h-1", movingNlSignatureGradientClass)} aria-hidden /><div className="border-b border-slate-200/80 px-5 py-4"><h3 className="text-base font-bold tracking-tight text-foreground">{title}</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-slate-200/80 bg-slate-50/80">{columns.map((column) => <th key={column} scope="col" className="px-4 py-3 font-bold text-foreground">{column}</th>)}</tr></thead><tbody>{rows.map((row, rowIndex) => <tr key={`${title}-${rowIndex}`} className="border-b border-slate-100 last:border-0">{columns.map((column) => <td key={column} className="px-4 py-3 leading-relaxed text-foreground-muted">{row[column]}</td>)}</tr>)}</tbody></table></div></div>;
}

function SourcesSection() {
  return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{page.officialSources.map((source) => <a key={source.href} href={source.href} className={cn("group relative block overflow-hidden rounded-2xl border border-slate-200/90 bg-white/95 p-5 shadow-sm ring-1 ring-slate-900/[0.04] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2 focus-visible:ring-offset-canvas", movingNlCardMicroLiftClass, transitionInteractive, activeBrightnessPress)} target="_blank" rel="noreferrer"><div className={cn("absolute inset-x-0 top-0 h-1 rounded-t-2xl", movingNlSignatureGradientClass)} aria-hidden /><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-copilot-bg-soft to-white text-brand-strong shadow-sm ring-1 ring-copilot-primary/10"><ShieldCheck className="h-5 w-5" aria-hidden /></span><span><span className="text-sm font-bold text-foreground">{source.label}</span><span className="mt-2 block text-sm leading-relaxed text-foreground-muted">{source.description}</span><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-link group-hover:text-link-hover">Open official source <ArrowRight className="h-3.5 w-3.5" aria-hidden /></span></span></div></a>)}</div>;
}

const crumbs = [{ name: "Home", item: "/" }, { name: "Netherlands", item: "/netherlands/" }, { name: "Taxes", item: "/netherlands/taxes/" }, { name: page.hero.pageTitle, item: page.path }];

export function TaxesAfterMovingNetherlandsView() {
  return (
    <>
      <BreadcrumbJsonLd crumbs={crumbs} />
      <main className={sitePageCanvasClass}>
        <Container className={cn("w-full max-w-screen-2xl", siteGuideColumnPadYClass)}>
          <section className={cn(siteHeroFramedShellClass, "overflow-hidden p-6 shadow-expatos-xl sm:p-8 lg:p-12")}>
            <div className={siteHeroTopAccentClass} aria-hidden /><div className={siteHeroGlowPrimaryClass} aria-hidden /><div className={siteHeroGlowSecondaryClass} aria-hidden />
            <div className="relative grid gap-8 lg:grid-cols-[minmax(0,1fr)_0.78fr] lg:items-center">
              <div><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-strong">{page.hero.eyebrow}</p><h1 className="mt-3 max-w-4xl text-4xl font-bold tracking-tight text-foreground sm:text-5xl lg:text-6xl">{page.hero.pageTitle}</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-foreground-muted sm:text-xl">{page.hero.subtitle}</p><div className="mt-6 flex flex-wrap gap-2">{page.hero.chips.map((chip) => <span key={chip} className={cn(CITIES_FUNNEL_INFO_CHIP, "shadow-sm ring-1 ring-slate-900/[0.03]")}>{chip}</span>)}</div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href={page.hero.primaryCta.href} className={primaryCtaClass}>{page.hero.primaryCta.label}<ArrowRight className="h-4 w-4" aria-hidden /></Link><Link href={page.hero.secondaryCta.href} className={secondaryCtaClass}>{page.hero.secondaryCta.label}</Link></div><p className="mt-5 max-w-3xl rounded-2xl border border-slate-200/80 bg-white/70 px-4 py-3 text-sm leading-relaxed text-foreground-muted shadow-sm ring-1 ring-slate-900/[0.03]">Educational orientation only. This page is not tax advice, legal advice, personalized filing advice or international tax planning advice.</p></div>
              <HeroImage />
            </div>
          </section>
          <HeroSignalStrip />
          <nav className="sticky top-3 z-20 mt-6 flex gap-2 overflow-x-auto rounded-2xl border border-slate-200/80 bg-white/90 p-2 shadow-card ring-1 ring-slate-900/[0.04] backdrop-blur-xl" aria-label="Taxes after moving guide sections">{page.sectionNav.map((item) => <a key={item.href} href={item.href} className={cn("shrink-0 rounded-xl px-3 py-2 text-sm font-semibold text-foreground-muted hover:bg-copilot-bg-soft hover:text-brand-strong focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30", transitionInteractive, activeBrightnessPress)}>{item.label}</a>)}</nav>
          <div className={sectionStackClass}>
            <section id="intro" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Core concept" title="What Happens Tax-Wise After Moving to the Netherlands?" fullWidth>{page.introPoints.map((point) => <p key={point}>{point}</p>)}</SectionIntro><VisualFigure visual={page.visuals.intro} /></div></section>
            <section id="snapshot" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="At a glance" title="Taxes After Moving at a Glance"><p>Use this snapshot as a triage checklist for your first Dutch tax year: what starts immediately, what depends on personal facts and what deserves deeper reading.</p></SectionIntro><VisualFigure visual={page.visuals.snapshot} /></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{page.snapshotCards.map((card, index) => <StatCard key={card.label} label={card.label} value={card.value} iconIndex={index} />)}</div></section>
            <section id="first-steps" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Arrival admin" title="First Tax-Related Steps After Moving"><p>Registration, BSN, health insurance, payroll, DigiD and allowance checks are connected. A practical onboarding order helps prevent avoidable delays.</p></SectionIntro><VisualFigure visual={page.visuals.firstSteps} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.firstStepsCards.map((card, index) => <FeatureCard key={card.title} title={card.title} body={card.body} iconIndex={index} />)}</div><div className="mt-6"><ExampleTable title="Illustrative first-step timing examples" columns={["Step", "Typical timing", "Example", "Record to keep"]} rows={page.arrivalTimingExamples.map((row) => ({ Step: row.step, "Typical timing": row.typicalTiming, Example: row.example, "Record to keep": row.recordToKeep }))} /></div></section>
            <section id="residency" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Tax residency" title="Understanding Dutch Tax Residency"><p>Tax residency affects reporting obligations, foreign-income considerations and tax filing requirements. It should not be reduced to nationality, visa status or a single registration date.</p></SectionIntro><VisualFigure visual={page.visuals.residency} /></div><div className="mt-6"><BulletPanel title="Residency factors to map" items={page.residencyFactors} /></div><div className="mt-6"><ExampleTable title="Residency scenario examples" columns={["Profile", "Facts", "Practical question", "Useful records"]} rows={page.residencyScenarioExamples.map((row) => ({ Profile: row.profile, Facts: row.facts, "Practical question": row.practicalQuestion, "Useful records": row.usefulRecords }))} /></div></section>
            <section id="payroll" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Salary" title="Payroll Tax and Your Salary"><p>Most employees immediately notice payroll deductions, pension contributions and healthcare-related deductions. Dutch gross salary and net salary can differ significantly.</p></SectionIntro><VisualFigure visual={page.visuals.payroll} /></div><div className="mt-6"><ExampleTable title="Payroll examples with figures" columns={["Profile", "Gross salary", "Monthly gross", "Likely payslip question", "What to compare"]} rows={page.payrollExampleRows.map((row) => ({ Profile: row.profile, "Gross salary": row.grossSalary, "Monthly gross": row.monthlyGross, "Likely payslip question": row.likelyPayslipQuestion, "What to compare": row.whatToCompare }))} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{page.payrollTopics.map((link, index) => <LinkCard key={link.href} item={link} iconIndex={index} />)}</div></section>
            <section id="ruling" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Highly skilled migrants" title="Understanding the 30% Ruling"><p>Some highly skilled migrants may qualify for the 30% ruling. It may affect taxable salary, net income and expat compensation, but eligibility is never guaranteed.</p></SectionIntro><VisualFigure visual={page.visuals.ruling} /></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><BulletPanel title="How to frame the 30% ruling" items={page.rulingPoints} /><LinkCard item={page.relatedGuides[1]} iconIndex={2} /></div><div className="mt-6"><ExampleTable title="30% ruling scenario examples" columns={["Scenario", "Figures", "Useful question", "Records"]} rows={page.rulingScenarioExamples.map((row) => ({ Scenario: row.scenario, Figures: row.figures, "Useful question": row.usefulQuestion, Records: row.records }))} /></div></section>
            <section id="foreign-income" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="International income" title="Foreign Income and International Tax Questions"><p>Many expats still have overseas income, rental property abroad, foreign investments, pensions or remote-work income after moving. These can create Dutch tax considerations.</p></SectionIntro><VisualFigure visual={page.visuals.foreignIncome} /></div><div className="mt-6"><ExampleTable title="Foreign-income scenarios after moving" columns={["Profile", "Example", "Question"]} rows={page.foreignIncomeExamples.map((row) => ({ Profile: row.profile, Example: row.example, Question: row.question }))} /></div><div className="mt-6 grid gap-4 md:grid-cols-2"><LinkCard item={page.relatedGuides[3]} iconIndex={3} /><LinkCard item={page.relatedGuides[4]} iconIndex={4} /></div></section>
            <section id="allowances" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Benefits" title="Dutch Allowances Expats Should Know"><p>Allowances can reduce pressure during the first year, but eligibility depends on personal circumstances and official rules.</p></SectionIntro><VisualFigure visual={page.visuals.allowances} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.allowanceCards.map((card, index) => <FeatureCard key={card.title} title={card.title} body={card.body} iconIndex={index} />)}</div><div className="mt-6"><ExampleTable title="Allowance examples with inputs to verify" columns={["Allowance", "Example inputs", "What to check", "Useful record"]} rows={page.allowanceScenarioExamples.map((row) => ({ Allowance: row.allowance, "Example inputs": row.exampleInputs, "What to check": row.whatToCheck, "Useful record": row.usefulRecord }))} /></div></section>
            <section id="healthcare" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Insurance" title="Healthcare and Taxes"><p>Dutch health insurance is mandatory for many residents. Healthcare costs and healthcare allowance are separate but connected topics for newcomers.</p></SectionIntro><VisualFigure visual={page.visuals.healthcare} /></div><div className="mt-6"><ExampleTable title="Healthcare cost scenarios" columns={["Scenario", "Monthly premium", "Allowance question", "Records"]} rows={page.healthcareCostExamples.map((row) => ({ Scenario: row.scenario, "Monthly premium": row.monthlyPremium, "Allowance question": row.allowanceQuestion, Records: row.records }))} /></div><div className="mt-6 grid gap-4 md:grid-cols-2"><LinkCard item={page.exploreNextCards[2]} iconIndex={0} /><LinkCard item={page.relatedFooterGuides[6]} iconIndex={1} /></div></section>
            <section id="annual-returns" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Annual filing" title="Annual Tax Returns in the Netherlands"><p>Many expats eventually file annual tax returns. Reasons can include salary adjustments, allowances, foreign income, moving mid-year or possible refunds.</p></SectionIntro><VisualFigure visual={page.visuals.taxReturn} /></div><div className="mt-6"><BulletPanel title="Common reasons annual filing becomes relevant" items={page.taxReturnReasons} /></div><div className="mt-6"><ExampleTable title="Annual return trigger examples" columns={["Trigger", "Example figure", "Why it matters", "Records"]} rows={page.annualReturnScenarioExamples.map((row) => ({ Trigger: row.trigger, "Example figure": row.exampleFigure, "Why it matters": row.whyItMatters, Records: row.records }))} /></div></section>
            <section id="mid-year" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Timing" title="Moving During the Tax Year"><p>Arriving mid-year can create split-year situations, foreign income questions and partial-residency considerations. This is common for expats.</p></SectionIntro><VisualFigure visual={page.visuals.midYear} /></div><div className="mt-6"><ExampleTable title="Mid-year move examples" columns={["Timeline", "Example", "Practical record"]} rows={page.midYearExamples.map((row) => ({ Timeline: row.timeline, Example: row.example, "Practical record": row.practicalRecord }))} /></div></section>
            <section id="remote-work" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Foreign employers" title="Remote Work and Foreign Employers"><p>Common scenarios include working remotely for a foreign employer, hybrid international work and digital nomad transitions. Cross-border tax complexity can increase quickly.</p></SectionIntro><VisualFigure visual={page.visuals.remoteWork} /></div><div className="mt-6"><ExampleTable title="Remote-work scenarios" columns={["Pattern", "Complexity", "Practical move"]} rows={page.remoteWorkScenarios.map((row) => ({ Pattern: row.pattern, Complexity: row.complexity, "Practical move": row.practicalMove }))} /></div><div className="mt-6"><ExampleTable title="Workday split examples" columns={["Pattern", "Workday split", "Likely question", "Records"]} rows={page.remoteWorkdayExamples.map((row) => ({ Pattern: row.pattern, "Workday split": row.workdaySplit, "Likely question": row.likelyQuestion, Records: row.records }))} /></div></section>
            <section id="mistakes" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Avoidable mistakes" title="Common Mistakes After Relocating"><p>Most first-year tax problems start with assumptions: ignoring foreign income, delaying DigiD, missing allowance checks or treating the 30% ruling as automatic.</p></SectionIntro><VisualFigure visual={page.visuals.mistakes} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.mistakeCards.map((card, index) => <FeatureCard key={card.title} title={card.title} body={card.body} iconIndex={index} />)}</div></section>
            <section id="life-stage" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Personal situation" title="How Taxes Change Depending on Your Situation"><p>Your first tax questions change depending on whether you are a single employee, couple, family, remote worker, freelancer, homeowner or highly skilled migrant.</p></SectionIntro><VisualFigure visual={page.visuals.lifeStage} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.lifeStageCards.map((card, index) => <FeatureCard key={card.title} title={card.title} body={card.body} iconIndex={index} />)}</div><div className="mt-6"><ExampleTable title="Life-stage examples with figures" columns={["Life stage", "Example numbers", "First checks"]} rows={page.lifeStageScenarioExamples.map((row) => ({ "Life stage": row.lifeStage, "Example numbers": row.exampleNumbers, "First checks": row.firstChecks }))} /></div></section>
            <section id="questions" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Common questions" title="Questions Expats Often Ask"><p>These questions help users identify the next missing fact: income type, residency timing, payroll setup, allowance eligibility, move date or foreign-income record.</p></SectionIntro><VisualFigure visual={page.visuals.questions} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.expatQuestions.map((item, index) => <FeatureCard key={item.q} title={item.q} body={item.a} iconIndex={index} />)}</div></section>
            <section id="related-tax-guides" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Internal guide hub" title="Related Expat Tax Guides"><p>Use these tax guides as a reading path: start broad, then open the specific payroll, 30% ruling, foreign-income or double-taxation page that matches your situation.</p></SectionIntro><VisualFigure visual={page.visuals.relatedGuides} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{page.relatedGuides.map((link, index) => <LinkCard key={link.href} item={link} iconIndex={index} />)}</div></section>
            <section id="services" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Professional help" title="Professional Services That May Help"><p>Professional advice may be useful when tax, payroll, relocation, immigration or financial planning questions overlap.</p></SectionIntro><VisualFigure visual={page.visuals.services} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{page.services.map((link, index) => <LinkCard key={link.href} item={link} iconIndex={index} />)}</div></section>
            <section id="faq" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="FAQ" title="Frequently Asked Questions"><p>Use the FAQ for orientation before checking official sources, employer payroll details or professional advice for your personal situation.</p></SectionIntro><VisualFigure visual={page.visuals.faq} /></div><div className="mt-6 grid gap-4 md:grid-cols-2">{page.faq.map((item, index) => <FeatureCard key={item.q} title={item.q} body={item.a} iconIndex={index} />)}</div></section>
            <section id="sources" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Official sources" title="Official Sources"><p>{page.sourcesDisclaimer}</p></SectionIntro><VisualFigure visual={page.visuals.sources} /></div><div className="mt-6"><SourcesSection /></div></section>
            <section id="related-guides" className={sectionClass}><div className="space-y-6"><SectionIntro eyebrow="Related guides" title="Continue Through the Relocation and Tax Ecosystem"><p>This guide sits between moving admin, salary planning, healthcare setup, foreign-income awareness and official tax sources. Use the ecosystem links to keep moving without jumping into unrelated tax planning.</p></SectionIntro><VisualFigure visual={page.visuals.relocationEcosystem} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{page.relatedFooterGuides.map((link, index) => <LinkCard key={link.href} item={link} iconIndex={index} />)}</div></section>
            <section className={cn("relative isolate overflow-hidden rounded-[2rem] bg-slate-950 p-6 shadow-expatos-xl ring-1 ring-white/10 sm:p-8 lg:p-10")}><div className={cn("absolute inset-x-0 top-0 h-1.5", movingNlSignatureGradientClass)} aria-hidden /><div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-cyan-400/20 blur-3xl" aria-hidden /><div className="pointer-events-none absolute -bottom-28 left-1/4 h-72 w-72 rounded-full bg-emerald-300/10 blur-3xl" aria-hidden /><div className="relative space-y-6"><SectionIntro eyebrow="Explore next" title="Build Your Dutch Tax Foundation" tone="onDark"><p>Move from first-year tax onboarding into payroll, 30% ruling, healthcare allowance, foreign income and relocation planning.</p></SectionIntro><VisualFigure visual={page.visuals.exploreNext} /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{page.exploreNextCards.map((link, index) => <LinkCard key={link.href} item={link} iconIndex={index} tone="onDark" />)}</div></section>
          </div>
        </Container>
      </main>
    </>
  );
}
