import type { CitiesBestForExpatsProfileCardConfig } from "../../best-cities-for-expats/config/citiesBestForExpats.types";
import { citiesBestForExpatsRoutes as R } from "../../best-cities-for-expats/config/citiesBestForExpats.routes";

export const citiesIntlProfProfileCards: CitiesBestForExpatsProfileCardConfig[] = [
  {
    id: "prof-amsterdam",
    name: "Amsterdam",
    guide: { href: "/netherlands/amsterdam/", label: "Amsterdam city guide" },
    accent: "sky",
    heroImage: {
      src: "/images/heroes/amsterdam-expat-relocation-planning-hero.png",
      alt: "Amsterdam canals — career hub snapshot",
    },
    tags: ["Most choice", "Premium rent"],
    intro: "Largest hiring pool, busy networks, and fast pace when your office is really here.",
    bestFor: "Finance, tech, growing companies, consulting, and roles that need lots of face-to-face.",
    tradeoffs: ["Rent and competition bite — model take-home after housing, not headline salary."],
    nextLinks: [
      { href: R.cityComparison, label: "City comparison tool" },
      { href: R.rentAffordability, label: "Rent affordability calculator" },
    ],
  },
  {
    id: "prof-utrecht",
    name: "Utrecht",
    guide: { href: "/netherlands/utrecht/", label: "Utrecht city guide" },
    accent: "violet",
    heroImage: {
      src: "/images/heroes/utrecht-expat-relocation-hero-planning-scene.png",
      alt: "Utrecht centre and station area",
    },
    tags: ["Central NL", "Scale-ups"],
    intro: "National rail hub on a human scale — strong trains and a credible scale-up scene without only living in Amsterdam chaos.",
    bestFor: "SaaS, consulting, work near government, and steady hybrid weeks.",
    tradeoffs: ["Peak crowding and housing competition still hurt if you skip planning."],
    nextLinks: [
      { href: R.dutchSalaryNetCalculator, label: "Dutch salary (net) calculator" },
      { href: R.cityComparison, label: "Compare Utrecht vs finalists" },
    ],
  },
  {
    id: "prof-rotterdam",
    name: "Rotterdam",
    guide: { href: "/netherlands/rotterdam/", label: "Rotterdam city guide" },
    accent: "cyan",
    heroImage: {
      src: "/images/heroes/rotterdam-expat-relocation-hero.png",
      alt: "Rotterdam skyline and waterfront",
    },
    tags: ["Port", "Space"],
    intro: "Port-city scale — logistics, maritime, energy-related work, and creative sectors, often with more space per euro than Amsterdam in many areas.",
    bestFor: "Big company offices, operations, and people who like modern urban energy by the water.",
    tradeoffs: ["Neighbourhoods vary a lot — check commute and daily feel street by street."],
    nextLinks: [
      { href: R.costOfLiving, label: "Cost of living calculator" },
      { href: R.cityComparison, label: "City comparison tool" },
    ],
  },
  {
    id: "prof-eindhoven",
    name: "Eindhoven",
    guide: { href: "/netherlands/eindhoven/", label: "Eindhoven city guide" },
    accent: "amber",
    heroImage: {
      src: "/images/heroes/eindhoven-city-hub-hero.png",
      alt: "Eindhoven Brainport city",
    },
    tags: ["Tech", "Engineering"],
    intro: "Tech and industry hub — strong engineering jobs with fewer long trips west when your role is truly local.",
    bestFor: "Deep tech, hardware, automotive-related careers and households that put job fit first.",
    tradeoffs: ["Niche roles outside core sectors can feel thinner — check early."],
    nextLinks: [
      { href: R.thirtyPercentRulingCalculator, label: "30% ruling calculator" },
      { href: R.cityComparison, label: "Compare Eindhoven vs finalists" },
    ],
  },
  {
    id: "prof-hague",
    name: "The Hague",
    guide: { href: "/netherlands/the-hague/", label: "The Hague city guide" },
    accent: "indigo",
    heroImage: {
      src: "/images/heroes/the-hague-expat-relocation-hero-planning-scene.png",
      alt: "The Hague cityscape and institutions",
    },
    tags: ["IOs & law", "Coast"],
    intro: "International organisations, legal, and policy work cluster here, with the coast nearby.",
    bestFor: "NGOs, diplomacy, legal, policy, and people who want English-friendly professional services.",
    tradeoffs: ["Two careers can pull in different directions — map partner travel before you pick one neighbourhood."],
    nextLinks: [
      { href: R.costOfLiving, label: "Cost of living calculator" },
      { href: "/netherlands/amsterdam/", label: "Amsterdam guide (commute context)" },
    ],
  },
  {
    id: "prof-haarlem",
    name: "Haarlem",
    guide: { href: "/netherlands/haarlem/", label: "Haarlem city guide" },
    accent: "rose",
    heroImage: {
      src: "/images/heroes/haarlem-grote-markt-expat-hero.png",
      alt: "Haarlem historic market square",
    },
    tags: ["Amsterdam orbit", "Coast"],
    intro: "Coastal calm with Amsterdam reach — works when office days are bounded and hybrid is honest.",
    bestFor: "Amsterdam-area careers that want recovery time and a walkable town centre.",
    tradeoffs: ["Premium market — compare rent plus travel with living closer to work."],
    nextLinks: [
      { href: R.rentAffordability, label: "Rent affordability calculator" },
      { href: R.cityComparison, label: "Compare Haarlem vs finalists" },
    ],
  },
  {
    id: "prof-leiden",
    name: "Leiden",
    guide: { href: "/netherlands/leiden/", label: "Leiden city guide" },
    accent: "emerald",
    heroImage: {
      src: "/images/heroes/leiden-expat-city-hero.png",
      alt: "Leiden canals and university quarter",
    },
    tags: ["Research", "Compact"],
    intro: "University-town rhythm with easy reach west — knowledge-sector energy without megacity sprawl.",
    bestFor: "Research, life sciences, knowledge work, and bike-first routines.",
    tradeoffs: ["Student demand overlaps housing in pockets — scout deliberately."],
    nextLinks: [
      { href: R.cityComparison, label: "Compare Leiden vs finalists" },
      { href: R.dutchSalaryNetCalculator, label: "Dutch salary (net) calculator" },
    ],
  },
  {
    id: "prof-delft",
    name: "Delft",
    guide: { href: "/netherlands/delft/", label: "Delft city guide" },
    accent: "teal",
    heroImage: {
      src: "/images/heroes/delft-expat-city-hero.png",
      alt: "Delft historic canals",
    },
    tags: ["TU", "Multi-hub"],
    intro: "Quiet canal town between The Hague and Rotterdam — handy when specialist days split across hubs.",
    bestFor: "Engineering- and academic-adjacent households who accept nearby hubs on some workdays.",
    tradeoffs: ["Tighter housing stock — fewer easy options than in bigger cities."],
    nextLinks: [
      { href: R.costOfLiving, label: "Cost of living calculator" },
      { href: "/netherlands/rotterdam/", label: "Rotterdam guide (context)" },
    ],
  },
  {
    id: "prof-amersfoort",
    name: "Amersfoort",
    guide: { href: R.cityComparison, label: "Model Amersfoort in city comparison" },
    accent: "sky",
    heroImage: {
      src: "/images/heroes/utrecht-expat-relocation-hero-planning-scene.png",
      alt: "Historic Dutch city on the rail corridor — compare Amersfoort in the city tool",
    },
    tags: ["Rail", "Compare"],
    intro: "Historic town on the Utrecht–Amsterdam corridor — a rising pick when hybrid patterns fit those links.",
    bestFor: "Hybrid professionals who want calm evenings and strong intercity trains.",
    tradeoffs: ["No dedicated ExpatCopilot city guide yet — compare finalists in the tool before you chase listings."],
    nextLinks: [
      { href: R.cityComparison, label: "City comparison tool" },
      { href: "/netherlands/utrecht/", label: "Utrecht guide (corridor context)" },
    ],
  },
  {
    id: "prof-breda",
    name: "Breda",
    guide: { href: "/netherlands/breda/", label: "Breda city guide" },
    accent: "cyan",
    heroImage: {
      src: "/images/heroes/breda-expat-city-hero.png",
      alt: "Breda city centre",
    },
    tags: ["Brabant", "Space"],
    intro: "Southern balance — often gentler monthly pressure, with Rotterdam in reach for occasional big-city days.",
    bestFor: "Space-first professionals and regional careers that do not need daily trips to the busiest western hubs.",
    tradeoffs: ["Job depth varies by sector — check partner markets and where clients are early."],
    nextLinks: [
      { href: R.rentAffordability, label: "Rent calculator" },
      { href: R.cityComparison, label: "City comparison tool" },
    ],
  },
];
