import type { MoneyTaxGuideMisunderstandingConfig } from "./taxGuideContent.types";

export const moneyTaxGuideMisunderstandings: readonly MoneyTaxGuideMisunderstandingConfig[] = [
  {
    id: "withheld-done",
    title: "Withheld tax is not always final tax",
    intro: "Payroll can be close — or not — depending on your full-year facts and return-time adjustments.",
    keyPoints: [],
    cautionNote: "",
    relatedTools: [],
    officialSourceKeys: ["bd_payroll_taxes", "bd_filing_return"],
  },
  {
    id: "gross-compare",
    title: "Gross salary comparisons mislead",
    intro: "Two offers with the same gross can produce different net after pension, hours, ruling, and commuter costs.",
    keyPoints: [],
    cautionNote: "",
    relatedTools: [{ kind: "tool", key: "jobOffer" }, { kind: "tool", key: "salaryNet" }],
    officialSourceKeys: [],
  },
  {
    id: "ruling-auto",
    title: "30% ruling is not automatic",
    intro: "Eligibility, application timing, and payroll setup all matter — assume nothing until confirmed.",
    keyPoints: [],
    cautionNote: "",
    relatedTools: [{ kind: "tool", key: "ruling" }],
    officialSourceKeys: ["bd_30_percent_facility"],
  },
  {
    id: "foreign-assets",
    title: "Foreign assets may still matter",
    intro: "Residency and reporting rules can bring overseas accounts and investments into the conversation.",
    keyPoints: [],
    cautionNote: "",
    relatedTools: [{ kind: "tool", key: "doubleTax" }],
    officialSourceKeys: ["bd_international_en"],
  },
  {
    id: "allowance-vs-deduction",
    title: "Allowances are not the same as deductions",
    intro: "They follow different rules and portals — mixing them up causes missed support or wrong expectations.",
    keyPoints: [],
    cautionNote: "",
    relatedTools: [{ kind: "tool", key: "healthcare" }],
    officialSourceKeys: ["toeslagen_portal", "bd_income_tax_individuals"],
  },
  {
    id: "box3-surprise",
    title: "Box 3 surprises people",
    intro: "Wealth reporting feels different from payslip tax — if you have meaningful investments, read the basics early so filing season is calmer.",
    keyPoints: [],
    cautionNote: "",
    relatedTools: [],
    officialSourceKeys: ["gov_income_tax_allowances"],
  },
  {
    id: "partial-year",
    title: "Arrival/departure years are harder",
    intro: "Partial-year income, moving costs, and split residency stories rarely fit a single blog template.",
    keyPoints: [],
    cautionNote: "",
    relatedTools: [{ kind: "tool", key: "expatTaxesGuide" }],
    officialSourceKeys: ["bd_filing_return"],
  },
  {
    id: "calculator-verdict",
    title: "Calculators estimate — they do not decide",
    intro: "Use them to learn sensitivity and ask better questions — not to “prove” an outcome to an authority.",
    keyPoints: [],
    cautionNote: "",
    relatedTools: [{ kind: "tool", key: "taxesTools" }],
    officialSourceKeys: ["bd_income_tax_individuals"],
  },
] as const;
