import type { CitiesBestForExpatsCityCardConfig } from "./citiesBestForExpats.types";

/** Top city option / comparison grid entries. */
export const citiesBestForExpatsCityCards: CitiesBestForExpatsCityCardConfig[] = [
  {
    id: "amsterdam",
    name: "Amsterdam",
    guide: { href: "/netherlands/amsterdam/", label: "Amsterdam city guide" },
    tags: ["Randstad", "HQs", "English-default"],
    intro: "Maximum jobs, services, and English-default life — toughest rent and housing competition.",
    bestFor: "HQs, finance, scale-ups, creatives; widest international day-to-day surface area.",
    tradeoffs: ["Premium rent; crowded market; plan commute + housing budget before you browse."],
    visualKey: "core-hub",
    levels: {
      costPressure: "high",
      internationalFeel: "high",
      familyFit: "mixed",
      connectivity: "high",
    },
  },
  {
    id: "utrecht",
    name: "Utrecht",
    guide: { href: "/netherlands/utrecht/", label: "Utrecht city guide" },
    tags: ["Central", "Rail hub", "Balance"],
    intro: "Central rail hub, compact core — “balance city” with serious rent competition.",
    bestFor: "Consulting, national travel, HQs; urban life without Amsterdam sprawl.",
    tradeoffs: ["Still expensive; housing moves fast — treat search like a project."],
    visualKey: "core-hub",
    levels: {
      costPressure: "high",
      internationalFeel: "high",
      familyFit: "high",
      connectivity: "high",
    },
  },
  {
    id: "rotterdam",
    name: "Rotterdam",
    guide: { href: "/netherlands/rotterdam/", label: "Rotterdam city guide" },
    tags: ["Port", "Creative", "Space value"],
    intro: "Port, logistics, creative industries — modern urban energy, often more room per euro than Amsterdam.",
    bestFor: "Trade, design, maritime-adjacent roles; open urban fabric.",
    tradeoffs: ["Some careers still orbit Amsterdam/The Hague — validate commute before signing."],
    visualKey: "core-hub",
    levels: {
      costPressure: "medium",
      internationalFeel: "high",
      familyFit: "mixed",
      connectivity: "high",
    },
  },
  {
    id: "the-hague",
    name: "The Hague",
    guide: { href: "/netherlands/the-hague/", label: "The Hague city guide" },
    tags: ["Institutions", "Coast", "Law"],
    intro: "Institutions, law, diplomacy, NGOs — coast nearby, strong expat services.",
    bestFor: "Policy, legal, IO/NGO paths; families who like sea + city mix.",
    tradeoffs: ["Daily Amsterdam commute gets old fast — be honest about office location."],
    visualKey: "core-hub",
    levels: {
      costPressure: "medium",
      internationalFeel: "high",
      familyFit: "high",
      connectivity: "high",
    },
  },
  {
    id: "eindhoven",
    name: "Eindhoven",
    guide: { href: "/netherlands/eindhoven/", label: "Eindhoven city guide" },
    tags: ["Tech", "Engineering", "Brainport"],
    intro: "Brainport: deep tech & engineering employers in a compact city.",
    bestFor: "Semiconductors, hardware, embedded, automotive R&D.",
    tradeoffs: ["Smaller “global nightlife” than Randstad; partner job markets can be narrower."],
    visualKey: "core-hub",
    levels: {
      costPressure: "medium",
      internationalFeel: "medium",
      familyFit: "high",
      connectivity: "mixed",
    },
  },
  {
    id: "haarlem",
    name: "Haarlem",
    guide: { href: "/netherlands/haarlem/", label: "Haarlem city guide" },
    tags: ["Amsterdam orbit", "Historic"],
    intro: "Historic centre + quick Amsterdam/Schiphol links — quieter than living in the capital core.",
    bestFor: "Amsterdam employers; atmosphere-first households.",
    tradeoffs: ["Not a secret discount; peak trains toward Amsterdam fill up."],
    visualKey: "strong-option",
    levels: {
      costPressure: "high",
      internationalFeel: "medium",
      familyFit: "high",
      connectivity: "high",
    },
  },
  {
    id: "leiden",
    name: "Leiden",
    guide: { href: "/netherlands/leiden/", label: "Leiden city guide" },
    tags: ["University", "Research", "Randstad"],
    intro: "University town between The Hague and Schiphol corridors — research-heavy.",
    bestFor: "Academia, life sciences, splits toward Hague or airport.",
    tradeoffs: ["Student demand spikes; time your housing search."],
    visualKey: "strong-option",
    levels: {
      costPressure: "medium",
      internationalFeel: "medium",
      familyFit: "mixed",
      connectivity: "high",
    },
  },
  {
    id: "delft",
    name: "Delft",
    guide: { href: "/netherlands/delft/", label: "Delft city guide" },
    tags: ["TU", "Quiet", "Randstad"],
    intro: "Small canal city between Rotterdam and The Hague — engineering & research adjacency.",
    bestFor: "TU-linked tech, quiet daily life with Randstad trains.",
    tradeoffs: ["Term-time housing pressure; big nights out mean a train ride."],
    visualKey: "strong-option",
    levels: {
      costPressure: "medium",
      internationalFeel: "medium",
      familyFit: "high",
      connectivity: "high",
    },
  },
  {
    id: "groningen",
    name: "Groningen",
    guide: { href: "/netherlands/groningen/", label: "Groningen city guide" },
    tags: ["North", "Student life", "Value"],
    intro: "Northern capital — strong student life, cycling, self-contained jobs market.",
    bestFor: "Local northern careers, academics, lower Randstad rent pressure.",
    tradeoffs: ["Distance to western HQs and Schiphol — fine if your work is here."],
    visualKey: "strong-option",
    levels: {
      costPressure: "lower",
      internationalFeel: "medium",
      familyFit: "mixed",
      connectivity: "mixed",
    },
  },
  {
    id: "breda",
    name: "Breda",
    guide: { href: "/netherlands/breda/", label: "Breda city guide" },
    tags: ["Brabant", "Space", "Border"],
    intro: "Brabant mid-size city — calmer than Randstad cores, strong southern links.",
    bestFor: "Cross-border workers, space-first households.",
    tradeoffs: ["Fewer HQs than Amsterdam/Rotterdam — check your sector locally."],
    visualKey: "strong-option",
    levels: {
      costPressure: "lower",
      internationalFeel: "medium",
      familyFit: "high",
      connectivity: "mixed",
    },
  },
  {
    id: "amstelveen",
    name: "Amstelveen",
    guide: { href: "/netherlands/amstelveen/", label: "Amstelveen city guide" },
    tags: ["Families", "Amsterdam orbit", "Schools"],
    intro: "Green suburb with Amsterdam reach — familiar with international-school flows.",
    bestFor: "Families wanting space + Amsterdam employers.",
    tradeoffs: ["Suburban rhythm; competitive segments still priced off capital demand."],
    visualKey: "strong-option",
    levels: {
      costPressure: "high",
      internationalFeel: "high",
      familyFit: "high",
      connectivity: "high",
    },
  },
  {
    id: "maastricht",
    name: "Maastricht",
    guide: { href: "/netherlands/maastricht/", label: "Maastricht city guide" },
    tags: ["Limburg", "Border", "University"],
    intro: "Compact Limburg city — border culture, university town, slower pace.",
    bestFor: "Limburg employers, EU-border life, distinct local scene.",
    tradeoffs: ["Far from Randstad job gravity — plan network and travel honestly."],
    visualKey: "strong-option",
    levels: {
      costPressure: "medium",
      internationalFeel: "medium",
      familyFit: "mixed",
      connectivity: "mixed",
    },
  },
];
