import type { CitiesBestForExpatsProfileCardConfig } from "./citiesBestForExpats.types";
import { citiesBestForExpatsRoutes as R } from "./citiesBestForExpats.routes";

/** Short city profile / decision cards (deeper than comparison grid). */
export const citiesBestForExpatsProfileCards: CitiesBestForExpatsProfileCardConfig[] = [
  {
    id: "p-amsterdam",
    name: "Amsterdam",
    guide: { href: "/netherlands/amsterdam/", label: "Amsterdam city guide" },
    accent: "sky",
    heroImage: {
      src: "/images/heroes/amsterdam-expat-relocation-planning-hero.png",
      alt: "Amsterdam canals and historic gables — expat city snapshot",
    },
    tags: ["Scale", "Competition"],
    intro: "Maximum scale and choice — and the sharpest housing competition.",
    bestFor: "Global careers, networking, English-default day-to-day.",
    tradeoffs: ["Rent stress + viewing queues; lock commute + budget before you fall for listings."],
    nextLinks: [
      { href: "/netherlands/amsterdam/", label: "Amsterdam city guide" },
      { href: R.rentAffordability, label: "Rent calculator" },
      { href: R.costOfLiving, label: "Cost of living" },
    ],
  },
  {
    id: "p-utrecht",
    name: "Utrecht",
    guide: { href: "/netherlands/utrecht/", label: "Utrecht city guide" },
    accent: "violet",
    heroImage: {
      src: "/images/heroes/utrecht-expat-relocation-hero-planning-scene.png",
      alt: "Utrecht city centre and Dom tower area — expat city snapshot",
    },
    tags: ["Central", "Competitive"],
    intro: "Central, attractive “balance” hub — housing still moves fast.",
    bestFor: "National travel, consulting, urban life without Amsterdam sprawl.",
    tradeoffs: ["Mid-size ≠ easy listings — speed + paperwork still decide."],
    nextLinks: [
      { href: "/netherlands/utrecht/", label: "Utrecht city guide" },
      { href: R.cityComparison, label: "City comparison tool" },
    ],
  },
  {
    id: "p-rotterdam",
    name: "Rotterdam",
    guide: { href: "/netherlands/rotterdam/", label: "Rotterdam city guide" },
    accent: "cyan",
    heroImage: {
      src: "/images/heroes/rotterdam-expat-relocation-hero.png",
      alt: "Rotterdam skyline and Erasmus bridge area — expat city snapshot",
    },
    tags: ["Port", "Design"],
    intro: "Modern port + creative energy; often more room per euro than Amsterdam.",
    bestFor: "Logistics, trade, design, contemporary urban fabric.",
    tradeoffs: ["Some careers still pull Amsterdam / The Hague — validate commute before signing."],
    nextLinks: [
      { href: "/netherlands/rotterdam/", label: "Rotterdam city guide" },
      { href: R.costOfLiving, label: "Cost of living" },
    ],
  },
  {
    id: "p-hague",
    name: "The Hague",
    guide: { href: "/netherlands/the-hague/", label: "The Hague city guide" },
    accent: "indigo",
    heroImage: {
      src: "/images/heroes/the-hague-expat-relocation-hero-planning-scene.png",
      alt: "The Hague cityscape and institutions quarter — expat city snapshot",
    },
    tags: ["Institutions", "Coast"],
    intro: "Institutions, coast nearby, distinct expat cluster.",
    bestFor: "Law, policy, diplomacy, NGOs; sea + city mix.",
    tradeoffs: ["Daily cross-Randstad commute is punishing — be honest about office location."],
    nextLinks: [
      { href: "/netherlands/the-hague/", label: "The Hague city guide" },
      { href: R.childcare, label: "Childcare estimator" },
    ],
  },
  {
    id: "p-eindhoven",
    name: "Eindhoven",
    guide: { href: "/netherlands/eindhoven/", label: "Eindhoven city guide" },
    accent: "amber",
    heroImage: {
      src: "/images/heroes/eindhoven-city-hub-hero.png",
      alt: "Eindhoven Brainport tech city atmosphere — expat city snapshot",
    },
    tags: ["Tech", "Engineering"],
    intro: "Engineering employer magnet in a compact footprint.",
    bestFor: "Hardware, semiconductors, deep product engineering.",
    tradeoffs: ["Partner job markets narrower; quieter nights than Randstad cores."],
    nextLinks: [
      { href: "/netherlands/eindhoven/", label: "Eindhoven city guide" },
      { href: R.cityComparison, label: "City comparison tool" },
    ],
  },
  {
    id: "p-haarlem",
    name: "Haarlem",
    guide: { href: "/netherlands/haarlem/", label: "Haarlem city guide" },
    accent: "rose",
    heroImage: {
      src: "/images/heroes/haarlem-grote-markt-expat-hero.png",
      alt: "Haarlem Grote Markt and historic streets — expat city snapshot",
    },
    tags: ["Amsterdam orbit", "Atmosphere"],
    intro: "Historic core; short hop to Amsterdam / Schiphol when needed.",
    bestFor: "Amsterdam-area workers; atmosphere-first households.",
    tradeoffs: ["Peak trains + premium rent — not a hidden cheap option."],
    nextLinks: [
      { href: "/netherlands/haarlem/", label: "Haarlem city guide" },
      { href: R.rentAffordability, label: "Rent calculator" },
    ],
  },
  {
    id: "p-leiden",
    name: "Leiden",
    guide: { href: "/netherlands/leiden/", label: "Leiden city guide" },
    accent: "emerald",
    heroImage: {
      src: "/images/heroes/leiden-expat-city-hero.png",
      alt: "Leiden canals and university quarter — expat city snapshot",
    },
    tags: ["Research", "Students"],
    intro: "Canals + university energy; splits toward Hague or Schiphol.",
    bestFor: "Research, life sciences, academic households.",
    tradeoffs: ["Student cycles spike demand — time your search."],
    nextLinks: [
      { href: "/netherlands/leiden/", label: "Leiden city guide" },
      { href: R.healthcareAllowance, label: "Healthcare allowance estimator" },
    ],
  },
  {
    id: "p-delft",
    name: "Delft",
    guide: { href: "/netherlands/delft/", label: "Delft city guide" },
    accent: "teal",
    heroImage: {
      src: "/images/heroes/delft-expat-city-hero.png",
      alt: "Delft historic centre and canals — expat city snapshot",
    },
    tags: ["TU", "Quiet"],
    intro: "Quiet daily life between Rotterdam and The Hague.",
    bestFor: "TU-linked tech; bikeable routines.",
    tradeoffs: ["Low-key evenings — big nights = train to Rotterdam or The Hague."],
    nextLinks: [
      { href: "/netherlands/delft/", label: "Delft city guide" },
      { href: R.utilities, label: "Utilities comparison" },
    ],
  },
  {
    id: "p-groningen",
    name: "Groningen",
    guide: { href: "/netherlands/groningen/", label: "Groningen city guide" },
    accent: "fuchsia",
    heroImage: {
      src: "/images/heroes/groningen-expat-city-hero.png",
      alt: "Groningen northern city centre — expat city snapshot",
    },
    tags: ["North", "Student"],
    intro: "Northern hub; student pulse; self-contained job market.",
    bestFor: "Northern careers, academics, anti-Randstad churn.",
    tradeoffs: ["Distance to western HQs & Schiphol — fine if work is local."],
    nextLinks: [
      { href: "/netherlands/groningen/", label: "Groningen city guide" },
      { href: R.costOfLiving, label: "Cost of living" },
    ],
  },
  {
    id: "p-breda",
    name: "Breda",
    guide: { href: "/netherlands/breda/", label: "Breda city guide" },
    accent: "cyan",
    heroImage: {
      src: "/images/heroes/breda-expat-city-hero.png",
      alt: "Breda historic centre in North Brabant — expat city snapshot",
    },
    tags: ["Brabant", "Space"],
    intro: "Brabant mid-size; approachable pace, southern links.",
    bestFor: "Cross-border commuters; space-first households.",
    tradeoffs: ["Some sectors stay Randstad-heavy — verify local hiring."],
    nextLinks: [
      { href: "/netherlands/breda/", label: "Breda city guide" },
      { href: R.cityComparison, label: "City comparison tool" },
    ],
  },
];
